### ISSUE TITLE
Jenkins master is not able to deploy agents

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-core#1000]
**Describe the bug**
After a pipeline is created and/or executed Jenkins is not able to successfully run the an ODS jenkins agent.

This is happening when using a Jenkins master build with the code from ods-core, master branch into Openshift 3.11

**To Reproduce**
1. Install ODS from master branch into Openshift 3.11
2. Create a new project
3. Add Quickstarters into the new project
4. See the issue in the pipelines

**Expected behavior**
To successfully run the ODS pipelines

**Screenshots**
![image](https://user-images.githubusercontent.com/26645694/125285512-04dac380-e31b-11eb-8b78-c9c6a7401280.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack master

**Additional context**
One thing we have found is that in the pod yml, the node selector is diferent from the one used in ODS 3.x and is the cause of this issue

**ODS 3.x**
```
nodeSelector:
    beta.kubernetes.io/os: linux
```

**ODS master**
```
nodeSelector:
    kubernetes.io/os: linux
```

**Comment by felipecruz91** [comment]
OpenShift 3 is based on an older version of Kubernetes, which is not anymore directly supported since Kubernetes plugin version 1.26.0.

To get agents working for Openshift 3, add this Node Selector to your Pod Templates:

beta.kubernetes.io/os=linux


Source: https://plugins.jenkins.io/kubernetes/

**Comment by braisvq1996** [comment]
If we make use of a lower version of the Kubernetes plugin there are other plugins that need to be downgraded as well

![image](https://user-images.githubusercontent.com/26645694/125408530-4ae76400-e3bb-11eb-9bbe-41234179f593.png)

**Comment by braisvq1996** [comment]
For what I have seen there are 3 plugins needed to be changed/added for the pipelines to work:

**Kubernetes**  version _1.25.2_ (downgrade from _1.29.7_)
**Openshift Sync** version _1.0.45_ (downgrade from _1.0.46_)
**Pipeline Utility Steps** version _2.5.0_ (was installed in ODS 3 but not for ODS 4 )

**Comment by clemensutschig** [comment]
@braisvq1996 install all them - and see if it works (what you can do - is to first install them via marketplace) and try this way ...

**Comment by clemensutschig** [comment]
why don't we try with the ocp4 piece(s) on 3 ... maybe they have backwards compatibility?

**Comment by braisvq1996** [comment]
Yeah, I have install the 3 of them in my Jenkins and now the pipelines works, I was able to run the quickstarter pipeline and the component pipeline successfully

**Comment by braisvq1996** [comment]
> why don't we try with the ocp4 piece(s) on 3 ... maybe they have backwards compatibility?

At least the kubernetes plugin version we currently use for ODS 4 and Openshift 4 does not work in Openshift 3 as Felipe mention here: https://github.com/opendevstack/ods-core/issues/1000#issuecomment-878238468

And this also force us to change the version of another plugin, Openshift Sync, as mentioned here: https://github.com/opendevstack/ods-core/issues/1000#issuecomment-878842273

Aside of the 3 plugins mentioned until now we did not see other issues in the other plugins for now

**Comment by clemensutschig** [comment]
hmmm - that would mean ods 4 will only certify on ocp4 - or do we introduce 2 images .. (that you build with a flag ... ?!

**Comment by braisvq1996** [comment]
well, we already have 2 dockerfiles for Jenkins master and agent base and acording to ODS, one should be used for Openshift 3 and the other for Openshift 4

https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L186

**Comment by braisvq1996** [comment]
Even if I mannually add the plugins into Jenkins, if the pod restart Kubernetes and openshift-sync are restored to the version that do not work in OCP 3

**Comment by michaelsauter** [comment]
@braisvq1996 You'd need to update the plugins in the image itself. See https://github.com/opendevstack/ods-core/blob/master/jenkins/master/ods-run.sh#L53-L91 for an explanation.

**Comment by braisvq1996** [comment]
I have been running some test last week and if we add the plugins version here in the file [plugins.txt](https://github.com/opendevstack/ods-core/blob/master/jenkins/master/plugins.txt) it will work.
The only problem is that this file is currently been used when instaling ODS into OCP 3 and OCP 4.

To solve it we can have 2 of these files, each been used by one of the Dockerfiles.
With that we have the correct plugins version in OCP 3 and the latest available for  OCP 4

I will prepare a PR for 4.x and master branches

@michaelsauter @clemensutschig @metmajer @felipecruz91

**Comment by metmajer** [comment]
Very cool @braisvq1996

**Comment by braisvq1996** [comment]
PR for [master](https://github.com/opendevstack/ods-core/pull/1020) and [4.x](https://github.com/opendevstack/ods-core/pull/1019) branches merged
So I will close this issue

**Comment by s2oBCN** [comment]
> Due to the change applied in #1023 we are not able to deploy agents again in our ODS 4 instalation
> 
> This is because of the version of the Kubernetes plugin
> 
> @clemensutschig @metmajer @michaelsauter

I'll create a PR to revert this change https://github.com/opendevstack/ods-core/pull/1023 and at the same time apply the correct versions of the plugin for an ODS box when building the ODS box.

**Comment by michaelsauter** [comment]
Hmm, #1023 changes the `rhel7` variant. Did you install ODS 4 in OpenShift 3? Or do you have issues in an OpenShift 4 cluster?

**Comment by s2oBCN** [comment]
I've created this PR https://github.com/opendevstack/ods-core/pull/1038

**Comment by braisvq1996** [comment]
> Hmm, #1023 changes the `rhel7` variant. Did you install ODS 4 in OpenShift 3? Or do you have issues in an OpenShift 4 cluster?

It is an instalation of ODS 4 into Openshift 3

The main problem now is that the Jenkins version that comes with centos based images is to low for the kubernetes plugin we use in rhel based images

**Comment by braisvq1996** [comment]
After we updated the ODS 4 instalation with the fix added by @s2oBCN we are able to deploy agents again so I will close this issue
