### ISSUE TITLE
extend provisioning app configuration to allow to enable single page client

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#1009]
**Is your feature request related to a problem? Please describe.**
The provisioning app delivers two types of front-ends.
One front-end is server-side template client and it is the default one. 
The second one front-end is a single-page client.
This feature request is about extending the provisioning app configuration to allow deployers to enable the single-page client in provisioning app.

The idea is to add a parameter in the ods configuration sample that allow deployers to activate the single-page client by setting the value to `true`.

**Comment by metmajer** [comment]
@stitakis existing end-to-end tests might depend on the existing UI.

FYI @jorge-romero @s2oBCN @jafarre-viewnext @hrcornejo

**Comment by metmajer** [comment]
@stitakis can you please put this into a release beyond ODS 4.0? We had planned to cut a release in the next days and I would not like to introduce extra dependencies at this point in time.

**Comment by stitakis** [comment]
@metmajer @jorge-romero yes, I'll move it to a future release. btw, the default value is `false`, means the current FrontEnd will be enabled by default.

**Comment by stitakis** [comment]
@metmajer we need this feature at BIX. It is not a disrupting one. The default is `false`. It means, it doesn't affect current behavior, which is tested anyway in ODS build.
