### ISSUE TITLE
Bring updates from Github to Bitbucket instances

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#102]
When there is an update to ODS on Github, consumers of ODS should receive those updates or at least be notified about them ... what could we use to do this?

**Comment by gerardcl** [comment]
We could use a mailing list where users/consumers should sign in for feedback (a mailing list with no-reply option) and feedback from users/consumers should come as issues in github.
This is going on the direction of creating a newsletter service.
Thinking about OS solutions like [mailman](http://www.gnu.org/software/mailman/index.html)

**Comment by michaelsauter** [comment]
Oh the issue here is about automatically syncing teh repos in your BitBucket instance with the ones on GitHub ... so not really solvable with a mailing list :)

**Comment by gerardcl** [comment]
Ouch! understood!

Then...a proposal --> what about providing/implementing a service that triggers forked repos' updates (via polling maybe better...so to assure any cluster can reach github)? 

Such polling service could be a simple service running in all/any clusters running ODS via a fork (public or private) on the CD namespace in OC. So, a possible workflow of such service could be:

1- first time/ initial configuration has as origin ods github (but could be edited...so to add credentials if required) project and destination points to the fork with the right credentials. It could handle different branches or tags as a list of the branches to update (default only master, but configurable)

2- every X hours (configurable param) the service executes wether a forced or not (configurable param) git fetch and merge (or reset) and push

3- send a notification of the defined users of that cluster if any changes with the changes

Note: this should follow the workflow defined in --> https://www.opendevstack.org/doc/development-guide#opendevstack-branching-flow-for-contributions

By the way, I found out that bitbucket server is already providing such feature --> https://confluence.atlassian.com/bitbucketserver/keeping-forks-synchronized-776639961.html

**Comment by stitakis** [comment]
@gerardcl proposal looks good to me... as you proposed "polling service" (from consumer interested in github project) looks to me the integration pattern that match this scenario. I would add another rule...  polling service should poll only versions that passed some quality checks... with this in mind... the polling service could checkout latest version on new changes to trigger a CI/CD of ODS... pipeline latest steps would be the push to BitBucket instances... just some thoughts :-)

**Comment by gerardcl** [comment]
I was thinking more on a simple service implementation like webhook-proxy service. But yes! Definitely once we have a test for that we could enable it in such github-fork-sync service!

**Comment by gerardcl** [comment]
Also taking into account that as a starting point it should be kept only the trust on the main origin (gh ods), a release is stable but not master. Taking such assumption a test might not be required indeed, but only assure that the sync is robust.

**Comment by michaelsauter** [comment]
I am not convinced that the problem described here is big enough that we should address it in a way like described above. 

The "problem" will not exist for many users of ODS, since typically, you stay on one, officially released, version, until you intentionally upgrade. The "problem" only exists for users of ODS wanting to be on the bleeding edge. 

My take on this is, that, unless we find a VERY simple solution, we do nothing. Potentially we could make a script that updates your repos that developers how want to contribute to ODS can use. But I'm not sold on this either yet ...

**Comment by stefanlack** [comment]
I agree with @michaelsauter . 

IT's not a big deal to merge changes from one remote to a local repository. The uses may decide if and at what time he wants to merge changens and he do not need this merges very often for a stable production environment.

**Comment by michaelsauter** [comment]
@stefanlack Cool. I actually made a script to do the sync once, right now it lives at https://github.com/opendevstack/PMC/pull/13. Not sure what to do. At the moment I am contemplating to make a `tools` dir in `ods-core` and put all sorts of helpers in there ...

**Comment by metmajer** [comment]
Since a multitude of small changes needed to be made and applied to various environments during the recent release, I plan to have such functionality made available rather sooner than later to improve reduce errors and improve our experience during a release event. I'll keep you posted about any advancements in this area here.

@michaelsauter Instead of having a collection of scripts in tools, why not wrap them into use-cases in a Makefile, such as `make release`. This would be my preferred approach.

**Comment by michaelsauter** [comment]
@metmajer I like the Makefile suggestion. Please also see #207, which is yet another thing which we should "script" / have a tool for.

**Comment by metmajer** [comment]
Awesome, I'll collect that together and share some thoughts timely. Cheers!

**Comment by clemensutschig** [comment]
@michaelsauter  - with the new installation and repos.sh - much of this is there - do we need more?!

**Comment by michaelsauter** [comment]
Yea let's close this. If some part is not done yet, we should open a new, more focused issue.
