### ISSUE TITLE
make is missing from Jenkins agent images in OpenShift 4

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#1025]
**Describe the bug**
@renedupont figured out that `make` is missing in the Jenkins agent images in OpenShift 4. However, `make` is present in OpenShift 3. We concluded that the base image provided by RedHat must differ: RHEL7 provides `make`, while the UBI8 one does not (see https://catalog.redhat.com/software/containers/openshift3/jenkins-2-rhel7/581d2f4500e5d05639b6517b?container-tabs=packages&gti-tabs=registry-tokens vs https://catalog.redhat.com/software/containers/openshift4/ose-jenkins/5cdd918ad70cc57c44b2d279?container-tabs=packages&gti-tabs=registry-tokens) 

While ODS does not claim that `make` is installed in the agent image, some projects might depend on it and might be surprised when they switch to OpenShift 4.

**To Reproduce**
Try to invoke `make` from `Jenkinsfile`.

**Expected behavior**
`make` should be installed.

**Affected version (please complete the following information):**
 - OpenShift: 4.0+
 - OpenDevStack: 3.x, 4.x, master

**Additional context**
The same might be true for other packages?

FYI @renedupont @felipecruz91

**Comment by felipecruz91** [comment]
All PRs have been merged, @michaelsauter feel free to close the issue
