### ISSUE TITLE
VS Code in EDP Box freezes

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-core#1032]
**Describe the bug**
The installed version of VS Code in EDP Box freezes. It has already been reported in the official repo https://github.com/microsoft/vscode/issues/119931.

**To Reproduce**
1. Launch an EDP Box (3.x) in AWS.
2. Launch VS Code.
3. See how it freezes.

**Expected behavior**
VS Code to run fine and **not** freeze.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.x

**Additional context**
The fix seems to have been released in the VS Code **Insiders** version. Therefore, the workaround for now is to run the following commands in EDP in a Box:

```cli
# Download latest version of VS Code Insiders (code-insiders-1.60.0 as of today)
wget https://az764295.vo.msecnd.net/insider/5f19eee5dc9588ca96192f89587b5878b7d7180d/code-insiders-1.60.0-1629829691.el7.x86_64.rpm

# Install the pkg
sudo rpm -i code-insiders-1.60.0-1629829691.el7.x86_64.rpm
```

Launch VS Code **Insiders**:

![image](https://user-images.githubusercontent.com/15997951/130778537-af52b9d7-50eb-4780-9f47-ac4cb5def950.png)

![image](https://user-images.githubusercontent.com/15997951/130779318-bfa61ecf-83a3-475f-ad76-e769d0f85a2a.png)

/cc @metmajer

**Comment by metmajer** [comment]
Cheers @felipecruz91, that's very useful. @s2oBCN do you want to take care of the fix?

**Comment by s2oBCN** [comment]
> Cheers @felipecruz91, that's very useful. @s2oBCN do you want to take care of the fix?

I have this running, with a workaround,  installing VS with https://snapcraft.io/code

**Comment by s2oBCN** [comment]
Insiders is for early adopters... I'd wait

**Comment by metmajer** [comment]
@s2oBCN I'd agree, but we use box instances to have internal teams develop their own Quickstarters. Without a working IDE this won't be possible. Is Insiders so early that it can't be used effectively? Do you know of a better way to solve the problem with VS Code?

**Comment by clemensutschig** [comment]
why don#t we install directly from github and are done with it?

**Comment by s2oBCN** [comment]
now it's working with the last odsBox
