### ISSUE TITLE
ODS in a Box creation fails due to "no space left on device"

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-core#1034]
**Describe the bug**
```
2021/09/02 00:01:20 [INFO] (telemetry) ending shell
[1;31m==> amazon-ebs: Error preparing shell script: open /tmp/packer-shell196603906: no space left on device[0m
[1;32m==> amazon-ebs: Step "StepProvision" failed[0m
[1;32m==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...[0m
2021/09/02 00:01:20 packer-builder-amazon-ebs plugin: Error asking for input: no available tty
[1;32m==> amazon-ebs: Terminating the source AWS instance...[0m
[1;32m==> amazon-ebs: Cleaning up any extra volumes...[0m
[1;32m==> amazon-ebs: Destroying volume (vol-0587ecbae5b9f0420)...[0m
[1;32m==> amazon-ebs: Deleting temporary security group...[0m
2021/09/02 00:02:21 [INFO] (telemetry) ending amazon-ebs
==> Wait completed after 2 minutes 10 seconds
2021/09/02 00:02:21 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2021/09/02 00:02:21 machine readable: amazon-ebs,error []string{"Error preparing shell script: open /tmp/packer-shell196603906: no space left on device"}
==> Builds finished but no artifacts were created.
[1;31mBuild 'amazon-ebs' errored after 2 minutes 10 seconds: Error preparing shell script: open /tmp/packer-shell196603906: no space left on device[0m

==> Wait completed after 2 minutes 10 seconds

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error preparing shell script: open /tmp/packer-shell196603906: no space left on device
```

**To Reproduce**
Check the links to the logs at https://GitHub.com/opendevstack/ods-core

**Affected version (please complete the following information):**
 - OpenDevStack 3.x and master (implies 4.x)

FYI @clemensutschig

**Comment by metmajer** [comment]
@stitakis can you please take a look?

**Comment by metmajer** [comment]
@stitakis @georgfedermann can you please advise?

**Comment by metmajer** [comment]
@clemensutschig @michaelsauter @stitakis @s2oBCN the build is broken since a week. can you please decide on some action?

**Comment by stitakis** [comment]
@metmajer @michaelsauter my apologies that I haven't noticed this earlier. I have removed the old log files and also updated the cron job that removes old log files. Retention is now 30 days. Since we are building the branch 4.x the disc space was filling up faster. There is enough disc space now. Next build should not break due this problem.

**Comment by metmajer** [comment]
Thanks @stitakis, no reason to apologise. I act persistently so we don't overlook the issue and our development team can stay current.

**Comment by clemensutschig** [comment]
@stitakis still red.. my gut feeling is the box Storage too small

**Comment by s2oBCN** [comment]
Now it's red becuase we need this change: https://github.com/opendevstack/ods-quickstarters/pull/646

**Comment by s2oBCN** [comment]
Now it's failing after 4h... , almost at the end, because of a test:
![image](https://user-images.githubusercontent.com/3382436/133035844-ac4c7f0d-b42f-4422-a3cd-f305b4dc8ad3.png)

Do you know why? because there's no more info. Otherwise I can investigate the test.

**Comment by clemensutschig** [comment]
@s2oBCN  - go into the logs - and search for this .. you'll see what's going on ...

**Comment by clemensutschig** [comment]
ok we found it - URL has changed for acceptance tests .. @s2oBCN  - you also need to fix this for e2e-spock*

**Comment by s2oBCN** [comment]
Fianlly working! :)

**Comment by metmajer** [comment]
@s2oBCN Wohoo :)

**Comment by clemensutschig** [comment]
hopefully the next run catches it - then we can backport

**Comment by clemensutschig** [comment]
Awesome... so you backport?

**Comment by s2oBCN** [comment]
> it - then we can backport

yes

**Comment by stitakis** [comment]
closing, odsbox master build is running successful again.
