### ISSUE TITLE
Latest ods-ci (master/4.x) is broken with "UnsupportedOperation: Encrypted snapshots can���t be shared public"

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#1062]
**Describe the bug**
Start a CI build from master/4.x: at the end of the build /which is successfull - the ami can't be update with

```
19:28:14  ==> amazon-ebs: Destroying volume (vol-0a1a893e022c999e3)...
19:28:14  ==> amazon-ebs: Deleting temporary security group...
19:28:14  Build 'amazon-ebs' errored after 5 hours 25 minutes: Error modify AMI attributes: UnsupportedOperation: Encrypted snapshots can���t be shared publicly. Specify another snapshot.
19:28:14  	status code: 400, request id: 7eef6e74-0cf4-4e7f-a421-6d63df53b335
19:28:14  
```

so looks like we cannot make this public?! @stitakis 

Looks like something changed on AWS?! ... the public part is at https://github.com/opendevstack/ods-core/blob/master/ods-devenv/packer/CentOS2ODSBox.json#L23-L25

**Comment by stitakis** [comment]
@clemensutschig I have removed public fix in branch `feature/ods-devenv`. The build is running now. Let see if this fix the problem.

**Comment by stitakis** [comment]
I'll close it once the builds run successful
