### ISSUE TITLE
SonarQube: update javascript and typescript version support

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-core#1073]
**Is your feature request related to a problem? Please describe.**
The current version only supports a typescript version> = 3.2.1 <3.8.0. At this point in time, version 4.5.2 is the latest Typescript version.

**Describe the solution you'd like**
Support latest javascript (ECMAScript 2020) and typescript (v4.x) version 

**Describe alternatives you've considered**
N/A

**Additional context**
- The used typescipt plugin `sonarqube-typescript-plugin` is archived: https://github.com/SonarSource/SonarTS
- The javascript plugin `sonarqube-javascript-plugin` is the official successor: https://github.com/SonarSource/SonarJS

**Comment by gerardcl** [comment]
will be fixed by https://github.com/opendevstack/ods-core/pull/1096 - that will come in ODS 4.2.0 release
