### ISSUE TITLE
Webhook proxy replaces all occurrences of project ID in build pipeline name

### ISSUE THREAD

**Issue by albertpuente** [opendevstack/ods-core#1078]
**Describe the bug**
When components have names which include the project ID, the code removes it from the Jenkins build name. This may lead to multiple components having the same build pipeline in Jenkins.

**To Reproduce**
For instance, in a project called mlops, Have a component named mlops-pipeline and another called mlops-mlops-pipeline.
Build pipelines for both components will both be named pipeline, appearing as one in Jenkins.

**Expected behavior**
Build pipelines for both components should be named pipeline and mlops-pipeline respectively.

**Affected version (please complete the following information):**
 - OpenDevStack 4.x

**Additional context**
See https://github.com/opendevstack/ods-core/blob/cbd094e123b0bbcb708bb54a1aef69ad4ff17805/jenkins/webhook-proxy/main.go#L340
Where -1 should be 1 to limit the number of replacements to just 1. There may be other places where this should be also changed.

**Comment by michaelsauter** [comment]
@albertpuente Good catch! Want to open a PR for it?

**Comment by metmajer** [comment]
FYI @hugowschneider

**Comment by michaelsauter** [comment]
I can also open a PR for this.
