### ISSUE TITLE
Problems installing locallly ODS - missing packages

### ISSUE THREAD

**Issue by jorge-romero** [opendevstack/ods-core#109]
While I was installing the enviroment, following the instructions provided it failed cause there were some missing packages that the ansible playbooks didn't install and I was force to do it manually:

- postgresql-devel
- python-devel
- python-psycopg2
- psycopg2-binary

**Comment by michaelsauter** [comment]
@tjaeschke Can you look into this?

**Comment by tjaeschke** [comment]
> @tjaeschke Can you look into this?

I will take a look.

**Comment by tjaeschke** [comment]
This has been fixed
