### ISSUE TITLE
Issues with the PVC in Openshift 4 clusters

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-core#1092]
**Describe the bug**
The current PVCs are using access mode RWO and we have been recomended to use RWX to avoid an error when the pod restarts
[Kube docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)

**To Reproduce**
1. Deploy a container with a PVC attached (access mode of the PVC to RWO)
2. re-deploy the container into a another node

**Expected behavior**
The deployment should not have any issues

**Affected version:**
 - OpenShift: 4.8
 - OpenDevStack 4.x
 
**Log Output **
```
Multi-Attach error for volume "pvc-XXXX-ZZZZ" Volume is already exclusively attached to one node and can't be attached to another
```

**Additional context**
[Where we may need to make the Changes](https://github.com/opendevstack/ods-core/search?l=YAML&q=ReadWriteOnce)

**Comment by metmajer** [comment]
@braisvq1996: note that @jorge-romero recently had an issue deploying our sock shop demo application because of a PVC issue. Note sure if that was the same error though.

**Comment by gerardcl** [comment]
I would not change to RWX since you want to ensure the rollout is successfully shutting down previous instances. Are we sure this error is related to the premission set and maybe rather related to the storage class type?

**Comment by michaelsauter** [comment]
> I would not change to RWX since you want to ensure the rollout is successfully shutting down previous instances.

IIRC RWX wasn't used in the past because it wasn't possible? For some (many?) rollouts it would be nice if it can be a rolling update instead of a restart. But it would require looking into all deployments whether this is safe or not ...

**Comment by braisvq1996** [comment]
This is what was suggested to us by our Openshift support team.
Of course I did not had the time to go in depth for this issue but I will once we close the urgent tasks at hand.

**Comment by braisvq1996** [comment]
Closing this as it was an issue with the backend for the storage in OCP4
