### ISSUE TITLE
Jenkins agent base fails to build

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-core#1093]
**Describe the bug**
We have tried to build the jenkins agent base and we have seen that it fails due to centos mirros

**To Reproduce**
1. Go to build jenkins agent base from 4.x or master branch
2. See error

**Expected behavior**
Jenkins agent build should not fail

**Affected version (please complete the following information):**
 - OpenShift: 4.8
 - OpenDevStack 4.x and master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
STEP 9: RUN yum -y install make glibc-langpack-en openssl     && yum clean all     && rm -rf /var/cache/yum/*
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
CentOS-8-BaseOS                                  39 kB/s | 8.1 kB     00:00
Failed to set locale, defaulting to C.UTF-8
Errors during downloading metadata for repository 'centos-baseos':
  - Status code: 404 for http://mirror.centos.org/centos/8/BaseOS/x86_64/os/repodata/repomd.xml
Error: Failed to download metadata for repo 'centos-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
error: build error: error building at STEP "RUN yum -y install make glibc-langpack-en openssl     && yum clean all     && rm -rf /var/cache/yum/*": error while running runtime: exit status 1
```

@gerardcl

**Comment by braisvq1996** [comment]
We need to also apply this change into 3.x branch as the Continous tests are failing due to this

**Comment by tbugfinder** [comment]
How about dropping use of CentOS8 repos and replacing those using ubi.repo ?

**Comment by gerardcl** [comment]
this afternoon I will provide a fix for this issue since we still see errors that make the builds unstable. the fix for ubi8 dockerfile will be like:

```
...
# Add UBI repositories.
COPY yum.repos.d/ubi.repo /etc/yum.repos.d/ubi.repo
RUN cd /etc/yum.repos.d && rm -r localdev-* ci-rpm-mirrors.repo \
    && yum -y install make glibc-langpack-en openssl \
    && yum clean all \
    && rm -rf /var/cache/yum/*
...
 yum install -y skopeo
....
```

it should also fix unstability related to recently created issues:
- https://github.com/opendevstack/ods-quickstarters/issues/720
- https://github.com/opendevstack/ods-quickstarters/issues/721
- https://github.com/opendevstack/ods-quickstarters/issues/722
- https://github.com/opendevstack/ods-quickstarters/issues/723
- https://github.com/opendevstack/ods-quickstarters/issues/725
