### ISSUE TITLE
Problems installing locallly ODS - cannot build jenkins master, slave, etc due to a github connection problem

### ISSUE THREAD

**Issue by jorge-romero** [opendevstack/ods-core#110]
I get always the error.

```
Cloning "https://github.com/opendevstack/ods-core.git " ...
  error: fatal: Couldn't find remote ref production
  Unexpected end of command stream
```

Enviroment: 
- Windows 10 with hyperV deactivated, using Virtualbox
- 24GB of RAM

I have check this:
- [x]  Clone the repository from the windows desktop [Works]
- [x] Clone the repository in the minishift VM [Works]
- [x] Clone the repository in a Docker container created in the minishift VM [Works]
- [x] Clone the repository in the container launched to build the jenkins one -> It downloads only the 50%-70% of the content
In the last case I get a bash console inside the container, and if I manually try to get the repository it get slower in the middle of the process and at the end fails  f.e.:
```
[root@jenkins-slave-base-3-build home]# git clone https://github.com/opendevstack/ods-core.git
Cloning into 'ods-core'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (23/23), done.
Receiving objects:  52% (516/988), 3.38 MiB | 155.00 KiB/s
```

**Comment by clemensutschig** [comment]
right now there is a very hard dependency onto bitbucket - you first needs to clone (and push the repos into your local bitbucket install) - and ensure you have the configuration right. then you need to run tailor in the various pieces (as written in the installation guide)

**Comment by jorge-romero** [comment]
Currently I'm on the **"Prepare CD project for Jenkins"** doing the task 
- Start jenkins slave base build: oc start-build -n cd jenkins-slave-base

Then if I check the in the minishift console the status of the build I go after a few minutes the error:
```
  Cloning "https://github.com/opendevstack/ods-core.git " ...
  error: fatal: Couldn't find remote ref production
  Unexpected end of command stream
```

**Comment by clemensutschig** [comment]
@jorge-romero  - you need to push this into an "local" bitbucket and create a `production` branch from master ... (which is actually your local "productive" version") .... 

<pre>
On the Project Dashboard Navigate to the “Settings” menu and grant the group “opendevstack-users” admin access.

Navigate to the ods-core/infrastructure-setup/scripts directory and execute mirror-repos.sh

Use your crowd login when asked for credentials. Verify that you have mirrored the github repos and that they have been populated in your Bitbucket instance. The ods-configuration repositpory will remain empty.

Setup project branch permissions - production should be guarded against direct merges except through admins
</pre>

**Comment by clemensutschig** [comment]
so - to fix this - push the repo to your bitbucket installation, and create a production branch - works :)

**Comment by jorge-romero** [comment]
Thansks, I have point to the local repo that already had the project mirrored and I changed the url in the build configs and it start working

**Comment by clemensutschig** [comment]
@jorge-romero - if there is something missing in the doc - please file a bug against https://github.com/opendevstack/opendevstack.github.io - and best case contribute the changes :)
