### ISSUE TITLE
clarify contribution guide, lifecycle of master and "released" branches

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-core#1105]
**Is your feature request related to a problem? Please describe.**
I couldn't find a doc how the project organizes in regards to released branches 1.x, 2.x, 3.x, 4.x in ods-core and on all additional repos. Some contributions (PRs) go directly into master, some get merged in addition into e.g. 4.x and some are only e.g. 4.x.

**Describe the solution you'd like**
A documentation which explains the different branches (btw. it looks like some could be removed) and their status and a project planning table would be helpful. This could e part of a contribution guide which I might just have missed. It could be referred in the README.md though.

**Describe alternatives you've considered**
Just not to contribute or ask within PRs.

**Additional context**
Maybe I just didn't find the appropriate readme.

**Comment by metmajer** [comment]
Hello @tbugfinder! We handled things differently in the past, but this is how we're working today:

- `master` is the integration branch on every repo.
- PRs go into master and into the existing release branches _that require_ this change. Usually, the current version, sometimes a version before, depending on the importance of the fix and provided that the older version is still in use of course. This way, we keep existing releases up to date with important fixes or features.
- When creating a new release, a new release branch is created based off of `master`. This way, every new release is always based on our integration branch.

Any further comments @michaelsauter ?

**Comment by michaelsauter** [comment]
@metmajer No further comments.

There is some documentation on the release process at https://github.com/opendevstack/PMC/blob/master/releases.md. I think it is still accurate (however not everything in that repo is)
