### ISSUE TITLE
ODS E2E tests failing because go dependency go junit report expected version disapperead

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#1122]
ODS E2E tests failing because go dependency go junit report expected version disappeared.

The go dependency go-junit-report in the expected version with tag `0.8.9` is not available anymore. It looks like the repository owner removed the tag in the github repository (https://github.com/jstemmer/go-junit-report)

This is impacting branches `master` and `4.x`

logs
```
06:48:33  ==> amazon-ebs: which: no go-junit-report in (/usr/local/bin:/usr/bin:/home/openshift/bin:/home/openshift/go/bin)
06:48:37  ==> amazon-ebs: go: github.com/openshift/api@v0.0.0-20180801171038-322a19404e37: stream error: stream ID 7; INTERNAL_ERROR; received from peer
06:48:37  ==> amazon-ebs: make: *** [prep-tools] Error 1
```

Available version:
![image](https://user-images.githubusercontent.com/1012854/158126541-6e0b8e79-ed47-4f10-a3b5-a9ef8d71d97b.png)

**Comment by stitakis** [comment]
@michaelsauter would be possible to replace this dependency on source code to a published artifact instead?

**Comment by michaelsauter** [comment]
@stitakis where do you see it is expecting tag `0.8.9`? I do not find that reference ...

**Comment by stitakis** [comment]
@michaelsauter my bad, I think I was looking at an old version of the master branch. It looks like ods is using version '0.9.1'... anyway it looks to me that the dependency is missing as the logs are indicating.

**Comment by michaelsauter** [comment]
Ok odd, as that tag still exists: https://github.com/jstemmer/go-junit-report/tags. That said we could update to v1.0.0, it seems there are no actual changes: https://github.com/jstemmer/go-junit-report/compare/v0.9.1...v1.0.0.

**Comment by michaelsauter** [comment]
As discussed, I am closing this as the error seems to be elsewhere.
