### ISSUE TITLE
Provisioning of projects doesn't setup Jenkins with Aqua credentials 

### ISSUE THREAD

**Issue by cschweikert** [opendevstack/ods-core#1125]
### Description:
When provisioning a new project the new Jenkins instance in the new cd project doesn't have credentials of Aqua.

### Expected behavior:
Either the right credentials are set up in Jenkins (`Manage Jenkins > Manage Credentials > ...`) OR no implicit and automatic runs of Aqua in Jenkins pipeline.

### Affected version:
 - OpenShift: 4.8
 - OpenDevStack: 4.x

### Log Output:
```
[...]
[Pipeline] sh (Get JSON of ConfigMap/aqua)
+ oc -n ods get ConfigMap/aqua -o json
[Pipeline] echo
Please provide the alert emails of the Aqua platform!
[Pipeline] echo
Not parameter 'projects.unitt.enabled' at cluster level. Default enabled
[Pipeline] echo
[Aqua Security Scan-fe-angular-test] **** STARTING stage 'Aqua Security Scan' for component 'fe-angular-test' branch 'master' ****
[Pipeline] stage
[Pipeline] { (Aqua Security Scan)
[Pipeline] echo
Please provide the alert emails of the Aqua platform!
[Pipeline] echo
Please provide the name of the repository in Nexus to store the reports!
[Pipeline] echo
Starting to scan via Aqua CLI...
[Pipeline] withCredentials
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
[Aqua Security Scan-fe-angular-test] **** ENDED stage 'Aqua Security Scan' for component 'fe-angular-test' branch 'master' **** (took 113 ms)
[Pipeline] echo
WARN: Error with Aqua due to: org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: Could not find credentials entry with ID 'unitt-cd-aqua'
[...]
```

**Comment by cschweikert** [comment]
Another problem with this implicit runs of Aqua are the unit tests of quickstarters. They usually cross-check the names of the build steps within Jenkins pipelines and they don't know about this Aqua step yet.

**Comment by metmajer** [comment]
@braisvq1996 @gerardcl please create the maintenance project finally and add this one

**Comment by braisvq1996** [comment]
> @braisvq1996 @gerardcl please create the maintenance project finally and add this one

As soon as I finish the current task at hand I will start working on the maintenance topic.

@cschweikert as far as I know there is no issues in Aqua integration for our current ODS installation but we do not make use of credentials like "<KEY>-cd-aqua". Instead we use "cd-user-with-password"

**Comment by cschweikert** [comment]
I provisioned the given project with a *project-specific cd user*. Jenkins' credentials store also knows it under the id `unitt-cd-cd-user-with-password`. I would expect Aqua to either request for that one or I would expect the provisioning app to provision also credentials with the id `unitt-cd-aqua`, which is the id that is currently requested by Aqua (on a project with project-specific cd user).

I don't know what Aqua will do with projects that don't have a project-specific cd user. AFAIK not having a project-specific cd user is discouraged for security reasons.

**Comment by cschweikert** [comment]
Oh, I see. AFAIK the cd user credentials should not be accessible by everyone for security reasons. This is the reason for having project-specific cd users. Maybe Aqua should use a different pair of credentials that is not tied to any cd user.

**Comment by cschweikert** [comment]
I opened a PR for changing the default
