### ISSUE TITLE
ods docs generation fails due to duplicate antora configuration in master and 4.x

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-core#1187]
**Describe the bug**
Branches master and 4.x have equal antora configuration!
This "bug" was added #1168 !

ToDo:
Change of antora.yml (version, prerelease) has to be reverted in branch 4.x.

https://github.com/opendevstack/ods-core/blob/4.x/docs/antora.yml#L1-L6

FYI
@victorpablosceruelo 
@braisvq1996 

Failing GH Action:
https://github.com/opendevstack/ods-documentation/actions/runs/2886841921/jobs/4588852032

**Comment by braisvq1996** [comment]
closed with #1188
