### ISSUE TITLE
Remove sonar-crowd plugin in SonarQube

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-core#1196]
The repository for the sonar-crowd plugin was archived.
As there's no development ongoing the plugin should be removed from the tool-stack.

https://github.com/deepy/sonar-crowd/

https://github.com/opendevstack/ods-core/blob/2fcad9cb32d633eb7c50ae1802387b06e10d7338/sonarqube/docker/Dockerfile#L56

**Comment by braisvq1996** [comment]
Yes, it should be removed for the next version of SonarQube (9.x)
One option is to configure SAML with Azure instead of Crowd. LDAP is also an option see documentation [here](https://docs.sonarqube.org/latest/instance-administration/authentication/overview/)

**Comment by braisvq1996** [comment]
SonarQube new LTS version (9.9) have just been released. Once cnes-report plugin gets updated for this version we can also udpate our instances and remove Crowd plugin
