### ISSUE TITLE
webhook proxy should return build ID and offer service / api to query build status

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#120]
Needed for the release manager. @metmajer 

That way jenkins etc is completely abstracted and one can use the webhook proxy for integration.

**Comment by metmajer** [comment]
Thanks @clemensutschig.

What's the context? We are building a simple multi-repo orchestration engine that would integrate with ODS components through the webhook. Naturally, if B depends on A, we want to know that A has finished before kicking off B. Here, A could be a repo containing infrastructure as code.

**Comment by clemensutschig** [comment]
I tried it with curl

<pre>
$ curl -X POST -k https://...../oapi/v1/namespaces/ods28-cd/buildconfigs/be-docker-plain-master/webhooks/............../generic
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1583  100  1583    0     0   2110      0 --:--:-- --:--:-- --:--:--  2110{"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"be-docker-plain-master-23","namespace":"ods28-cd","selfLink":"/apis/build.openshift.io/v1/namespaces/ods28-cd/buildconfigs/be-docker-plain-master-23/instantiate","uid":"c8e9c214-85fc-11e9-9b41-0050569e63cb","resourceVersion":"129839908","creationTimestamp":"2019-06-03T12:40:36Z","labels":{"buildconfig":"be-docker-plain-master","openshift.io/build-config.name":"be-docker-plain-master","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"be-docker-plain-master",**"openshift.io/build.number":"23"**},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"be-docker-plain-master","uid":"aaf71a4d-6db1-11e9-9bbe-0050569e63cb","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"..../ods28/ods28-be-docker-plain.git","ref":"master"},"status":{"phase":"New","config":{"kind":"BuildConfig","namespace":"ods28-cd","name":"be-docker-plain-master"},"output":{}}}
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Success",
  "message": "invalid Content-Type on payload, ignoring payload and continuing with build",
  "code": 200
}

</pre>

a curl against
<pre>
 https://..../apis/build.openshift.io/v1/namespaces/ods28-cd/builds/be-docker-plain-master-23
</pre> does the rest then

**Comment by clemensutschig** [comment]
playing with this uncovered openshift/api#331

**Comment by clemensutschig** [comment]
@oalyman - can you pick this up - or wait until @michaelsauter  is back (3 weeks)

**Comment by clemensutschig** [comment]
completed looks this way

<pre>
  "status": {
    "phase": "Complete",
    "startTimestamp": "2019-02-18T17:18:20Z",
    "completionTimestamp": "2019-02-18T17:24:22Z",
    "config": {
      "kind": "BuildConfig",
      "namespace": "prov-cd",
      "name": "prov-app-test"
    },
    "output": {

    }

</pre>

**Comment by clemensutschig** [comment]
<pre>
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "builds.build.openshift.io \"prov-app-test-62\" not found",
  "reason": "NotFound",
  "details": {
    "name": "prov-app-test-62",
    "group": "build.openshift.io",
    "kind": "builds"
  },
  "code": 404
}

</pre>

**Comment by michaelsauter** [comment]
@clemensutschig @metmajer So if I understand this correctly, then you want one pipeline (the orchestrating one) to know about the status of other pipelines. If so, why should the webhook proxy answer that question? For me the proxy is simply the glue between Bitbucket and Jenkins. To me it looks like you can answer your question directly from a Jenkins pipeline as you can talk to the OpenShift API directly (via `oc` commands). Right?

**Comment by michaelsauter** [comment]
As a first step, I will work on returning the build ID, such as `be-docker-plain-master-23` when the webhook request is forwarded. Response will be:
```
{"buildId": "be-docker-plain-master-23"}
```

Next step would be to add some kind of subfolder, e.g. `/oapi/namespaces/:NAMESPACE/builds/:ID` that queries for a build status. Here I would probably just pass on whatever OpenShift returns. Sounds good?

**Comment by metmajer** [comment]
As I understood it, the webhook proxy should act as the central gateway to a Jenkins instance running on OpenShift (see Clemens' first entry). @michaelsauter then what you suggest would be very convenient. Thanks!

**Comment by michaelsauter** [comment]
I changed my mind overnight a little :) I think I will just pass through whatever response I get from OpenShift also when forwarding a webhook request...

**Comment by michaelsauter** [comment]
@clemensutschig Do we still need a way to query the build ID?

**Comment by michaelsauter** [comment]
@gerardcl OK for me. I am not sure about if this is still needed, see my last comment. Seems not to be needed for 1.2 at least ...

**Comment by michaelsauter** [comment]
Closing due to no response, please open a new issue when a further feature is required.
