### ISSUE TITLE
Removal of Centos and deprecation of ODSBox

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-core#1209]
**Is your feature request related to a problem?**
Centos7 eol will be on June 2024. up until now we have been offering both, ubi and centos but we will only continue to support ubi images from now on.

**Describe the solution you'd like**
Remove Centos images and deprecate ODSBox

**Additional context**
This is needed in order to continue with the update to nodejs18 in the quickstarters -> https://github.com/opendevstack/ods-quickstarters/pull/795

**Comment by tbugfinder** [comment]
Do we prep for ubi9 or alma9/rocky9?

**Comment by braisvq1996** [comment]
We could go with ubi9 in a separe PR. right now Python Quickstarter have already been updated to use ubi9
