### ISSUE TITLE
sonarqube image should support alternate download of Developer edition for commercial use

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#121]
https://github.com/opendevstack/ods-core/blob/master/sonarqube/Dockerfile#L26

is hardcoding the opensource version .. this should be tweakable to the commercial version .. the only difference is the path .. for commercial it's "CommercialDistribution/sonarqube-developer" vs free being "Distribution/sonarqube/"

**Comment by clemensutschig** [comment]
@stitakis - fyi

**Comment by stitakis** [comment]
@clemensutschig @michaelsauter I think this requirement is already implemented in master: https://github.com/opendevstack/ods-core/blob/6654ee044617eab9a74995bff6ebe5fc6a8fc488/sonarqube/Dockerfile#L25, is this what you mean? Do you we need to port it to ODS 1.2.0?

**Comment by michaelsauter** [comment]
@stitakis If it is in `master`, it will automatically end up in `1.2.0`.

**Comment by michaelsauter** [comment]
Closing - please reopen if you think this is not done.
