### ISSUE TITLE
Automated nexus resource setup fails with Nexus latest image

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-core#131]
There is a change in the latest Nexus image (3.17.0), released 2 days ago.
There is no longer a static default admin password, but a generated password instead, located at 

/nexus-data/admin.password

It can be retrieved on the console via 

oc rsh -n cd $(oc get pods -n cd | cut -d" " -f1 | grep "nexus") cat /nexus-data/admin.password

The scripts have to be modified, so the generated password will be used

**Comment by rattermeyer** [comment]
Think we should fix the versions of tools we are using and not relying on "latest" or a varying tag.
Latest is annoying if you want to support software and a stable documentation.

**Comment by tjaeschke** [comment]
We will open a new issue for a fixed version

**Comment by stefanlack** [comment]
see #156
