### ISSUE TITLE
Latest master (webhook proxy) breaks during build

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#151]
https://github.com/opendevstack/ods-core/blob/master/jenkins/webhook-proxy/Dockerfile#L12

---> 50cddee4a8a0
--
  | Removing intermediate container fee9470db878
  | Step 5/11 : COPY pipeline.template.json /home/webhook-proxy/pipeline.template.json
  | error: build error: lstat pipeline.template.json: no such file or directory

no wonder ... 

template is now called '.tmpl'

**Comment by ungerts** [comment]
@michaelsauter fixed it and tested container build (#152)

**Comment by michaelsauter** [comment]
😞 Sorry! I tested the thing before I renamed it ... thanks for fixing @ungerts!
