### ISSUE TITLE
Remove project param from webhook proxy

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#162]
Talking with @cschweikert about the proxy, we realised that we should remove the `project` param from the webhook proxy request payload (both for `/build` and `/` endopoints), and instead extract this information from the namespace in which the webhook proxy runs. This prevents webhooks from other BitBucket spaces ... 

FYI @ungerts @metmajer Any objections? I assume not, but wanted to communicate this (master-breaking) change upfront.

I'll implement this shortly.

**Comment by metmajer** [comment]
No, this is definitely a good idea!

**Comment by tjaeschke** [comment]
+1

Von: Michael Sauter <notifications@github.com>
Gesendet: Donnerstag, 25. Juli 2019 13:21
An: opendevstack/ods-core <ods-core@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [opendevstack/ods-core] Remove project param from webhook proxy (#162)


Talking with @cschweikert<https://github.com/cschweikert> about the proxy, we realised that we should remove the project param from the webhook proxy request payload (both for /build and / endopoints), and instead extract this information from the namespace in which the webhook proxy runs. This prevents webhooks from other BitBucket spaces ...

FYI @ungerts<https://github.com/ungerts> @metmajer<https://github.com/metmajer> Any objections? I assume not, but wanted to communicate this (master-breaking) change upfront.

I'll implement this shortly.

**Comment by michaelsauter** [comment]
Cool. I will also create a PR to 1.0.x I think, since for BitBucket payloads the "compatibility break" should not be noticed ...

**Comment by ungerts** [comment]
+1
