### ISSUE TITLE
rundeck installation failed

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#165]
When running local OpenDevStack installation (executed today using branch master),  script _setup-local-environment.sh_ failed to install rundeck.

> TASK [modified.neel.rundeck : Redhat | get rundeck rpm] ***************************************************************************************************************************
fatal: [atlassian]: FAILED! => {"changed": false, "changes": {"installed": ["rundeck-config-2.11.8-1.59.GA", "rundeck-2.11.8-1.59.GA"]}, "msg": "Error: Package: rundeck-2.11.8-1.59.GA.noarch (rundeck-release-bintray)\n           Requires: rundeck-config\n           Available: rundeck-config-2.0.0-1.8.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.0.0-1.8.GA\n           Available: rundeck-config-2.0.1-1.9.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.0.1-1.9.GA\n           Available: rundeck-config-2.0.2-1.13.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.0.2-1.13.GA\n           Available: rundeck-config-2.0.3-1.14.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.0.3-1.14.GA\n           Available: rundeck-config-2.0.4-1.15.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.0.4-1.15.GA\n           Available: rundeck-config-2.1.0-1.16.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.1.0-1.16.GA\n           Available: rundeck-config-2.1.1-1.17.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.1.1-1.17.GA\n           Available: rundeck-config-2.1.2-1.18.GA.noarch (rundeck-release-bintray)\n               rundeck-config = 2.1.2-1.18.GA\n

etc.

> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}

>PLAY RECAP ************************************************************************************************************************************************************************

> atlassian                  : ok=89   changed=66   unreachable=0    **failed=1**    skipped=23   rescued=0    ignored=1

**Comment by stefanlack** [comment]
Temp solution:
Edit file **/etc/yum.conf** in atlassian-box and set option

> obsoletes=0

Then, run rundeck provisioning again:
> vagrant ssh atlcon -c "cd /vagrant/ansible/ && export ANSIBLE_VAULT_PASSWORD_FILE=/vagrant/ansible/.vault_pass.txt && ansible-playbook -v -i inventories/dev playbooks/rundeck.yml"

**Comment by stefanlack** [comment]
Currenty ansible yum-Task seams not to support setting obsolete - option.

Maybe we should rewrite _ods-core\infrastructure-setup\ansible\roles\modified.neel.rundeck\tasks\install_redhat.yml_, so that task uses _command_ rather than yum:

> command: yum install -y --setopt=obsoletes=0

**Comment by rattermeyer** [comment]
command is normally not a good idea. We could add the rundeck package to excluded package:
https://unix.stackexchange.com/questions/13410/how-to-block-yum-from-upgrading-obsoleted-package. Would that solve the issue?
Would simply add the line to the /etc/yum.conf before doing the installation.

As far as I understand, we have a rundeck rpm that is no longer available in the repos?
