### ISSUE TITLE
Jenkins Master not able to access Repos on self-signed Bitbucket instances

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-core#167]
Currently, jenkins master does not have the same setup as the slave to access code on self-signed bitbucket instances.
Therefore build breaks. with 

```fatal: unable to access 'https://svc-rundeck-openshift:5Ks3ZWqqgxu3bT41ONr8@bitbucket-atlassian.apps.testods.opitz-consulting.com/scm/secnd/secnd-be-spring-boot.git/': Peer's certificate issuer has been marked as not trusted by the user.```

**Comment by clemensutschig** [comment]
@rattermeyer  - do you fix this for 1.2.. the code is in slave-base

**Comment by rattermeyer** [comment]
Yes. local fix exists already. Need to create PRs. Probably beginning of next week.

**Comment by clemensutschig** [comment]
@rattermeyer  TOP! .. this is wonderfull .. :)

**Comment by clemensutschig** [comment]
@rattermeyer - sonr forget the pr please
