### ISSUE TITLE
webhook proxy /build does not work in case repository has enabled bb webhook proxy

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#174]
the `/build` endpoint today - creates a pipeline in the same name format as a request coming from the "normal" bitbucket webhook.

As there is always a webhook on a repo - `/build` will never create a new pipeline as it's already there (after a push of a new branch into bitbucket, that triggers the creation of a pipeline) - so env params will never make it... (and hence you can never "really" build)

proposal is to postfix the pipeline name with `builder` in case of `/build` being called.

@michaelsauter  - cool?

**Comment by clemensutschig** [comment]
proposed fix - line 242 ff

```
// attach -builder, otherwise the "classic" webhook proxy will always win
branchName :=  req.Branch + "-builder"
pipeline := makePipelineName(req.Project, component, branchName)
```

**Comment by michaelsauter** [comment]
I agree that we need to do sth. about it. For now, I suggest to set the `component`, which also solves the problem.

I am not sold on your idea yet because it orevents people from triggering an existing pipeline via `/build`  ...

**Comment by clemensutschig** [comment]
I am confused.. whats the difference between your Proposal and meine..  ? Both Change the Name..  ;-)

**Comment by clemensutschig** [comment]
@michaelsauter can you doc this and the close this ... ;)

**Comment by michaelsauter** [comment]
@clemensutschig I will - it's on my list!
