### ISSUE TITLE
Add support for SonarQube scanning to Golang quickstarter

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-core#190]
**Is your feature request related to a problem? Please describe.**
Currently, ODS does not deliver code quality metrics for Golang components since the corresponding SonarQube plugin is not available.

**Describe the solution you'd like**
Support the SonarQube scanner for Golang (via https://docs.sonarqube.org/latest/analysis/languages/go/).

**Describe alternatives you've considered**
~A clear and concise description of any alternative solutions or features you've considered.~

**Additional context**
~Add any other context or screenshots about the feature request here.~

**Comment by michaelsauter** [comment]
FYI @gerardcl

**Comment by gerardcl** [comment]
@metmajer can you also approve https://github.com/opendevstack/ods-core/pull/192 ? thanks!

**Comment by metmajer** [comment]
Done!
