### ISSUE TITLE
Get rid of oc container from rundeck

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-core#20]
Instead of using a special oc container, use the Jenkins slave base image,s o we have only one set of containerdefinitons to maintain.

**Comment by clemensutschig** [comment]
Fix will be 2fold- enhance jenkins Slave with certs and inherit for the rundeck container from it.  And overwrite the entrypoibt

**Comment by clemensutschig** [comment]
fixed and verified on our soil
