### ISSUE TITLE
Enhance quality of logging information

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-core#209]
**Is your feature request related to a problem? Please describe.**
Some script do not log, what they do, for example the sonarqube run shell script.
So in case of an error, it is often not possible to get the root cause.

**Describe the solution you'd like**
1. All scripts log at least to stdout or stderr and describe, what they do.

This relates to PR #196

**Comment by michaelsauter** [comment]
Just to add to it, I realised https://github.com/opendevstack/ods-core/blob/a72c7325a94fc77c35510481ef1119f322132c30/infrastructure-setup/scripts/prepare-openshift-cluster.sh does not use `set -eux` ... this should also be present in all scripts.

**Comment by michaelsauter** [comment]
@tjaeschke Could you do some work related to this for version 2?

**Comment by michaelsauter** [comment]
Closing as this issue is too broad. If we find a concrete script which logs too little, let's open an issue for that.
