### ISSUE TITLE
Remove image trigger from Jenkins master instances

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#210]
**Is your feature request related to a problem? Please describe.**
With lots of Jenkins master instances in one cluster, having an image trigger leads to lots of re-deployments at the same time. This can have an impact on cluster performance.

**Describe the solution you'd like**
It might be better to remove the trigger and provide tooling instead to rollout new versions in batches instead of all-at-once.

**Describe alternatives you've considered**
None - potentially there is something in OCP that can stagger the image trigger?

**Additional context**
Also, not tracking the `latest` tag will help ...

**Comment by clemensutschig** [comment]
done - see 
https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/deploy/jenkins-master.yml#L250
