### ISSUE TITLE
auth proxy related shared-images cleanup

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-core#215]
**Is your feature request related to a problem? Please describe.**
This is a followup activity from https://github.com/opendevstack/ods-project-quickstarters/issues/424 

**Describe the solution you'd like**
The idea is to clean shared-images since `nginx-authproxy`is not required anymore. Only `RShiny` and `Jupyter` quickstarters were having it as a dependency (sidecar auth-proxy).

**Describe alternatives you've considered**
To keep it --> out of scope if really not required

**Additional context**
Review any other dependency and update documentations

**Comment by gerardcl** [comment]
@michaelsauter @kiwo @rattermeyer @henrjk @clemensutschig  can you provide feedback/thoughts?

**Comment by stitakis** [comment]
Hi @gerardcl, cleanup sounds always a good idea, specially if simplify things. Regarding auth-proxy: it looks to me like a convenient way to restrict access by default and open resource to the public. If this could be implemented as a whitelist configured by environment variables in deployment configuration would be perfect

**Comment by gerardcl** [comment]
Hi @stitakis, I am not sure if I got your suggestion, but I am also agreeing to the fact of cleaning up if not anymore required.
Regarding access restriction: the openshift/oauth-proxy handles that (and the current implementation does it also by default in the current provided deployment configuration).
What do you mean by whitlisting in environment variables?

**Comment by gerardcl** [comment]
yes, to all :) 
for further understanding, please check the implementation and please read the docs (specifically here --> https://github.com/openshift/oauth-proxy#limiting-access-to-users )
