### ISSUE TITLE
Enforce limited access of Snyk

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#217]
The Snyk CLI sends the content of the dependency files (e.g. `package.json`) to Snyk. In theory, it could send much more data to Snyk (all source files), and that would be difficult to detect from network traffic. To prevent this from happening, ODS could limit access to just the dependency files. The idea would be to run the Snyk CLI under a different user which has access only to one folder. ODS would copy the dependency files to that folder prior to scanning. We need to test if Snyk still works with this setup, but I would assume it does not need the rest of the source code ...

FYI @stitakis @borja44

**Comment by stitakis** [comment]
Hi @michaelsauter @borja44, the solution described above implies that the sources are not available when snyk cli runs. To test this I ran successfully ```snyk test``` and "snyk monitor``` commands after removing the ```src``` folder on my computer. So first test was successfull. I will do more testing and come back to you.

**Comment by michaelsauter** [comment]
@stitakis Thanks for following that up. I could not find documentation on Snyk about what access is required but I would assume that only the dependency file is needed. If not, we could ask Snyk why they need broader access.

**Comment by stitakis** [comment]
@michaelsauter I have done a test where the project is copied to a temp forder but excluding from the copy the ```src`` folder and other folders like ```build``` (list could be customized by a variable). Considering that the project layout is different for each programming language I think this approach is pragmatic and good enough to meet the requirement (avoid leaking sources or sensible information to Snyk). Following as example draft ```Makefile``` that shows the needed shell commands to implement as solution the test I did.
```
SNYKDIR := 'build-snyk-env/'

clean:
	rm -rf $(SNYKDIR)

setup_dir:
	mkdir -p $(SNYKDIR)
	rsync -av --progress . $(SNYKDIR) --exclude .git --exclude *src --exclude build
	ls $(SNYKDIR)

run_snyk:
	cd $(SNYKDIR)
	snyk auth f969a3ad-f91f-4470-aeb4-79322c57cb10
	snyk monitor -d --file=build.gradle
	snyk test -d --file=build.gradle
```
Please note that it does not setup an extra user as described above in this issue.
Would be this approach good enough?

**Comment by michaelsauter** [comment]
I was thinking of a simpler and more drastic implementation :) IIRC, you have to pass the dependency file (e.g. `build.gradle`) to the Jenkins stage. Why not simply copy just that file to that other folder?

**Comment by stitakis** [comment]
@michaelsauter  this was my first approach. To test it, I copied the ```build.gradle``` and ran snyk cli command. Unfortunatelly this didn't work because gradle needs the other gradle files contained in the project root directory. This problem leads me to the solution proposed above. I think it is a pragmatic one. Eventually the list of excluded folders could be make configurable. Should we go for the proposed solution. What do you think?

**Comment by michaelsauter** [comment]
@stitakis I would go for a whitelist approach if possible and copy only the files that are needed. Based on the input (e.g. `build.gradle`) one should be able to figure out what files are needed. I am surprised though that it needs the other Gradle files - does that mean that Snyk executes Gradle?!

**Comment by stitakis** [comment]
@michaelsauter snyk relies on the dependency management tool of each supported language. It doesn't reimplement functionality that is available in the build tool. Yes, snyk executes gradle (or maven, or npm, etc...) to get a list of all project dependencies. We could go for your approach, but we will need to define in the code which files will be copied. Ev. we could do this configurable by adding a property to the ```context```. If you agree I'll start coding this enhancement (with support for mvn, gradle, npm, go, python requirements file), what do think?

**Comment by michaelsauter** [comment]
Given that there are not that many supported languages at the moment (right?) I guess we can define in the stage which files to copy for which dependency system. If you agree that is feasible, please go ahead. I'd say initially we would not need to make this configurable - if we run into issues where projects need other files that we have not considered, we can look into this again (and users have the workaround of copying the stage available to them anyway ...)

**Comment by stitakis** [comment]
@michaelsauter @borja44 I did some progress on this. I'm currently testing it and will be ready this week.

**Comment by stitakis** [comment]
@borja44 please have a look at following code:
``` 
stage('Snyk Security Scan') {
      withEnv(["SNYK_AUTHENTICATION_CODE=${snykAuthenticationCode}", "PROJECT_NAME=${context.targetProject}",
               "COMPONENT_NAME=${context.componentId}", "BUILD_FILE=${buildFile}", "ORGANISATION=${organisation}",
               "SNYKDIR=build-snyk-env", "NEXUS_HOST=${context.nexusHost}", "NEXUS_USERNAME=${context.nexusUsername}",
               "NEXUS_PASSWORD=${context.nexusPassword}"]) {
        // Verify that snyk is installed
        def status = sh(script: "snyk version", returnStatus: true, label : "getting snyk version")
        if (status != 0) {
          error "snyk is not installed!"
        }

        // Limit access to snyk. Copy all required resources to temp folder
        // copy gradle resources (copy recursive to support submodules)
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"*gradle*\" --exclude=\"*\" . $SNYKDIR", label: "copy gradle resources")

        // copy maven resources (copy recursive to support submodules)
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"pom.xml\" --exclude=\"*\" . $SNYKDIR", label: "copy maven resources")

        // copy maven resources
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"package.json\" --exclude=\"*\" . $SNYKDIR", label: "copy maven resources")

        // copy python resources
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"*requirements.txt\" --exclude=\"*\" . $SNYKDIR", label: "copy python resources")

        // copy go resources
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"go.mod\" --exclude=\"*\" . $SNYKDIR", label: "copy go resources")

        // copy scala resources
        // requires in project/plugins.sbt this line: addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"build.sbt\" --exclude=\"*\" . $SNYKDIR", label: "copy scala resources")
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"project/build.properties\" --exclude=\"*\" . $SNYKDIR", label: "")
        sh (script: "rsync -rv --prune-empty-dirs  --include=\"*/\" --include \"project/plugins.sbt\" --exclude=\"*\" . $SNYKDIR", label: "")

        // Authorise snyk
        status = sh(script: "snyk auth $SNYK_AUTHENTICATION_CODE", returnStatus: true, label : "authenticating to snyk")
        if (status != 0) {
          error "something went wrong by authorising snyk (SNYK_AUTHENTICATION_CODE=$SNYK_AUTHENTICATION_CODE)!"
        }
        // first monitor project
        status = sh(script: "cd $SNYKDIR && ls -lart && snyk monitor --org=$ORGANISATION --file=$BUILD_FILE --project-name=$COMPONENT_NAME", returnStatus: true, label : "start monitoring in snyk")
        if (status != 0) {
          error "something went wrong with snyk monitor command!"
        }
        // fail if vulnerabilites are found
        status = sh(script: "cd $SNYKDIR && ls -lart && snyk test --org=$ORGANISATION --file=$BUILD_FILE --all-sub-projects", returnStatus: true, label : "run snyk test")
        if (status != 0 && context.failOnSnykScanVulnerabilities) {
          error "snyk test found vulnerabilities (see snyk report above for details!)!"
        }
      }
    }
```
It copies the required build resources to a temp folder called `SNYKDIR` and run `snyk cli` in the `SNYKDIR` folder.
This approach works and brings to proof that:
1. snyk do not need any sources.
2. It just only needs the list of dependencies provides by gradle, maven, pip, npm, sbt, etc..

To shed more light here, `snyk cli` only works if the corresponding build tool (like gradle, mvn, pip, npm, etc...) is available. This is the case because `snyk cli` actually calls the build tool to A. resolve all direct and transitive dependencies and B. to provide a list of these dependencies. In that sense `snyk cli` is an extension of the build system, which in no way need the project source code to work.

I hope this clarifies how snyk cli works.

**Comment by michaelsauter** [comment]
I think this is not needed anymore. Either one trusts Snyk, or one doesn't. If one does not trust Snyk, there's no need to install it.
