### ISSUE TITLE
Centralise configuration

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#219]
At the moment, ODS has a `ods-configuration-sample` which shows which configuration params need to be present. The user is supposed to create a `ods-configuration` repo in Bitbucket, and there mirror all the files and params as in the sample repo. The structure of the sample repo is such that it tries to mirror the file structure of the repo containing the corresponding template file.

That approach is not ideal:

* Due to the structure, many params need to be repeated, making them tedious to setup/update. It would be nicer to define repeated params in one file.
* Often, PRs in one repo do not contain the whole change but need to be accompanied by a PR in the sample repo

I propose:

* Moving the sample config into `ods-core`
* Defining all shared params in one file
* Providing scripts to the user to create `ods-configuration` and to manage updates to it

**Comment by henrjk** [comment]
Sorry for being late to this issue

Currently there is  https://github.com/opendevstack/ods-configuration-sample/blob/master/ods-project-quickstarters/ocp-templates/templates/templates.env.sample

@michaelsauter are there already plans or issues regarding how to deal with this?

**Comment by michaelsauter** [comment]
@henrjk Yes, I will adjust the points where code points to that sample file as well. Going to create a PR for that hopefully today.
