### ISSUE TITLE
Calling ./upload-templates.sh from prepare-local-environment fails because the "upload-templates.sh" in quickstarters was removed.

### ISSUE THREAD

**Issue by kiwo** [opendevstack/ods-core#220]
Calling ./upload-templates.sh from prepare-local-environment fails because the "upload-templates.sh" in quickstarters was removed.

**Comment by michaelsauter** [comment]
Closing as the problem was related to an outdated ods-core as far as I understand now. Please reopen if the problem re-occurs.
