### ISSUE TITLE
jenkins images are not being built in new installation because of unknown parameter name "SNYK_DISTRIBUTION_URL". 

### ISSUE THREAD

**Issue by kiwo** [opendevstack/ods-core#221]
`Using project "cd".
Already on project "cd" on server "https://127.0.0.1:8443".
Update Jenkins Config
--> oc version
--> Client and server version could not be detected properly, got:
%s
 oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0

--> Version mismatch between client (v3.11) and server (?) detected. This can lead to incorrect behaviour. Update your oc binary or point to an alternative binary with --oc-binary.
--> oc project cd --short
Comparing templates in /ods/ods-core/jenkins/ocp-config with OCP namespace cd.
Limiting resources to bc,is with selector app=jenkins.
--> oc process --filename=./bc.yml --output=yaml --param-file=.combined.env
error: unknown parameter name "SNYK_DISTRIBUTION_URL"

2019/10/31 12:27:57 Could not process bc.yml template: exit status 1
Start Jenkins Builds
Error from server (Forbidden): buildconfigs.build.openshift.io "jenkins-master" is forbidden: buildconfigs.build.openshift.io "jenkins-master" not found
Error from server (Forbidden): buildconfigs.build.openshift.io "jenkins-slave-base" is forbidden: buildconfigs.build.openshift.io "jenkins-slave-base" not found
Error from server (Forbidden): buildconfigs.build.openshift.io "jenkins-webhook-proxy" is forbidden: buildconfigs.build.openshift.io "jenkins-webhook-proxy" not found
`

When removing SNYK_DISTRIBUTION_URL from bc.env Build works fine.

**Comment by michaelsauter** [comment]
The sample config has that param defined (https://github.com/opendevstack/ods-configuration-sample/blob/master/ods-core/jenkins/ocp-config/bc.env.sample#L16). Have you checked that you prepared all params?

**Comment by michaelsauter** [comment]
Closing as the problem was related to an outdated ods-core as far as I understand now. Please reopen if the problem re-occurs.
