### ISSUE TITLE
Webhook Proxy does not deal with multiple simultaneous branches for the same issue

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#226]
**Describe the bug**
Based on the branch name, the webhook proxy creates a pipeline. E.g. a branch `FOO-123-abc` will create a pipeline `COMPONENT-123`. When another branch is created with the same issue reference, e.g. `FOO-123-def`, the webhook proxy will simply trigger the pipeline `COMPONENT-123`. However, that is not what the user intended as the commit that should be built is not on `FOO-123-abc` but on `FOO-123-def`.

**Expected behavior**
The webhook proxy should realise that the branches are different and would need to create a different pipeline.

**Affected version:**
 - OpenShift: all
 - OpenDevStack: all

**Comment by henrjk** [comment]
I ran into this as well but assumed it was by design to avoid creating to many cloned environments if auto cloning is used.

The suggested changes make sense to me.
