### ISSUE TITLE
Jenkins in prov-cd cannot give image-puller permissions

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#228]
**Describe the bug**
When creating projects via Jenkins, the execution fails due to:
```
oc policy add-role-to-user system:image-puller system:serviceaccount:mstest-cd:jenkins -n cd
Error from server (Forbidden): rolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:prov-cd:jenkins" cannot list rolebindings.rbac.authorization.k8s.io in the namespace "cd": RBAC: clusterrole.rbac.authorization.k8s.io "self-provisoner" not found
```

**To Reproduce**
I created and triggered a new pipeline, which should create the jobs, on a branch with quite a bit of cleanup, but I think the error is unrelated to that. The invocation was basically this:
```
curl "https://webhook-proxy-prov-cd.example.com/build?trigger_secret=SECRET&jenkinsfile_path=create-projects/Jenkinsfile&component=ods-corejob-create-projects-mstest" -v \
-H 'Content-Type: application/json' \
-d '{"branch":"task/cleanup","repository":"https://cd_user@bitbucket.example.com/scm/opendevstack/ods-core.git","env":[{"name":"PROJECT_ID","value":"mstest"},{"name":"PROJECT_ADMIN","value":"mstest@example.com"},{"name":"PIPELINE_TRIGGER_SECRET","value":"SECRET"}]}'
```

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack: master only

@kiwo Did you run across this? Did you have to change anything regarding the permissions?

EDIT: Here's the branch I was trying this on: https://github.com/BIX-Digital/ods-core/tree/task/cleanup

**Comment by clemensutschig** [comment]
@michaelsauter - this used needs to be able to grant provision rights to others .. (and we need to ensure that we tighten this down as much as possible)

**Comment by michaelsauter** [comment]
I have added the following rolebindings:
```
$ oc adm policy add-cluster-role-to-group system:image-puller system:authenticated -n cd
$ oc adm policy add-role-to-group view system:authenticated -n cd
```

Works like a charm 🎉 

I'll need to add this to the installation instructions.

FYI @kiwo
