### ISSUE TITLE
Build endpoint does not update env params

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#237]
When passing environment variables to the `/build` endpoint, the webhook proxy creates a pipeline with those variables. Further invocations via the webook proxy will use the values from the initial creation - independent if you pass any env variables, or pass different values. In Jenkins itself, it is possible though to start the job with different values.

According to https://docs.openshift.com/container-platform/3.11/dev_guide/builds/triggering_builds.html#generic-webhooks it is possible to pass new variables when triggering a build, and if the provided vars collide with existing ones, the values of the passed ones take precedence.

I think that the current behaviour of the webhook proxy is surprising / buggy and that it should take the env variables from the `/build` request and put them into the trigger request to OpenShift.

Before doing that change, it would be nice if @metmajer and @kiwo could comment if that makes sense for you as well or if you would want to see a different behaviour ...

I am not entirely sure that we want to go down that route as the webhook proxy initially was just that, a proxy. So it had to do create+trigger in one invocation. One could argue that the current `/build` endpoint should really be two invocations: create and, separately, trigger ... however doing that would break existing consumers of `/build`.

**Comment by kiwo** [comment]
-> currently does not affect the implementation of "kill rundeck" because every job title is unique.

**Comment by kiwo** [comment]
current quickstarter naming pattern from ProvApp: ods-quickstarter-" + job.getName() + "-"  + component_id;

"corejobs" job: ods-corejob-" + job.name + "-" + projID

**Comment by michaelsauter** [comment]
@kiwo Thanks for the update, and good to know. However, a consequence is that every provisioning is its own pipeline ... which I'd say is not really ideal. That said, switching the pipeline name to e.g. just `"ods-quickstarter-" + job.getName()` only reduces the number of pipelines to one pipeline per type.

Maybe we can tackle this issue also post-2.0, and leave the state as is for now since what you did works with the current design.

I'll give this some more thought ...

**Comment by michaelsauter** [comment]
@clemensutschig Why is this in ODS 2 now? There is no agreed solution yet so I would put this to v3. v2 works as-is ...

**Comment by michaelsauter** [comment]
We decided to go for the following approach:

Just take the env params as passed to `/build`, and forward them. If some env params are not passed, that have been passed initially, then the original value is not overwritten, and basically serves as a default.
