### ISSUE TITLE
Bash script for copying configuration

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-core#24]
Add a bash script, which removes the sample suffix and copies the configuration-sample into the configuration directory. Additionally this should make a git diff, to show wether there are changes between the current master and the locally cloned files.

**Comment by michaelsauter** [comment]
How about changing the whole approach to configuration? E.g. we could have one folder in `ods-core`, which contains the sample config, and then a script to init/update the `ods-configuration` repo. The advantage of that would be that a PR which changes code and sample config does not need to touch multiple repos ...

What do you think? (@clemensutschig this is the idea I mentioned earlier today)

**Comment by michaelsauter** [comment]
@tjaeschke Should we close this ticket now?

**Comment by tjaeschke** [comment]
Implemented with #98
