### ISSUE TITLE
prepare-jenkins-builds param file not exists

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#248]
**Describe the bug**
When running `prepare-jenkins-builds.sh`, the following code 

```
cd ${BASE_DIR}/ods-project-quickstarters/jenkins-slaves/maven/ocp-config
yes 'y' | tailor update -v --force
```

fails with error:

```
2019/11/19 10:13:19 Options could not be processed: Param directory ../../../../ods-configuration/ods-project-quickstarters/jenkins-slaves/maven/ocp-config does not exist
```

**To Reproduce**
1. Run prepare-jenkins-builds.sh via `vagrant ssh openshift -c "sudo /ods/ods-core/infrastructure-setup/scripts/prepare-jenkins-builds.sh"`

**Expected behavior**
Jenins slaves templats are configured and uploaded.

**Screenshots**

**Affected version:*
 - Version from master skript, installed by following the local installation guide.

**Additional context**

Same problem exists when running `vagrant ssh openshift -c "sudo /ods/ods-core/infrastructure-setup/scripts/prepare-jenkins-slave-builds.sh"`

```
Using project "cd".
Already on project "cd" on server "https://127.0.0.1:8443".
2019/11/19 11:53:39 Options could not be processed: Param directory ../../../../ods-configuration/ods-project-quickstarters/jenkins-slaves/nodejs8-angular/ocp-config does not exist
2019/11/19 11:53:39 Options could not be processed: Param directory ../../../../ods-configuration/ods-project-quickstarters/jenkins-slaves/nodejs10-angular/ocp-config does not exist
2019/11/19 11:53:39 Options could not be processed: Param directory ../../../../ods-configuration/ods-project-quickstarters/jenkins-slaves/python/ocp-config does not exist
2019/11/19 11:53:39 Options could not be processed: Param directory ../../../../ods-configuration/ods-project-quickstarters/jenkins-slaves/scala/ocp-config does not exist
Error from server (Forbidden): buildconfigs.build.openshift.io "jenkins-slave-python" is forbidden: buildconfigs.build.openshift.io "jenkins-slave-python" not found
Error from server (Forbidden): buildconfigs.build.openshift.io "jenkins-slave-scala" is forbidden: buildconfigs.build.openshift.io "jenkins-slave-scala" not found
Error from server (Forbidden): buildconfigs.build.openshift.io "jenkins-slave-nodejs8-angular" is forbidden: buildconfigs.build.openshift.io "jenkins-slave-nodejs8-angular" not found
Error from server (Forbidden): buildconfigs.build.openshift.io "jenkins-slave-nodejs10-angular" is forbidden: buildconfigs.build.openshift.io "jenkins-slave-nodejs10-angular" not found

```

**Comment by michaelsauter** [comment]
@stefanlack I guess this is with a fresh installation? That might now be due to @tjaeschke changes where he removed the old codepath. The jenkins slaves need to be moved to `ods-quickstarters`. I might get to that in the evening.

**Comment by stefanlack** [comment]
@michaelsauter yes, it is a fresh installation.

**Comment by michaelsauter** [comment]
I started to move the slaves to the new location: https://github.com/opendevstack/ods-quickstarters/pull/4. Those definitions point to the new configuration files now.

I think what's left is to update the shell script you ran to use the new repo.

**Comment by stefanlack** [comment]
I will update the shell skript.

**Comment by michaelsauter** [comment]
@stefanlack Thanks a lot! Let me know when you need any help.
