### ISSUE TITLE
configurable buildconfig output

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-core#253]
**Is your feature request related to a problem? Please describe.**
It would be beneficial for hybrid workloads to use OpenShift/ODS as the build environment pushing images to an (or even multiple) external docker registry (registries) like Nexus, AWS ECR or Azure Container Registry.
I'm using the term hybrid workloads in a sense were a single container image is used within OpenShift, AWS, Azure, HPC-Singularity executor or even plain docker.

**Describe the solution you'd like**
The output target should be configurable so that images could be pushed to a docker registry. I didn't research if output could even be a multi-target item (ImageStream *and* docker registries).

**Describe alternatives you've considered**
Building images within ODS and use the same repo for external builds which isn't a 1:1 move as Jenkinsfile has to be changed.
Not everybody wants to expose the internal registry.

**Additional context**
https://docs.openshift.com/container-platform/3.11/dev_guide/builds/build_output.html
https://docs.openshift.com/container-platform/4.2/builds/managing-build-output.html

**Comment by tbugfinder** [comment]
I spent some time on that without having success.

- oc tooling doesn't download the container image.

```
h-4.2$ oc get --export isimage test
No resources found.
Error from server (BadRequest): export of "imagestreamimages" is not supported
sh-4.2$ 
```

- docker pull/push isn't possible within a pod as it requires a running dockerd.

- rootless podman (pull/push) isn't (yet?) possible due to lack of appropriate namespaces within the pod.

- https://github.com/genuinetools/img also relies on namespace support

```
sh-4.2$ cat /proc/sys/user/max_user_namespaces
0
sh-4.2$ 
sh-4.2$ echo 10000 > /proc/sys/user/max_user_namespaces
sh: /proc/sys/user/max_user_namespaces: Read-only file system
sh-4.2$ 
```

**Comment by michaelsauter** [comment]
I think https://github.com/containers/skopeo is the way to go. I have not played with it but that might work within OpenShift.

**Comment by clemensutschig** [comment]
@tbugfinder  - can you try and report on any findings? ...

**Comment by tbugfinder** [comment]
Yes - I'll provide an update soon.

**Comment by tbugfinder** [comment]
I've successfully copied an image within OpenShift itself using skopeo. It needs some tweaks for the authentication part and the certificates but overall best tool to do that.

Next test will be copying to an external registry like NEXUS.

https://github.com/nmasse-itix/OpenShift-Examples/blob/master/Using-Skopeo/README.md

**Comment by tbugfinder** [comment]
Nice read, too.
https://blog.openshift.com/promoting-container-images-between-registries-with-skopeo/

**Comment by clemensutschig** [comment]
@tbugfinder - cool! ... the service account to get access to the registry is already in the pod available ... but looks like you have solved this, eh :)?

**Comment by clemensutschig** [comment]
I am wondering if we should package scopeo in a slave, but ... :)

**Comment by michaelsauter** [comment]
@clemensutschig Might be helpful! I would say we give this a test-run now and if we are happy with it and see enough value, we can add it for ODS 3.

**Comment by tbugfinder** [comment]
Awesome, skopeo copied an image successfully from Openshift registry to NEXUS.

I'd also like to see scopeo in the Jenkinsslave.
This should be in ODS2.

**Comment by tbugfinder** [comment]
I was using:
 yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/skopeo-0.1.37-3.el7.centos.x86_64.rpm http://mirror.centos.org/centos/7/extras/x86_64/Packages/containers-common-0.1.37-3.el7.centos.x86_64.rpm

**Comment by clemensutschig** [comment]
@tbugfinder anything Else you did?

**Comment by tbugfinder** [comment]
Well, although my current test code includes podman, buildah, EPEL above line should really be all.
I could strip anything else off if you need confirmation.

**Comment by clemensutschig** [comment]
@tbugfinder  see PR .. anything else we miss?

**Comment by tbugfinder** [comment]
Nice! I'll test it.

**Comment by tbugfinder** [comment]
I've picked the RHEL Dockerfile and was able to use skopeo successfully for copying an image. This makes it easy to offload images from the internal registry, even for debugging purposes.

**Comment by clemensutschig** [comment]
super cool... @michaelsauter  - maybe we should add a default stage in the shared lib to use skopeo for uploading the image to nexus?.. just thinking out loud.

**Comment by michaelsauter** [comment]
@clemensutschig I'd like to understand usage a little better first. Now that skopeo is available, it should be easy enough for people to use code snippets that make use of it. During the next release cycle we could collect use cases and then see which features make sense to provide out-of-the-box. I don't really get the Nexus use-case yet to be honest. Also, people might use this to push an image into AWS or so?

**Comment by tbugfinder** [comment]
Indeed images could be uploaded to different regions in AWS/Azure, onprem registries or between OpenShift environments (see the issue's top).

The use-case is building the image once and execute it not only within the building OpenShift environment but also on e.g. native docker installations for debugging purposes or in a HPC environment.

A stage in the shared library could have map of registries and tokens as input.

Within Nexus, the docker endpoint has to be configured in addition, AFAIK.

**Comment by clemensutschig** [comment]
@tbugfinder  - what about you providing an example (= code) .. then lets see if we can include ...
