### ISSUE TITLE
Sonarqube pod crashes with version 7.9 in local installation

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-core#269]
**Describe the bug**
After replacing the Sonarqube version 7.3 with 7.9 because of startup problems the sonarqube pod crashes.

**To Reproduce**
1. Use Sonar version 7.9 and local installation
2. Build Image
3. Deploay image

**Expected behavior**
The pod starts up withour errors

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
ERROR: [1] bootstrap checks failed
--
  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

```

**Comment by michaelsauter** [comment]
Weird ... works on our cluster 😕

**Comment by tjaeschke** [comment]
The problem is on the local vm used for the Openshift cluster. There you have to run 
`sysctl -w vm.max_map_count=262144`
I will add this to the `prepare-openshift-cluster.sh` script.

**Comment by stefanlack** [comment]
After virtual box image is restarted, error occur again.
