### ISSUE TITLE
documentation links to shared images are broken

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#271]
**Describe the bug**
Documentation at https://www.opendevstack.org/ods-documentation/ods-core/latest/infrastructure-setup/index.html points to 
- openresty-nginx.adoc
- nginx-authproxy-crowd.adoc

Both files are missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/2901438/69602751-e5ddcf80-1018-11ea-983b-0d1bfea663aa.png)

**Comment by michaelsauter** [comment]
@gerardcl Can you please fix? Let me know if you need help.

**Comment by gerardcl** [comment]
hi @stefanlack  @michaelsauter ! so the change here indeed is to remove the mentions to both `openresty-nginx` and `nginx-authproxy-crowd` in the documentations, and, for now, update it so to mention still existing ones: `airflow` and `elasticsearch`

see comments in PR https://github.com/opendevstack/ods-core/pull/224 and more information to it via related issue #215
