### ISSUE TITLE
webhook proxy should return url to jenkins create job

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#281]
**Is your feature request related to a problem? Please describe.**
Releated to https://github.com/opendevstack/ods-provisioning-app/issues/279, where I am asked to link the jenkins job that has created the new initiative.
Rather than building that url at the provision-app implementation, it would be better that the webhookproxy is returning that url

**Describe the solution you'd like**
Webhook Proxy should return the url to the build Job. 

Let's examine current (based on master branches) data that is returned from webhook proxy.

_Webhook Proxy was called with url:_ 
"https://webhook-proxy-prov-cd.192.168.56.101.nip.io/build?trigger_secret=secret101&jenkinsfile_path=create-projects/Jenkinsfile&component=ods-corejob-create-projects-tst04"

_Data returned from webhook proxy:_
```
{
  "kind": "Build",
  "apiVersion": "build.openshift.io/v1",
  "metadata": {
    "name": "ods-corejob-create-projects-tst04-production-1",
    "namespace": "prov-cd",
    "selfLink": "/apis/build.openshift.io/v1/namespaces/prov-cd/buildconfigs/ods-corejob-create-projects-tst04-production-1/instantiate",
    "uid": "b0cb02d7-11a9-11ea-9997-08002750261b",
    "resourceVersion": "913911",
    "creationTimestamp": "2019-11-28T06:38:30Z",
    "labels": {
      "buildconfig": "ods-corejob-create-projects-tst04-production",
      "openshift.io/build-config.name": "ods-corejob-create-projects-tst04-production",
      "openshift.io/build.start-policy": "Serial"
    },
    "annotations": {
      "openshift.io/build-config.name": "ods-corejob-create-projects-tst04-production",
      "openshift.io/build.number": "1"
    },
    "ownerReferences": [
      {
        "apiVersion": "build.openshift.io/v1",
        "kind": "BuildConfig",
        "name": "ods-corejob-create-projects-tst04-production",
        "uid": "b0c5bb4d-11a9-11ea-9997-08002750261b",
        "controller": true
      }
    ]
  },
  "spec": {
    "serviceAccount": "builder",
    "source": {
      "type": "Git",
      "git": {
        "uri": "http://cd_user@192.168.56.31:7990/scm/opendevstack/ods-core.git",
        "ref": "production"
      },
      "sourceSecret": {
        "name": "cd-user-with-password"
      }
    },
    "strategy": {
      "type": "JenkinsPipeline",
      "jenkinsPipelineStrategy": {
        "jenkinsfilePath": "create-projects/Jenkinsfile",
        "env": [
          {
            "name": "PIPELINE_TRIGGER_SECRET",
            "value": "YTQzNjQ5ZDAtMDFhNS00NzU3LTk2NDYtMTc1NGVkMjNlYTdh"
          },
          {
            "name": "PROJECT_ADMIN",
            "value": "opendevstack.admin"
          },
          {
            "name": "PROJECT_ID",
            "value": "tst04"
          }
        ]
      }
    },
    "output": {},
    "resources": {},
    "postCommit": {},
    "nodeSelector": {},
    "triggeredBy": [
      {
        "message": "Generic WebHook",
        "genericWebHook": {
          "secret": "\u003csecret\u003e"
        }
      }
    ]
  },
  "status": {
    "phase": "New",
    "config": {
      "kind": "BuildConfig",
      "namespace": "prov-cd",
      "name": "ods-corejob-create-projects-tst04-production"
    },
    "output": {}
  }
}
```

Sadly I do not see the url to jenkins job. 
Can you add the URL to the returned data? For example, I would expect URL to the build log: https://jenkins-prov-cd.192.168.56.101.nip.io/job/prov-cd/job/prov-cd-ods-corejob-create-projects-tst04-production/1/ 

**Describe alternatives you've considered**
Build URL to jenkins build job at provisioning app. But this is bad design. Creating Jenkins build jobs is done by webhook proxy, so we do not need to duplicate the implementation of building the url.
If internal build system changed, provision app should work without modifications.

**Additional context**
By the way, it would be helpfull if we have a documentation about the returned value from webhook proxy. As far as I see, only the input format is documented at https://www.opendevstack.org/ods-documentation/ods-core/latest/jenkins/webhook-proxy.html#_post_build

**Comment by michaelsauter** [comment]
@stefanlack the webhook proxy returns the OpenShift response as-is. As it is a **proxy** I don't want to change this. I will document the response. Also keep in mind that the webhook proxy does not actually talk to Jenkins - it does not have the Jenkins URL available.

I think you'll have to assemble it based on what is returned in `annotations` ...

**Comment by stefanlack** [comment]
Ok, than I do the construction of the url in provision app.
