### ISSUE TITLE
Invalid APP_DNS doesn't stop build at given step

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-core#298]
**Describe the bug**
The build process doesn't stop at given line in case `APP_DNS` is invalid. The build process proceeds and fails at a later `RUN` while importing the certificated.

**To Reproduce**
1. Set `APP_DNS` to an invalid or unreachable value.
2. Start BUILD

**Expected behavior**
In case `APP_DNS` isn't valid or reachable within the pod the build process should stop immediately at the given `RUN` step.

**Screenshots**
N/A

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [1.2.x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```


Step 13/37 : RUN gnutls-cli --insecure --print-cert ${APP_DNS} </dev/null\| sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/oc_app.crt
--
  | ---> Running in 5501bf295bfc
  |  
  | Cannot resolve 192.168.99.100.nip.io:443: Name or service not known
  | ---> 438eb7b3bfe8





....




Step 17/37 : RUN $JAVA_HOME/bin/keytool -storepasswd -new mysecretpassword -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit &&     echo "yes" \| $JAVA_HOME/bin/keytool -import -trustcacerts -file /tmp/oc_app.crt -alias oc_app -keystore $JAVA_HOME/lib/security/cacerts -storepass mysecretpassword &&     echo "yes"
--
  | ---> Running in 3ec67cdc8ba6
  |  
  | keytool error: java.lang.Exception: Input not an X.509 certificate
  | Removing intermediate container 3ec67cdc8ba6
  | error: build error: The command '/bin/sh -c $JAVA_HOME/bin/keytool -storepasswd -new mysecretpassword -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit &&     echo "yes" \| $JAVA_HOME/bin/keytool -import -trustcacerts -file /tmp/oc_app.crt -alias oc_app -keystore $JAVA_HOME/lib/security/cacerts -storepass mysecretpassword &&     echo "yes"' returned a non-zero code: 1


```

**Additional context**
N/A

**Comment by clemensutschig** [comment]
@tbugfinder  - want to submit a PR ? :D

**Comment by tbugfinder** [comment]
How about setting pipefail for the shell?

`SHELL ["/bin/bash", "-o", "pipefail", "-c"]`
