### ISSUE TITLE
rework Jenkins Dockerfiles

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-core#312]
**Describe the bug**
Referring to: https://github.com/opendevstack/ods-core/pull/296#discussion_r353133496 
- too many layers as there are too many RUN statement
- No common indention
- inconsistent `RUN` statements, some lines start with `&&` compared to others ending with `&& \

**To Reproduce**
1. Just look at the code.

**Expected behavior**
Harmonized and clean Dockerfiles

**Screenshots**
N/A

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [1.2.x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
N/A
```

**Additional context**
N/A

**Comment by michaelsauter** [comment]
Yes, that would be great! I'm changing the label to enhancement though as it is not broken.

**Comment by tbugfinder** [comment]
Would you agree on adding .editorconfig also within this PR?

**Comment by clemensutschig** [comment]
@tbugfinder  - sure thing :)

**Comment by metmajer** [comment]
@tbugfinder would prefer creating at least a dedicated commit message for that. Have you seen that we already use an `.editorconfig` at https://github.com/opendevstack/ods-mro-jenkins-shared-library? Please double-check to see if you can re-use this one.
