### ISSUE TITLE
Jenkins Master version / source

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-core#327]
**Feature Request**

The Jenkins version of  the registry repo source of Jenkins master seems to be older than "expected" - especially as security fixes were added to later versions.
The image tagged latest is older than the tag v3.11. The docker.io registry repo isn't maintained any longer.
The logfiles show:
```
INFO: Started w.@53499d85{Jenkins v2.150.2,/,file:///var/lib/jenkins/war/,AVAILABLE}{/var/lib/jenkins/war}
```
**Describe the solution you'd like**
Use later Jenkins version for the Jenkins Master, e.g. tag v3.11.

**Describe alternatives you've considered**
jenkins:lts or test new origin images of quay.io.
https://quay.io/repository/openshift/origin-jenkins?tag=latest&tab=tags
```
docker pull quay.io/openshift/origin-jenkins:latest
```
**Additional context**

**Comment by michaelsauter** [comment]
@tbugfinder Are you referring to the tag `2`? This is the base image for the Jenkins master, see https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/bc.yml#L38.

To my knowledge, this is up-to-date, at least it gets updates quite frequently.

The base image for the slave can be configured, see https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/bc.yml#L79. We use the `3.11` tag internally, as the `latest` tag seems outdated.

**Comment by tbugfinder** [comment]
I didn't check the `bc.yml`.
I run build locally using docker + Dockerfile. So this file is kind of out-of-sync:
https://github.com/opendevstack/ods-core/blob/master/jenkins/master/Dockerfile#L1

**Comment by michaelsauter** [comment]
Yes it should at least say that the value has no effect on OpenShift as the BuildConfig wins ...

**Comment by tbugfinder** [comment]
I'll add a PR :-)
Which Jenkins version is expected for ODS1.2.x and ODS2 deployments?

**Comment by michaelsauter** [comment]
Great!

Latest of v2 of Jenkins. OpenShift version we cannot assume, anything from 3.9 to 3.11 should be possible and up to the user to configure.

**Comment by clemensutschig** [comment]
This is fixed - and controllable in ods-master.
https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L136
