### ISSUE TITLE
create-projects: Unkown path in Tailorfile

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-core#334]
Tailorfile https://github.com/opendevstack/ods-core/blob/master/create-projects/ocp-config/cd-jenkins/Tailorfile has a reference to a `param-file` ../../../ods-config/ods-core.env that is not documented.

https://github.com/opendevstack/ods-core/blob/fdf0de7ae9bca8838f2c0b98b59be0ac23eb1379/create-projects/ocp-config/cd-jenkins/Tailorfile#L1

This could be a parameter so I can point to the configuration needed during runtime

**Comment by clemensutschig** [comment]
@michaelsauter - bug?

**Comment by hugowschneider** [comment]
@clemensutschig, I believe it is a matter of documentation. "How to config ODS and use the env files".  #344 points somewhat to the same issue

**Comment by michaelsauter** [comment]
@clemensutschig This is not a bug. However, this path only works given the proper environment, which is there in the Jenkins pipeline. If you would want to call Tailor in another context (e.g. testing like Hugo does), then you would need to replicate the env.

To make this better, I believe we should remove the `param-file` line from the `Tailorfile`. Then users will need to pass the param ad-hoc, which is slightly more cumbersome, but at least it is obvious.

**Comment by hugowschneider** [comment]
@michaelsauter But also a question... the Tailorfile is somehow the core information what to deploy and how. If I select a Tailorfile and it works for testing it does not test the one used for deployment. Do you see an away of addressing that?

**Comment by michaelsauter** [comment]
The only other way is to make both use cases have the same path setup.

BUT I think the tests should eventually execute the Jenkins pipeline anyway to create a new project (vs. calling the script directly) and then you do test the real thing.
