### ISSUE TITLE
create-projects: Misplaced selector / Selector not specified in Tailorfile

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-core#337]
`--selector "template=cd-jenkins-template" ` should be part of the Tailorfile to ensure consistency.

https://github.com/opendevstack/ods-core/blob/4b51909ee622406dbd9c37f9836ca54a684569b4/create-projects/ocp-config/cd-jenkins/Tailorfile#L1-L5

https://github.com/opendevstack/ods-core/blob/4b51909ee622406dbd9c37f9836ca54a684569b4/create-projects/create-cd-jenkins.sh#L74-L80

**Comment by clemensutschig** [comment]
@hugowschneider  / @michaelsauter  - close? this works now with ODS3 / master=?!

**Comment by michaelsauter** [comment]
Yes can be closed.
