### ISSUE TITLE
ods-setup: Add ODS Jenkins deployment to tests

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-core#343]
Test the deployment of Jenkins inside the base `ods` project.

**Comment by clemensutschig** [comment]
related to #636

**Comment by michaelsauter** [comment]
@clemensutschig Is this a v3 topic or beyond? I lost track a little of the current progress on this :)

**Comment by clemensutschig** [comment]
not needed anymore - with all the tests - we cover this as well
