### ISSUE TITLE
Tailorfiles are referencing different configuration files

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-core#344]
Tailor file inside project creation and inside Jenkins folder are pointing to different tailor files.

https://github.com/opendevstack/ods-core/blob/04bfd8ce04466263a5440572d66563c460fd2904/create-projects/ocp-config/cd-jenkins/Tailorfile#L1

https://github.com/opendevstack/ods-core/blob/04bfd8ce04466263a5440572d66563c460fd2904/jenkins/ocp-config/Tailorfile#L3

**Comment by michaelsauter** [comment]
Yes but this is not a bug ... it is that way because the `create-projects` job creates a folder with name `ods-config`.

**Comment by hugowschneider** [comment]
I could not say bug of not, but it is very confusing

**Comment by michaelsauter** [comment]
Agreed! I think it would probably be better to move this out of the Tailorfile and pass the argument directly, then it is less confusing ...

**Comment by hugowschneider** [comment]
Another suggestion would be to split the configuration into more specific files. For example but not necessarily these names: jenkins.env, bitbucket.env and... then it gets more flexible and also gets easier to differentiate.

**Comment by michaelsauter** [comment]
@hugowschneider Hmm, I'm not a fan. I don't see this being simpler then just passing the file on invocation.
