### ISSUE TITLE
BuildConfig For Jenkins Master/Jenkins Slave/Webhook have different triggers

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-core#349]
There is a trigger for the Jenkins master build config while for the webhook and the slave there is none.

For testing ODS is better to have no triggers at all to enable more control over the setup steps.

Also, is this difference in the build configs intentional?

https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/bc.yml

https://github.com/opendevstack/ods-core/blob/04bfd8ce04466263a5440572d66563c460fd2904/jenkins/ocp-config/bc.yml#L17-L19

https://github.com/opendevstack/ods-core/blob/04bfd8ce04466263a5440572d66563c460fd2904/jenkins/ocp-config/bc.yml#L81

https://github.com/opendevstack/ods-core/blob/04bfd8ce04466263a5440572d66563c460fd2904/jenkins/ocp-config/bc.yml#L110

**Comment by michaelsauter** [comment]
Why is this marked as invalid now? I think your point is valid. I would probably favour a rebuild on image change, and no deployment triggers in the jenkins instances.

**Comment by hugowschneider** [comment]
Does invalid means "the code fells wrong" ?? Or is "the ticket feels wrong"? LOL... Nevertheless... If you agree I would do a pull request removing the trigger...

**Comment by michaelsauter** [comment]
"Invalid" means that the ticket does no apply - e.g. someone thought something with the code is wrong but it is not.

What we should do with the trigger I am not really sure yet.

**Comment by hugowschneider** [comment]
Just added a "bug" label. I will remove the trigger, PR will come soon
