### ISSUE TITLE
Import Certificates during Jenkins build

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-core#350]
During import_certs.sh in the line:

https://github.com/opendevstack/ods-core/blob/04bfd8ce04466263a5440572d66563c460fd2904/jenkins/master/import_certs.sh#L14

Also in:

https://github.com/opendevstack/ods-core/blob/04bfd8ce04466263a5440572d66563c460fd2904/jenkins/slave-base/Dockerfile.centos7#L31-L32

Since there is no port option, it is not possible to build Jenkins in a local cluster, or in a cluster that does not use the default (443) port.  

Also, those lines are duplicated across multiple files:

https://github.com/opendevstack/ods-core/blob/master/jenkins/slave-base/Dockerfile.centos7
https://github.com/opendevstack/ods-core/blob/master/jenkins/slave-base/Dockerfile.rhel7
https://github.com/opendevstack/ods-core/blob/master/jenkins/master/import_certs.sh

A would suggest adding a port variable in the env file.

**Comment by clemensutschig** [comment]
@hugowschneider Hmmm did you try with a Port? Add it and default it to 443 ;-)

And Great Catch!!!

**Comment by hugowschneider** [comment]
I am adding it as we speak...
