### ISSUE TITLE
webhook proxy - jenkins fails to fetch build in case branch name > 63chars

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#369]
**Describe the bug**

SEVERE: Timer task io.fabric8.jenkins.openshiftsync.BuildWatcher$1@5856f0b9 failed
--
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default/apis/build.openshift.io/v1/namespaces/pltfmdev-cd/builds?labelSelector=*buildconfig%3Ddemo-app-release-manager-feature-add-ods-service-and-test-support* . Message: unable to parse requirement: invalid label value: "demo-app-release-manager-feature-add-ods-service-and-test-support": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=unable to parse requirement: invalid label value: "demo-app-release-manager-feature-add-ods-service-and-test-support": must be no more than 63 characters, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).

**To Reproduce**
1. create extensively long branch name = longer than 63 chars

**Expected behavior**
jenkins can fetch build config

**Affected version (please complete the following information):**
 - OpenShift: [all]
 - OpenDevStack [all]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
see above
```

**Additional context**

**Comment by clemensutschig** [comment]
@metmajer  - fyi

**Comment by michaelsauter** [comment]
Will implement a fix this week.

**Comment by michaelsauter** [comment]
Also see related issue https://github.com/opendevstack/ods-provisioning-app/issues/335.
