### ISSUE TITLE
Sonarqube - updatecenter / marketplace does not use proxy 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#373]
**Describe the bug**
marketplace behind proxy is not working

**To Reproduce**
login as admin and go to marketplace - you'll see that you can't search not installed plugins

**Expected behavior**
search works behind proxy

**Affected version (please complete the following information):**
 - OpenDevStack [all]

**Log**
```

Caused by: java.net.SocketException: Connection reset
--
  | at java.net.SocketInputStream.read(SocketInputStream.java:210)
  | at java.net.SocketInputStream.read(SocketInputStream.java:141)
  | at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
  | at sun.security.ssl.InputRecord.read(InputRecord.java:503)
  | at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
  | at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
  | at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
  | at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
  | at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
  | at org.sonar.core.util.DefaultHttpDownloader$BaseHttpDownloader$HttpInputSupplier.getInput(DefaultHttpDownloader.java:272)
  | at org.sonar.core.util.DefaultHttpDownloader.readString(DefaultHttpDownloader.java:111)
  | ... 51 common frames omitted
```

**Additional context**
how to make it work:
https://community.sonarsource.com/t/trouble-setting-up-proxy-for-sonarqube-marketplace/4284

**Comment by clemensutschig** [comment]
@oalyman - fyi ...
https://docs.sonarqube.org/7.4/instance-administration/marketplace/

**Comment by michaelsauter** [comment]
Careful with the version, we are defaulting to 7.9 in ODS 2.0 ...

**Comment by clemensutschig** [comment]
@michaelsauter  - same in https://docs.sonarqube.org/latest/instance-administration/marketplace/

should be a quick fix based on ... 

https://github.com/opendevstack/ods-core/blob/master/jenkins/slave-base/set_java_proxy.sh

**Comment by michaelsauter** [comment]
@clemensutschig Ah nice. For some reason I failed to use the docs / find the right page :(

**Comment by clemensutschig** [comment]
we should fix this for ods2 and beyond ... (in lieu of the current plugin "issue")
