### ISSUE TITLE
Download of sonar-scanner-cli fails

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#378]
During the image build of the jenkins-slave-base image, downloading the ZIP file of sonar-scanner-cli (`curl -LOv http://repo1.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/${SONAR_SCANNER_VERSION}/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip`) does not work properly as Maven responds with:
```
501 HTTPS Required.
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```

According to the provided link:

> Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.

All OpenDevStack versions are affected.

Suggested fix: change to HTTPS, and check at the same time if other places use HTTP instead of likely available HTTPS.

**Comment by clemensutschig** [comment]
@michaelsauter  - get from nexus.... ?! this should be the default anyway ...

**Comment by michaelsauter** [comment]
For now I'll do the smallest change possible - just using HTTPS. There are other dependencies downloaded in this `Dockerfile` that are not pulled from Maven so Nexus won't apply there either. I've created a follow-up issue to track the Nexus enhancement: #386.
