### ISSUE TITLE
Create Makefile to give easy access to common tasks

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#381]
**Is your feature request related to a problem? Please describe.**
Right now it is difficult to find which "commands" are available, and how to do certain tasks such as updating SonarQube.

**Describe the solution you'd like**
I would like to have a `Makefile` that contains various targets which make it easy to run commands. Examples would be:

* `make jenkins`: Run `tailor update` on Jenkins build resources and start/follow builds
* `make sonarqube`: Run `tailor update` on SQ build resources (build configs etc.), build the image, run `tailor update` on SQ run resources (deployment configs etc.)
* `make nexus`: Run `tailor update` on Nexus resources (no custom image like SQ, so easier to handle ...). Later on that could handle repository setup in Nexus too.
* `make cd-setup`: Creates / updates resources in the CD namespace like cd-user, rolebindings
* `make configuration`: Runs `configuration-sample/update` script

**Describe alternatives you've considered**
None.

**Additional context**
This would pave the way to an easier installation / update procedure.

@metmajer I think you mentioned sth. like this before as well. I can't find it right now though. Did you have in mind what I described or different ideas?

@hugowschneider This would make use of some of the scripts you wrote ... and on the other hand, the tests could use this `Makefile` to do the setup. What do you think?

**Comment by metmajer** [comment]
@michaelsauter will see if I still have the links... will provide an update today

**Comment by metmajer** [comment]
@michaelsauter I couldn't find these issues quickly either, but what I had in mind goes a bit beyond:

`make test`: runs automated tests -- which could be scoped to the current repo or, if invoked in some meta-(test-)repo, would exhaustively test the entire ODS

`make distribute`: to distribute an ODS codebase from a configurable upstream repo to a configurable number of downstream repos. Thoughts here are to automate release branch generation, git pull $upstream and tagging. In case of merge conflicts, the user would need to resolve conflicts and re-run (so idempotent behavior would be needed).

`make release`: distribute + whatever else is needed

`make install`: to install or upgrade ODS on a configurable set of clusters. This will require us to define a generic install or upgrade procedure first, but would be an incredible improvement to have.

Would love to elaborate thoughts on this with the team soon.

**Comment by michaelsauter** [comment]
I see, and it sounds good to me. Unfortunately, I think apart from `test`, we are far off from implementing them. Therefore, I suggest to start with what I have built, and extend to cover what you have in mind as soon as we have the building blocks for it.

**Comment by metmajer** [comment]
Agreed. We should talk about a concept about the installation though as this tends to be an expert thing at the moment. We may find a smart way how to implement that.

**Comment by michaelsauter** [comment]
Closing this as common tasks are possible, and now we can extend on top of that - I suggest to create more targeted issues for that.
