### ISSUE TITLE
checkout-respositories.sh executes in sh instead of bash

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#397]
**Describe the bug**
the interpreter directive of the script ods-core/infrastructure-setup/scripts/checkout-repositories.sh is #!/bin/sh, which in case of Ubuntu 16.04 points to a dash version that does not support the **source** command which is used in line #8, resulting in the error message:
`./checkout-repositories.sh: 8: ./checkout-repositories.sh: source: not found`
Also, the script does not define set -e or similar, so execution continues in a broken state after the config file could not be read.
Most other scripts use #!/usr/bin/env bash, which appears to be a proper fix to this issue.
List of affected scripts, executing in /bin/sh:
./infrastructure-setup/conf/wildfly-init-redhat.sh
./infrastructure-setup/scripts/ansible.sh
./infrastructure-setup/scripts/checkout-repositories.sh
./infrastructure-setup/scripts/keycloak.sh
./infrastructure-setup/scripts/mirror-repositories-to-gitserver.sh
./infrastructure-setup/scripts/mirror-repos.sh
./jenkins/master/import_certs.sh
./jenkins/master/kube-slave-common.sh
./sonarqube/ocp-config/sonarqube.yml
./sonarqube/run.sh

**To Reproduce**
- on an Ubuntu 16.04 installation, checkout ods-core repository from github
- run ods-core/infrastructure-setup/setup-local-environment.sh to create the file local.config
- run ods-core/infrastructure-setup/scripts/checkout-repositories.sh

**Expected behavior**
The given config file should be sourced or else the script should fail and not continue execution in a broken state.

**Screenshots**

**Affected version (please complete the following information):**
 - all ODS versions

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
./checkout-repositories.sh: 8: ./checkout-repositories.sh: source: not found
```

**Additional context**
affected operating system: Ubuntu 16.04

**Comment by metmajer** [comment]
Resolved via #399
