### ISSUE TITLE
Update Atlassian default Atlassian tool versions

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-core#4]
Currently, we are one major or multiple minor versions behind releases:

Tool          |Default Version |available
-----------|----------------|---------
Bitbucket   |4.14.3              |5.12
Confluence|6.1.3                |6.10.1
Jira            |7.3.6                |7.10.2

Or generally speaking, we shoiuld define against which version we define certain customziations, e.g. confluence blueprint key in provisioning app.

**Comment by clemensutschig** [comment]
I suggest always latest. If nothing more latest major

**Comment by michaelsauter** [comment]
Unlinking from v1.

**Comment by tjaeschke** [comment]
Versions in #98 

Tool | Version
------------ | -------------
Atlassian Crowd | 3.4.4
Atlassian Jira | 7.13.3
Atlassian Confluence | 6.14.3
Atlassian Bitbucket | 5.16.3
Rundeck | 2.11.8-1.59.GA
