### ISSUE TITLE
Add Makefile target to test quickstarter

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#400]
We already have a guide how to test changes to a quickstarter at https://github.com/opendevstack/ods-quickstarters/wiki/Run-quickstarter-via-Jenkins. This is useful to:

* test if e.g. fixes in a branch have the desired effect
* run a quickstarter not listed in the prov app

The guide is quite technical and many errors (e.g. typos) can be made in the process. To prevent this from happening, I suggest a Makefile target that interactively asks for parameters, and then creates the pipeline and runs it, following the logs until they complete.

FYI @stitakis

**Comment by metmajer** [comment]
If we support environment variables in the Makefile, it would be easily integrable.

**Comment by michaelsauter** [comment]
Yes this task should actually not be that complicated to achieve ... it's basically just converting the guide to a script.

**Comment by michaelsauter** [comment]
Actually a duplicate of https://github.com/opendevstack/ods-quickstarters/issues/151, @sino92 will drive this topic.
