### ISSUE TITLE
Jenkins runs out of memory and becomes unresponsive

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-core#412]
**Describe the bug**
During our work on our internal ODS development environment, we increasingly see unresponsive Behavior with Jenkins. Analyzing the memory of the Java process has shown that we were too low on memory with our 2 GB settings: we ran out of heap space and had frequent garbage collector activity, which resulted in Jenkins becoming suspended frequently.

**Expected behavior**
Have a guess...

**Screenshots**

***OOM***
![PastedGraphic-1](https://user-images.githubusercontent.com/873565/74553754-49143980-4f58-11ea-9ed8-5a3bbd2437eb.png)

***Components failing randomly***
<img width="1792" alt="Screenshot 2020-02-14 at 16 23 30" src="https://user-images.githubusercontent.com/873565/74553829-6a752580-4f58-11ea-8773-5794d575b62d.png">

***Non-availability due to frequent suspension***
<img width="1792" alt="Screenshot 2020-02-14 at 16 22 35" src="https://user-images.githubusercontent.com/873565/74553842-6fd27000-4f58-11ea-8d06-4d65c0234490.png">

**Affected version (please complete the following information):**
 - OpenDevStack 2

**Proposed Solution**
1) The following article suggests tuning parameters for Jenkins using the G1 GC: https://jenkins.io/blog/2016/11/21/gc-tuning/.
2) The following article says that `-Xmx` should be set to `Xms`. It also states that `-Xmx=2g` is the absolute minimum for Jenkins: https://support.cloudbees.com/hc/en-us/articles/204859670. 
3) The following article mentions a set of environment variables to be used to put the findings out of `1)` and `2)` into practice in OpenShift: https://docs.openshift.com/container-platform/3.9/using_images/other_images/jenkins.html.

Finally, here is a screenshot of a Deployment Config from our internal development cluster with an `-Xmx=4g`. Note that the applied resource limit's upper bound needs to be set to a higher value:

<img width="1409" alt="Screenshot 2020-02-14 at 17 50 27" src="https://user-images.githubusercontent.com/873565/74554438-dc9a3a00-4f59-11ea-8404-b5392d08d117.png">

**Comment by metmajer** [comment]
@clemensutschig @michaelsauter please provide feedback on the suggested approach!

**Comment by michaelsauter** [comment]
If we need the memory for MRO, then we need to make this change.

Without MRO, I haven't seen OOM issues with Jenkins so far.

One thing to note is that unfortunately existing installations will not update automatically when you implement your proposed changes ... so we'd also need to write a small how-to.

**Comment by metmajer** [comment]
Check. The memory increase is definitely a requirement. Without the other part, the improved GC behavior, we have seen minute-long suspension times of Jenkins. If you're good to go with this, let's work out a PR.

**Comment by clemensutschig** [comment]
@metmajer  - please post the settings you added to the DC /including the key

**Comment by metmajer** [comment]
Here is the complete list of environment variables to be injected into a Jenkins master's deployment configuration.

| Name  | Value  |
|---|---|
| `JAVA_GC_OPTS`  | -server -XX:+AlwaysPreTouch -Xloggc:/var/lib/jenkins/gc-%t.log -XX:NumberOfGCLogFiles=5 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1  |
| `JAVA_MAX_HEAP_PARAM`  | -Xmx4g  |
| `CONTAINER_HEAP_PERCENT`  | 1  |

As the most simple solution, I suggest to add those 3 variables as Template Parameters into https://github.com/opendevstack/ods-core/blob/38892b9761abe9f3dc973ff161ba9ea8fbc38771/create-projects/ocp-config/cd-jenkins/cd-jenkins-master.yml and then inject them into the list of environment variables in the contained `DeploymentConfig`s list of container environment variables.

**Comment by metmajer** [comment]
To fix the memory issues, the following parameters will need to be adjusted as follows:

```
- name: JENKINS_MEMORY_LIMIT
  value: 5Gi
- name: JENKINS_MEMORY_REQUEST
  value: 2Gi
```

**Comment by metmajer** [comment]
@hrcornejo I have updated `JAVA_GC_OPTS` and removed the print options. Please adjust!
