### ISSUE TITLE
Webhook Proxy does not run under jenkins serviceaccount

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#413]
**Describe the bug**
The OCP template does not define the `serviceAccount` to use, but it should be `jenkins`, the same account that the Jenkins master instance uses.

**Affected version:**
 - OpenShift: all
 - OpenDevStack: 1.2.x, 2.x

**Comment by clemensutschig** [comment]
What? We fixed this now how often?

**Comment by michaelsauter** [comment]
I think it is fixed locally but not pushed upstream. I am about to create a PR.

**Comment by michaelsauter** [comment]
I believe https://github.com/opendevstack/ods-core/blob/master/create-projects/create-projects.sh#L23 hides this problem (which is why 2.x works as is ...)
