### ISSUE TITLE
Scripted Nexus Setup

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-core#42]
The setup of blob store and repositories should be handled by a [groovy script](https://help.sonatype.com/repomanager3/rest-and-integration-api/script-api/writing-scripts#app) in nexus3.
The script can be uploaded and executed through the [rest api](https://help.sonatype.com/repomanager3/rest-and-integration-api).

**Comment by michaelsauter** [comment]
@stitakis FYI this was the ticket I mentioned. The documentation for the current repos is at https://github.com/opendevstack/opendevstack.github.io/blob/f5b86d59a2c3bc318025d2380931f168175e3b15/doc/getting-started.md#setup-and-configure-nexus3.

**Comment by stitakis** [comment]
I think we could add an additional repository called "snapshots". This repo is used by maven to upload snapshot version of jars. It differs to "candidates" repository by the "Version Policy" because it needs to allow upload of jars with the same name. To support that functionality the "Version Policy" should be set to "Snapshot".

**Comment by clemensutschig** [comment]
@tjaeschke @rattermeyer  - is this sth for 1.1?... just asking...

**Comment by rattermeyer** [comment]
yes, should be. is in the infrastructre refactoring PR #98 infrastructure-setup/scripts/prepare-nexus.sh

**Comment by clemensutschig** [comment]
@tjaeschke - we want to close 1.1 asap ... so either out or in .. make your call *today*

**Comment by tjaeschke** [comment]
@clemensutschig Like @rattermeyer said, this should be in.

**Comment by clemensutschig** [comment]
@rattermeyer  - we need a date .. we want to cut 1.1. ....

**Comment by tjaeschke** [comment]
Implemented in #98
