### ISSUE TITLE
Grant jenkins service account rights to administer its own cd project

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-core#420]
**Is your feature request related to a problem? Please describe.**
While Jenkins SA is admin over dev and test projects, it doesn't hold the same rights for itself. Only those can: 
1. cluster-admin
2. project-specific developer

A third group - flow team - can reduce dependency on the first two groups especially when the task is to free up resources and clean up unused/inactive projects.
As provisioning app doesn't yet support project deletion feature for any of the aforementioned group types, flow team shouldn't be dependent on the two groups to remove the project.

**Describe the solution you'd like**
Add this line below: https://github.com/opendevstack/ods-core/blob/996cc57e6defe8a8b027bd152543cf20bea7c27c/create-projects/create-projects.sh#L20
`oc policy add-role-to-user admin system:serviceaccount:${PROJECT_SUFFIX}-cd:jenkins`

**Comment by michaelsauter** [comment]
@sino92 I actually think it is better that it does not have admin rights. It does not need it right now, so the principle of least permission applies.
