### ISSUE TITLE
Nexus repo setup script missing in ods-core

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#423]
**Describe the bug**
I remember there was a script/groovy sth? that setup the repos in nexus... is this gone now?

@michaelsauter  / @tjaeschke

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/createRepos.json

why are those not in the nexus folder? ...

**Comment by michaelsauter** [comment]
@clemensutschig I agree, they should be. We should put work into the cluster setup asap.

**Comment by clemensutschig** [comment]
@michaelsauter  - if for nothing else, we should colocate the needed config(s) within the corresponding folders 

- Nexus
-- https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/createBlobStores.json
-- https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/createRepos.json
-- https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/createRole.json
-- https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/createUser.json
-- https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/deactivateAnonymous.json
-- https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/developer-role.json
-- https://github.com/opendevstack/ods-core/blob/master/infrastructure-setup/scripts/json/developer-user.json
