### ISSUE TITLE
Removal of non-essential operational scripts

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-core#447]
I propose that we remove non-essential operational type scripts from ods-core. Having these operational scripts seem a bit odd to have in ods-core to me. 

In particular:

- scripts `check-unsecured-routes.sh` and `list-routes-status.sh`in [ods-core/ocp-scripts at ae327a3371](https://github.com/opendevstack/ods-core/tree/ae327a337146ba2ab8220d1e45d771af7525562e/ocp-scripts).
- the associated Jenkinsfile and Openshift config at [ods-core/check-ocp-secure-routes at ae327a3371](https://github.com/opendevstack/ods-core/tree/ae327a337146ba2ab8220d1e45d771af7525562e/check-ocp-secure-routes)

@michaelsauter, @gerardcl, @stefanlack, @tjaeschke , @kiwo : let me know if you have concerns or suggestions. Thanks!

**Comment by gerardcl** [comment]
as said in the PR: fine to remove, but we can also provide them in another way or really integrate them from scratch (so to really be in use by default)
