### ISSUE TITLE
ODS CI infrastructure deployed in AWS

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#470]
**Is your feature request related to a problem? Please describe.**
Due to missing automated CI for ODS integration problems are discovered too late. CI will allow devs to react faster and fix integration issues earlier.

**Describe the solution you'd like**
Setup a CI for ODS in AWS (AWS-ODS-CI).
Reuse/enhance tests and scripts defined in ods-core/tests

How github with AWS integration would work:
A GitHub webhook will send a notification (http request) to AWS-ODS-CI on following event:
- on PR merge triggered (auth by CI-Runner based on project/branch whitelist: i.e master, 2.x)
- notification will include GITHUB PROJECT NAME, BRANCH_NAME, CLIENT_ID and AUTH_CODE for authentication and authorization. (CLIENT_ID and AUTH_CODE stored as github secrets) 
- Note: PR merge can only be triggered after PR approval (or by admins). This will mitigate risk of executing devs adding malicious code and get it executed in AWS-ODS-CI (which could be the case i.e if CI is triggered on each commit).     

How AWS-ODS-CI would look like:
- A CI-Runner will expose an endpoint that will process the github notification 
- The CI-Runner will authorize requests (based on CLIENT_ID and AUTH_CODE and on project/branch whitelist: i.e master, 2.x)
- After this, it will spin up a EC2 machine to install ODS on it. (NOTE: this EC2 machine needs to be sandboxed as much as possible (security policies, roles, VPC, etc...))
- Integration test will be triggered after ODS installation. 
- Next the EC2 machine with latest ods-core (master or 2.x) machine will be stored as image (to be defined how). This will allow devs to reuse it i.e for CI of ods-quickstarters.  
- Emails can be triggered to notify failures. In this case, devs should be enable to A. log into CI-Runner and see logs and B. also able to connect EC2 machine to debug it. 
- If all succeeds the merge on github could continue and completed.

Benefits of this solution
- It will allow us to setup EC2 machines with enough resources to run the ods test and solve current limitation of github actions environment.
- It will allow us to create EC2 images with ODS installed to be reused for other purposes.
- Secrets to connect to other infrastruce can be kept private in the AWS-ODS-CI infrastructure. This will allow use to eventually connect to real bitbucket servers
 

**Describe alternatives you've considered**
Currently ODS tests are running as github actions but they are failing. Apparently the infrastructure provided by GitHub doesn't have enough resources (this still need to be confirmed).

**Comment by stitakis** [comment]
@metmajer @clemensutschig @michaelsauter @hugowschneider @oalyman @georgfedermann @henrjk @gerardcl sounds good?

**Comment by henrjk** [comment]
A variant would be to have the AWS-ODS-CI not create a fresh ODS install on every build.

Perhaps it would be created once a day or some other schedule. Security concerns could be mitigated enough to make this viable by also monitoring resource consumption.

**Comment by henrjk** [comment]
If I am not mistaken one drawback is that this will exclude to do a subset of tests when pull requests are made (or updated). 
Reason would be that such a PR could change the GitHub action workflows as well, and then execute unreviewed code on the AWS-ODS-CI.

**Comment by gerardcl** [comment]
hi! IMHO before going to too custom/fixed solutions (which might increase tech. debt) I would try to explore opensource facing services that could still provide us what we require (since this is an opensource project). Here I am providing a well-known list of possible CI and CD providers we could still test: https://free-for.dev/#/?id=ci-and-cd 

Also, to point out that AFAIK there was a proposal in the last meeting to test a bit more current implementation.

**Comment by michaelsauter** [comment]
As an update - I figured out that the reliable tests for Tailor use Travis. I can't get them to run on Github Actions. And @hugowschneider tried Travis back then, which led to errors so he switched to Github Actions ...

**Comment by michaelsauter** [comment]
FYI I think https://buildkite.com/docs/tutorials/elastic-ci-stack-aws could also be an option to look into. It is built as a companion to Buildkite, which is a CI runner for private infrastructure. Buildkite is free for open source.

**Comment by tbugfinder** [comment]
FYI https://040code.github.io/2020/05/25/scaling-selfhosted-action-runners

**Comment by hugowschneider** [comment]
FYI: During #600 we had disk pressure issues reported by OC during the build of Jenkins images, I guess this is the root of the problem in both CI/CD infrastructures.

**Comment by stitakis** [comment]
@s2oBCN fyi
