### ISSUE TITLE
Jenkins becomes "unresponsive" and does not start new job runs

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#473]
remove **$JENKINS_HOME/.kube** and restart. that makes it work! finally I found it..

@metmajer  @michaelsauter

**Comment by clemensutschig** [comment]
@gerardcl  - here is our guy I guess, not even jenkins restart helps ... :( I could imaging if I wipe the vpc - there is no sq information there ... and thats why its working .. this is really a WTF...

**Comment by clemensutschig** [comment]
and from this point on -. there is no way out .. restart does not help .. nothing .. I have no idea if this is really it - but there must be something burried ... (I don't see anything suspicious in the threaddump) ..

**Comment by clemensutschig** [comment]
/logs and /caches deletion and restart did not help

**Comment by clemensutschig** [comment]
flipping to a new pvc - made it work (and restarted the builds that never started ... there must be something in the openshift plugin I guess).. this is reall really really weird..

**Comment by michaelsauter** [comment]
Could also be somehow related to the Sonar plugin. We use version 2.6.1, and 2.11 is available, see https://plugins.jenkins.io/sonar/.

**Comment by gerardcl** [comment]
shall we anyway upgrade to latest sonar plugin version?

**Comment by michaelsauter** [comment]
@gerardcl Recorded in #478.

**Comment by clemensutschig** [comment]
something is stored in `.kube` that gets corrupted, or invalid? ...

**Comment by gerardcl** [comment]
hi! more insights:
1- upgrading to a cluster to ODS2.1 there was a race condiction: jenkins redeploying and a job in progress <- that seems a way to reproduce
2- the errors that appeared in jenkins logs when trying then to run jobs where sonar plugin crashes <- that seems unrelated but is what is shown when manually triggering jobs without success

**Comment by clemensutschig** [comment]
I am wondering if we should not delete `.kube` on every start,.. what's your thoughts?

**Comment by gerardcl** [comment]
I would like to test it, but makes sense, that seems a not necessary folder to be kept anyway!

**Comment by michaelsauter** [comment]
I just witness a case where deleting `.kube` fixed an issue as well (pipelines wouldn't start, but also Jenkins did not show any pipelines at all anymore).

However, I don't know if deleting `.kube` on boot works because I believe that is how the pod is "logged in" to OpenShift. You'd need to delete it on shutdown somehow, no?

**Comment by gerardcl** [comment]
I will try that too... but anyway I have tried to reproduce the issue, for example, by coming from a 1.2.x jenkins to a 2.x one, but still not suffering that issue... I have even tested triggering the deployment while having a pipeline running and so on... have any of you been able to reproduce it again?

**Comment by clemensutschig** [comment]
bingo - I found it - if the cluster is relocating pods (e.g. cluster resources) - the thing breaks it seems
