### ISSUE TITLE
Webhook Proxy: Can't set a desired pipeline name

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-core#479]
**Is your feature request related to a problem? Please describe.**
I am currently setting a cronjob using OC template. The cron job triggers a Jenkins pipeline. Currently the pipeline of the cron job is associated with a specific branch name: https://github.com/opendevstack/ods-core/blob/0d2238f8eeafb844b63eb5c7dbb467d7b5b87d6e/jenkins/webhook-proxy/main.go#L301 
I think it makes more sense to name the pipeline based on what it does, i.e. track projects, check security etc.. and become branch independent. Otherwise if I delete the feature branch, then the pipeline will be gone. This isn't desired behavior for a cron job.

**Describe the solution you'd like**
Allow provided query values to set pipeline name. If nothing is provided, then it defaults to method above. Example request:
`${WEBHOOK_URI}/build?pipeline_name=${PIPELINE_NAME}&...`
```
pipelineNameParam := queryValues.Get("pipeline_name")
if pipelineNameParam != "" {
	pipeline = pipelineNameParam
} else {
        log.Println(
		"Pipeline name not given. Making a new pipeline name",
	)
        pipeline := makePipelineName(project, component, req.Branch)
}
```
@michaelsauter @henrjk @oalyman What do you think?

**Comment by michaelsauter** [comment]
This should be possible via https://www.opendevstack.org/ods-documentation/ods-core/latest/jenkins/webhook-proxy.html#_parameters. Does that solve your issue? If so, please close.
