### ISSUE TITLE
MRO & Webhook proxy - creation of pipelines for *-q / *-p branches

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#484]
Today webhook proxy creates a pipeline for each tag  per default (and in the MRO case for `v*-p` and `v*-q`). In this case they will always come with a `[ci skip]` commit, and the jenkins shared lib skips the build, rightly (but still flags the commit to be built with the skipped build of jenkins)..

![image](https://user-images.githubusercontent.com/40628552/79633969-06ddc300-8168-11ea-9196-a7d26be596db.png)

![image](https://user-images.githubusercontent.com/40628552/79643582-f8ad9800-81a3-11ea-8df6-8bd2b9994b3a.png)

As we don't want people to execute those tags anyway - we could also just skip the creation of the pipeline for this pattern entirely .. (and flag the commit with the mro build, which I would like much better). I would suggest we create a reserved pattern - e.g. `ods-generated-v*-env` for the tag that we exclude from building in the webhook proxy

@michaelsauter  - open question :)

**Comment by clemensutschig** [comment]
I changed the tag names in MRO now
![image](https://user-images.githubusercontent.com/40628552/79645290-bb023c80-81ae-11ea-9e51-1f782d44f906.png)

**Comment by clemensutschig** [comment]
The longer i think about it we dont want anyone to build the tag (standalone) itself.. because to make this work there is many steps required

**Comment by michaelsauter** [comment]
Agreed - this has already been implemented in master though: #450.
