### ISSUE TITLE
Extend sync repos script with source and target ref

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#486]
Right now, only one ref can be given, which is used as both source and target. This works well if one lives on `2.x` or `master`, and wants to simply sync that. If someone lives of a custom branch (such as `production` or `2.x.custom` or so), it would be helpful to specify source ref (what to pull, e.g. `master`) and target ref (what to push, e.g. `production`).

**Comment by clemensutschig** [comment]
See https://github.com/opendevstack/ods-core/blob/master/ods-setup/repos.sh#L62-L66
