### ISSUE TITLE
Publish ods images to Docker Hub

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#490]
Discussion from https://github.com/opendevstack/ods-core/pull/456:

From @clemensutschig:

> why NOT on github in our org - this is now fully supported (tab pacakges)

We should figure out if we want to store our images in Docker Hub or GitHub, or both?

FYI @henrjk @clemensutschig @oalyman

**Comment by oalyman** [comment]
Ah cool, wasn't aware of GH packages. I would vote for publishing to both.

**Comment by stitakis** [comment]
If there are no drawbacks, I vote for publishing to both too.

**Comment by michaelsauter** [comment]
I think publishing to both might cause confusion which one to pull.

**Comment by oalyman** [comment]
@michaelsauter @clemensutschig Will we stick with dockerhub? Then we can close this.

**Comment by clemensutschig** [comment]
dockerhub / opendevstackorg
