### ISSUE TITLE
Publish Jenkins images / migrate to UBI for ODS 4

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#491]
I'm not sure for Jenkins-master, jenkins-slave-base and jenkins-webhook-proxy. Because all three can be easily built from source, and some of them depend on local "state":

- is it Redhat or CentOS based?
- which version of OpenShift is used?
- for the Jenkins master, it would have been nice to bake in a config file into the image (edition of SonarQube)

FYI @henrjk @oalyman @clemensutschig

**Comment by henrjk** [comment]
Another state is the certificate authority configuration. We could move this to the runtime similar to https://github.com/opendevstack/ods-provisioning-app/pull/406.

**Comment by henrjk** [comment]
Another obstacle would be how we would tag those images.  For example at https://quay.io/repository/openshift/origin-jenkins?tab=tags one can see how v4 images are  tagged  (source on openshift/jenkins).

**Comment by henrjk** [comment]
Experimenting with building a jenkins master image from the redhat UBI image `quay.io/openshift/origin-jenkins:4.3`. 

The image was modified to not do the certificate authority configuration and another minor change. It was building without errors.

I also tested deploying it to an existing ods project in our openshift cluster. It started up and the web ui is available. 
However I have not yet tried to have it actually build stuff. This would be the next step. 

See branch https://github.com/BIX-Digital/ods-core/tree/task/experiment-with-jenkins-builds for details.

**Comment by henrjk** [comment]
I also checked with RedHat via a support request whether there are UBI images we could use.

The Openshift Jenkins team responded: 
a) There are no ubi based images on 3.11
b) Using v4 jenkins UBI images for v3.11 has not been tested, and some plugins present in the 4.x images may be incompatible with 3.11.
c) Advice to migrate to ocp v4.

While in my experiment the 4.x ubi appear to work for us on OpenShift 3.11, my recommendation is to not pursue this until we are on Openshift v4.

**Comment by michaelsauter** [comment]
@oalyman Do you still want to give this a shot, or should we keep it like it is for 3.0 - and revisit once we move to OpenShift 4?

**Comment by oalyman** [comment]
@michaelsauter I think we agreed on moving it to the time we create a ODS release for Openshift 4

**Comment by michaelsauter** [comment]
We have UBI8 images for OpenShift 4 now.
