### ISSUE TITLE
Move Jenkins Jobs into one folder

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#501]
Currently we have `create-projects`, `delete-components` and `delete-projects`. I propose to have those located under a folder named `jenkins-jobs`.

**Comment by clemensutschig** [comment]
I thought the same. Why Not move under jenkins/project-jobs

**Comment by michaelsauter** [comment]
Since we're not attempting this for v3, and it might actually be harder for users to find, I'm closing this.
