### ISSUE TITLE
Base ods-provision app & ods-doc-gen service on imagestreams rather than having only a DC

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#505]
**Is your feature request related to a problem? Please describe.**
instead of directly referencing an image out of the DC(s) - as in https://github.com/opendevstack/ods-core/blob/master/provisioning-app/ocp-config/dc.yml#L33-L34 we should create a local image stream - so people can also tag from contributions into it.

@michaelsauter  fyi

**Comment by oalyman** [comment]
@clemensutschig I think you resolved this with https://github.com/opendevstack/ods-core/pull/547

**Comment by clemensutschig** [comment]
nope - not entirely ... the dc of ods-provision-app - still points directly to an image .. do you fix this?
https://github.com/opendevstack/ods-core/blob/master/ods-provisioning-app/ocp-config/dc.yml#L33

vs..  https://github.com/opendevstack/ods-provisioning-app/blob/master/openshift/dc.yml#L29

**Comment by oalyman** [comment]
Closed by #563
