### ISSUE TITLE
Rename /and change labels of provision application

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#506]
https://github.com/opendevstack/ods-core/blob/f95d9314b4011d4d9b03746e0fd46e923092935d/provisioning-app/ocp-config/dc.yml#L14-L16

I strongly vouch to change the name /and labels to `ods-provisioning-application`

**Comment by oalyman** [comment]
@clemensutschig I think you did this already, right?

**Comment by clemensutschig** [comment]
@oalyman  - yeahh ... https://github.com/opendevstack/ods-core/blob/master/ods-provisioning-app/ocp-config/cm.yml#L74 

for the `ods-provisioning-app` - it's still prov app -> https://github.com/opendevstack/ods-provisioning-app/blob/master/openshift/cm.yml#L74

happy to close, if you are ok ..

**Comment by clemensutschig** [comment]
@oalyman ping

**Comment by michaelsauter** [comment]
I guess we leave this for now.
