### ISSUE TITLE
ODS Dev Env automated installation on centos

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#510]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for installing an ODS development environment in a virtual machine. 

**Describe the solution you'd like**
Fully scripted automated installation of ODS basic components on a centos 7.7+ VM.
An installation script will install openshift and ODS (as first iteration just without Atlassian stack, nexus and sonarqube)
An E2E Test "Project creation" will verify that the installation is working properly and is fully functional.
For the implementation of the required script we will reuse the tests script done in the past (currently running as github actions).

**Comment by hugowschneider** [comment]
There are a series of examples of automated virtual machine creation in this repo.

https://github.com/geerlingguy/packer-boxes

I tested ubuntu and centos and they worked for me.

**Comment by stitakis** [comment]
duplicated in #549... closing this item
