### ISSUE TITLE
Fetch shared lib from github per default instead of requiring "local" clone on bitbucket

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#518]
With the new ods default setup - I am wondering if we should not fetch the shared lib directly from github per default?!

This would allow us to remove yet another "install step" ... so instead of 
https://github.com/opendevstack/ods-core/blob/master/jenkins/master/configuration/init.groovy.d/ods-jenkins-shared-library.groovy#L17

we would seed the github url :)

@michaelsauter?

**Comment by michaelsauter** [comment]
Why not? Sounds good to me. However I think we would simply adjust the installation to not sync the library, and then default the env variable we read to the GitHub url ... ?

**Comment by clemensutschig** [comment]
Yeah correct ... One piece less to Sync.. install... ;-)
