### ISSUE TITLE
Change default branch from production to master

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#523]
To simplify, we will make `master` the default, not `production`.

**Comment by clemensutschig** [comment]
@michaelsauter - why Not make configurable? That way we would allow Side by side ods installations with different Branches..  ;-)

**Comment by michaelsauter** [comment]
Oh yes, we leave it configurable. But the default should not be `production`, it should be `master` ... :)

**Comment by clemensutschig** [comment]
Check ;)

Michael Sauter <notifications@github.com> schrieb am Di., 5. Mai 2020,
10:31:
