### ISSUE TITLE
Jenkins create/delete.. project jobs dont use shared library 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#526]
**Describe the bug**
While all quickstarters use the Shared lirbary - in the main create/... jobs we have the same code duplicated..

Create Project job : https://github.com/opendevstack/ods-core/blob/master/create-projects/Jenkinsfile

The Master instance has the Shared lib available.. 

Secondly i strongly vouch to have those jobs inside the jenkins directory..  

@michaelsauter - was the Design intended this way or accidential?

**Comment by michaelsauter** [comment]
They don't make use of the pipeline features, I'd probably leave them like they are - it's only three pipelines that rarely change.

**Comment by michaelsauter** [comment]
There's not much they could share, so let's keep them as simple as possible.
