### ISSUE TITLE
Add PHP plugin to Sonarqube

### ISSUE THREAD

**Issue by villanlu** [opendevstack/ods-core#536]
**Is your feature request related to a problem? Please describe.**
Can't scan PHP projects with Sonarqube

**Describe the solution you'd like**
Add to Sonarqube Dockerfile: https://binaries.sonarsource.com/Distribution/sonar-php-plugin/<latest version>

**Describe alternatives you've considered**
Use other scanning solutions

**Comment by clemensutschig** [comment]
Easy for ods 3.. why dont von submit a pr? The addition is in sonarqube/dockerfile

**Comment by villanlu** [comment]
@clemensutschig pr created: https://github.com/opendevstack/ods-core/pull/537
