### ISSUE TITLE
Add make to the slave-base

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-core#539]
**Describe the solution you'd like**
We would like to see `make` added as an essential build tool for our slave-base.

**Additional context**
Mentioned in https://github.com/opendevstack/ods-quickstarters/pull/260

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-core/blob/master/Makefile#L56 - closing as done

**Comment by michaelsauter** [comment]
I think @metmajer meant to have `make` available as a built tool on the agent image. However, that is also already done. I checked on an agent base image from `master`:
```
+ make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
```
