### ISSUE TITLE
Webhook Proxy: Allow to protect all branches or branches with certain prefix

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#55]
Right now, Jenkins pipelines can only be protected by branch name, defaulting to `master,develop,production,staging,release`. We should allow users to protect all branches (`*`) and branches with a certain prefix (as in, ending in a slash, e.g. `release/`, `feature/`).

**Comment by clemensutschig** [comment]
@michaelsauter  - isnt' that a shared lib thing? - if so - just move it over thru 

![image](https://user-images.githubusercontent.com/40628552/52119284-e4ba5c80-2618-11e9-96dc-8efa5a5a2622.png)

**Comment by michaelsauter** [comment]
@gerardcl The idea is to have the same control as in the shared library:

1. exact match (what we already have)
2. prefix match (starts with e.g. `release/`)
3. wildcard (all branches)

You can see the configured default in the log of the webhook proxy.
