### ISSUE TITLE
Cleanup various infrastructure setup folders / approaches

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#550]
Today we have various folders and approaches to infrastructure setup - namely

1. https://github.com/opendevstack/ods-core/tree/master/infrastructure-setup
1. https://github.com/opendevstack/ods-core/tree/master/ods-setup
1. the work @georgfedermann  is doing

I would strongly vouch to remove the "old" infrastructure setup folder - in lieu of the new approach ...

thoughts anyone? @michaelsauter @hugowschneider @georgfedermann

**Comment by clemensutschig** [comment]
related to #549

**Comment by metmajer** [comment]
I second that, since the new approach allows for better portability and is closest to our testbed used via GitHub Actions.

**Comment by michaelsauter** [comment]
Yes we will need to remove duplicated stuff for sure. I kept it there for now as the stuff in`infrastructure-setup` might serve as a reference point how to create the "new VM" ...

However, there is one part in `infrastructure-setup` which is not made obsolete by something else yet, and that is the Ansible-based Atlassian setup. @georgfedermann doesn't use that in the VM, but if you want to install a "production ODS", you probably want to use sth. like this ...
