### ISSUE TITLE
Add helm/kubectl to tools

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-core#551]
**Is your feature request related to a problem? Please describe.**
The current way ODS builds and deploys to OpenShift is quite opinionated. That makes it hard to deploy more demanding infrastructure.

**Describe the solution you'd like**
I would like to be able to use custom deployment descriptors that are under my control when deploying to OpenShift.

OpenShift 4 is converging towards more "standardized" kubernetes resources (e.g. planning to remove DeploymentConfig in favor of Deployment in the future). This makes "native" (as in kubernetes native) tools a prime target to be available.

Helm is one of the tools where a large community exists and already provides lots of advice and documentation. Since the advent of helm v3 there's no need for privileged components (like tiller) in the cluster. 

**Describe alternatives you've considered**
tailor and OpenShift templates. Both seem insufficient when dealing with more complex environments that should be able to get deployed from a single source of truth.

**Additional context**

**Comment by michaelsauter** [comment]
So what exactly would you like to see? Would your requirement be met by installing the `helm` binary into the slave?

Installing `kubectl` is not needed I think, as you have `oc` installed already, which is just a wrapper around `kubectl`.

I'm wondering if you have tried to work with Tailor / OpenShift Templates. What limitations are you facing that makes the use of those insufficient? Please refer also to the Helm vs. Tailor comparison here: https://github.com/opendevstack/tailor#tailor-vs-helm, which outlines why Helm might not be the best choice (right now).

**Comment by serverhorror** [comment]
Yes, all I want is a helm/kubectl. I'm grabbing this in the Jenkinsfile so it's not a huge problem.

Of course it's easy enough to get them via curl. Then again: `skopeo` is already provided so those two tools seem like a natural addition.

We're trying to minimize the code that we have to write/maintain. That means that a few underlying tools rely on `kubectl` being available _or_ we would have to maintain our own version of scripts. 

Limitations of OpenShift Templates:
* It is a single, gigantic file. That would mean that we have to put all the configuration in a single file. These files are a mix of JSON, INI, python, you name it (don't ask, it's just the way the software was written). Having the ability to put them somewhere else will give us easier editing capabilities (ever tried to edit Python/YAML embedded in YAML and keep the indentations OK or edit a complex structure -- as said sometimes people have the idea of using code as a configuration file?)

Limitations of tailor:
* relies on OpenShift templates (see above)
* tailor has 2 contributors, helm >400

In all fairness, if you want to make a point on the shortcomings of helm:
* It is easy to have imperative deployments rather than declarative -- but I don't have enough experience with tailor to make a fair comparison :)

**Comment by michaelsauter** [comment]
@serverhorror Thanks.

I think adding `helm` is relatively easy, and given its huge adoption (outside the OpenShift world), a nice addition to the Jenkins images. I would say why not?

Regarding OpenShift Templates: They don't need to be one file. You can have as many templates as you want - Tailor will collect all of them and merge resources from all into a single list.

Your limitations of Tailor are fair, but keep in mind that Tailor basically just adds diff on top of existing `oc` functionality. That means that (besides diffing, which eventually will be replaced by native Kubernetes functionality once available in OpenShift) all it does is running actual `oc` commands. You can see that easily by running `tailor -v`. Therefore if you use Tailor, you are basically using `oc`, which has a lot of contributors.

**Comment by michaelsauter** [comment]
Should we install `helm` in the base image for v3? @serverhorror would you open a PR that does that?

**Comment by michaelsauter** [comment]
Just to follow up on this:

* OpenShift 4.3 adds Helm as a TP: https://www.openshift.com/blog/openshift-4-3-deploy-applications-with-helm-3
* OpenShift 4.4 seems to fix the issues with OpenShift-only resources such as `BuildConfig`: https://access.redhat.com/errata/RHBA-2020:0581

So we're definitely seeing RedHat working to have first-class support for Helm. So even more reason to add `helm` as a binary into the agent image. @serverhorror Do you want to contribute this?

Once ODS is OpenShift 4 only (maybe in ODS 5?) we can think about deeper integration of ODS with Helm. Related to that: there is a tool that allows to convert OpenShift Templates to Helm charts: https://github.com/redhat-cop/template2helm.

**Comment by serverhorror** [comment]
Hey,

Sorry for not getting back, we now have better examples of why `helm` and `kubectl` are a welcome addition (recent versions please, kubectl 1.18 works perfectly fine with a 1.11 cluster).

We do work with external vendors and they provide us with resources like plain Kubernetes files or helm charts -- those are paid and unpaid collaborations; so we do not always have the choice of throwing money at them to change the things they provide us with.

Our basic goal is that we needwant to be able to support multiple environments from a single source, so deploy to ODS and a plain Kubernetes like EKS or maybe even something unmanaged (we run all of those variants due to various reasons).

Here 
* [openrefine.zip](https://github.com/opendevstack/ods-core/files/5400333/openrefine.zip) -- "in house" needs to go to ODS and an EKS cluster
* [nf-tower-deployment.zip](https://github.com/opendevstack/ods-core/files/5400349/nf-tower-deployment.zip) -- commercial package; we want to be able to use it in ODS to deploy/test out things; the production deployment will need to go to EKS because of resource constraints
* [ordino_bi_vienna_deployment.zip](https://github.com/opendevstack/ods-core/files/5400355/ordino_bi_vienna_deployment.zip) -- collaboration (unpaid); should be able to be deployed from ODS and run within ODS
* [coral_bi_vienna_deployment.zip](https://github.com/opendevstack/ods-core/files/5400359/coral_bi_vienna_deployment.zip) -- same as above

Given the above, how would you configure this so one can change parameters and have multiple deployments at the same time?

I hope those examples help.

**Comment by michaelsauter** [comment]
Hmm, currently you would need to write the logic yourself in the Jenkinsfile. Going forward, the next step could be to allow Helm to be used in the release manager process. But that needs more investigation.

How about doing the first step and adding `helm` to the agent image for the next ODS version? Then it is easier for you to write your own deployment logic.

One more note: currently ODS focuses only on OpenShift, there is no deployment to plain Kubernetes (and I don't think that will change soon, at least personally I don't see that happening). For just deploying a single component to multiple clusters, https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/vars/withOpenShiftCluster.groovy might be handy.

**Comment by serverhorror** [comment]
We already run a `cloud-tools` image with various aditions.

I like the `withOpenShiftCluster` idea. Would that work, together with release manager, so that we can deploy to:
* dev
* test
* prod-loc1, prod-loc2, prod-loc3 (for example)

I'm thinking about the `environments` section. Or would this be better suited to be reported in the shared library.

Wrt. OpenShift vs. kubernetes, as long as we are able to log in to a remote cluster -- and have a working kubeconfig -- I think our case is fine. Logging in and providing a working kubeconfig is, as I see it, our responsibility.

**Comment by michaelsauter** [comment]
Two notes:

* https://github.com/opendevstack/ods-jenkins-shared-library/issues/496 will bring the capability of `withOpenShiftCluster` to `odsComponentStageRolloutOpenShiftDeployment`. This would be unrelated to the release manager. However, the release manager will also get the multi-cluster deployment capability later on.

* I'm working on Helm support in https://github.com/opendevstack/ods-jenkins-shared-library/issues/495.
