### ISSUE TITLE
Jenkins Deployment on OpenShift cluster fails

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#561]
**Describe the bug**
Following the ODS installation instructions as provided here: https://www.opendevstack.org/ods-documentation/opendevstack/3.x/administration/installation.html.

After having successfully setup the ODS namespace and having installed nexus in OpenShift by running
```
make install-ods-project 
make install-nexus 
make configure-nexus
```
the attempt to install jenkins by running
```
make install-jenkins
```
will fail in the target start-jenkins-build-master with
```
Pulling image openshift/jenkins:2 ...
error: build error: failed to pull image: API error (404): {"message":"pull access denied for openshift/jenkins, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}
 ```
Trying to fix the issue by running the script
```
ods-core/ods-setup/setup-jenkins-images.sh
```
first fails because there the old namespace cd is still in use. Fixing this, tailor with fail with 
```
+ cd ods-setup/../jenkins/ocp-config
+ tailor -n ods apply --non-interactive --param=ODS_GIT_REF=master
Comparing templates in . with OCP namespace ods.
Found 14 resources in OCP cluster (current state) and 0 resources in processed templates (desired state).

No items where found in desired state. Are there any templates in .?
```
because it doesn't find templates in the specified folder location.

**To Reproduce**
1. In a fresh CentOS 7 box run the ods-core ods-devenv setup script to get an OpenShift cluster with ODS integration including a nexus deployment
2. In ods-core run ```make install-jenkins``` 

**Expected behavior**
Jenkins master, slave and webhook proxy get deployed and available in OpenShift cluster.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Cloning "http://172.17.0.12:7990/scm/opendevstack/ods-core.git" ...
Replaced Dockerfile FROM image openshift/jenkins-2-centos7
Pulling image openshift/jenkins:2 ...
error: build error: failed to pull image: API error (404): {"message":"pull access denied for openshift/jenkins, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}
Please, check build jenkins-master-4 since it seems failed/not completed.
```

**Comment by clemensutschig** [comment]
Hmmm are the images avail in openshift imagestreams? As which Account you run the build?

**Comment by michaelsauter** [comment]
@georgfedermann I'll look into this today. What I can already say is that you shouldn't use `ods-core/ods-setup/setup-jenkins-images.sh`, that is from the test setup. Only what is referenced from the `Makefile` should be used by your setup script.

**Comment by michaelsauter** [comment]
Regarding the images: try `openshift/jenkins-2-centos7:v3.11`

**Comment by georgfedermann** [comment]
Will give it a try right away.

**Comment by michaelsauter** [comment]
Changed the defaults in https://github.com/opendevstack/ods-core/commit/1dff2a1b4a4ef481d88835a900950f68ff433dfa.

**Comment by michaelsauter** [comment]
Closing this as the image reference was incorrect, and the sample value is fixed now.
