### ISSUE TITLE
jenkins-master deployment in OpenShift fails because keytool cannot be found

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#575]
**Describe the bug**
Jenkins deployment in OpenShift fails. keytool cannot be found in jenkins-master container.

**To Reproduce**
1. Create DeploymentConfig in OpenShift for jenkins master using tailor
2. Start jenkins master deployment in OpenShift
3. Open jenkins-master pod log file
```
INFO: found /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
INFO: importing into cacerts
/usr/libexec/s2i/ods-run: line 12: keytool: command not found
```

**Expected behavior**
jenkins-master pod should start up

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
INFO: found /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
INFO: importing into cacerts
/usr/libexec/s2i/ods-run: line 12: keytool: command not found
```

**Comment by clemensutschig** [comment]
Hugh.. how come.. i guess its just not on the path?

**Comment by michaelsauter** [comment]
Reverted the merged PR again: https://github.com/opendevstack/ods-core/pull/576.
