### ISSUE TITLE
Add tailor CLI to Jenkins base slave

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#62]
Allows user to make use of Tailor in the Jenkins pipeline.

**Comment by clemensutschig** [comment]
@michaelsauter - I assume 0.9.1? 
**https://github.com/opendevstack/tailor/releases/download/v0.9.1/tailor_linux_amd64**

right now - and this is something we have to clean up - we have not defined a single path (directory?) - where we put all those ... it's pretty spread. thoughts?

**Comment by michaelsauter** [comment]
@clemensutschig Yes, 0.9.1 for now.

Regarding path / cleanup, I don't really see a need for this. We use a "standard" Unix location I would say. In https://github.com/opendevstack/ods-core/blob/master/jenkins/slave-base/Dockerfile.rhel7, we have either `/usr/local/<the-program>/bin` and then add this to the `$PATH`, or if it is just one binary, we place into `/usr/local/bin` which already is in the `$PATH`. 

Not sure why we would have a single path other than `/usr/local`?

The only thing we need to clean up I think is that the cnes report is currently just a jar, we should wrap it in a binary like it is done for the scanner etc.
