### ISSUE TITLE
SQ token should be automatically added into ods-core.env and file committed into BB

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#624]
Related to #549 

**Describe the bug**
The token for SQ is created during `configure SQ` (https://github.com/opendevstack/ods-core/blob/master/sonarqube/configure.sh#L187) and needs then to be manually added to the `ods-core.env` and MOST importantly, committed and pushed to bitbucket - because the `create-projects` jenkins job sets it as secret

**Expected behavior**
All the above happens automatically

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [3 / master]

**Additional context**
follow up to #623

**Comment by michaelsauter** [comment]
I'm going to work on this.

Related to https://github.com/opendevstack/ods-core/pull/622, which writes to a file but doesn't clean up. Instead of this, it should replace in `ods-core.env`.

FYI @georgfedermann

**Comment by clemensutschig** [comment]
@michaelsauter  - that (write into ods-core.env) be awesome - one less piece people need to care about .. :)
