### ISSUE TITLE
ods-setup - various edp in a box driven findings

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#625]
**Describe the bug**
1. https://github.com/opendevstack/ods-core/blob/master/ods-setup/bitbucket.sh#L113 misses ods-document-generation-templates
1. https://github.com/opendevstack/ods-core/blob/master/ods-setup/repos.sh misses ods-document-generation-templates .. here all branches and tags need to be pushed (release.* and tags and master)
1. https://github.com/opendevstack/ods-core/blob/master/Makefile#L92 and https://github.com/opendevstack/ods-core/blob/master/Makefile#L117 are NOT needed anymore - because we build wrapper images now .. 

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [3/master]

@georgfedermann - fyi ...

**Comment by michaelsauter** [comment]
Regarding the templates repo: what was your plan with https://github.com/opendevstack/ods-document-generation-svc/pull/26? Should the default be to use GitHub?

I think it might be good to configure this in `ods-core.env`, like we do with the shared lib (which defaults to GitHub now). And if someone wants to use the templates at GitHub, then we should make the syncing of the templates repo to Bitbucket optional ... or would you rather want to sync the template repo all the time?

**Comment by clemensutschig** [comment]
@michaelsauter  - that is a pretty big change - and we sync the url thru the various layers to the doc gen service (via jenkins dc -> rm quickstarter -> tailor) .. The other option would be a fallback in the codebase, if not reachable - go to github ...?

**Comment by michaelsauter** [comment]
OK. Then I suggest I add the repo to be created/synced by default. Maybe for v4 we can make it configurable, and that way avoid that the users has to sync it. 

The only annoying thing about the template syncing is that we need all tags / release branches (which is different than the other repos) ...
