### ISSUE TITLE
/tests broken and on old version

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#636]
**Describe the bug**
ods-core/tests are broken - and sit on old ocp version (3.9)
For ods 3 we have to get them at least back up and running .. - also in lieu of the work of @georgfedermann - to have at least some non manual tests.

Topics that come to my mind
a) we have a new central namespace 'ods'
b) the tests should verify that all components are there and up and running
c) the tests should create a new project and see if all components are in those namespaces deployed (webhook proxy, jenkins) and in bitbucket
d) bonus points - one quickstarter provisioned ...

**To Reproduce**
1. Go to 'ods-core/tests'
2. run 'make test"

**Expected behavior**
All tests are green and working

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [master / 3]

**Comment by georgfedermann** [comment]
cd opendevstack/ods-core/tests/
[openshift@ip-172-31-46-231 tests]$ export GOPROXY="https://goproxy.io,direct"
[openshift@ip-172-31-46-231 tests]$ echo $GOPROXY 
https://goproxy.io,direct
[openshift@ip-172-31-46-231 tests]$ make
go test -v github.com/opendevstack/ods-core/tests/create-projects -run "^(TestCreateJenkins)"
go: downloading k8s.io/apimachinery v0.0.0-20190221213512-86fb29eff628
go: downloading github.com/openshift/client-go v3.9.0+incompatible
go: downloading github.com/openshift/api v3.9.0+incompatible
go: downloading k8s.io/client-go v0.0.0-20190228174230-b40b2a5939e4
go: downloading k8s.io/api v0.0.0-20190222213804-5cb15d344471
go: extracting github.com/openshift/api v3.9.0+incompatible
go: downloading github.com/gogo/protobuf v1.3.1
go: extracting github.com/openshift/client-go v3.9.0+incompatible
go: extracting k8s.io/apimachinery v0.0.0-20190221213512-86fb29eff628
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/json-iterator/go v1.1.8
go: downloading gopkg.in/inf.v0 v0.9.1
go: extracting github.com/gogo/protobuf v1.3.1
go: extracting github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/json-iterator/go v1.1.8
go: extracting gopkg.in/inf.v0 v0.9.1
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/google/gofuzz v1.0.0
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: downloading github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: extracting k8s.io/klog v1.0.0
go: extracting github.com/google/gofuzz v1.0.0
go: extracting sigs.k8s.io/yaml v1.1.0
go: downloading gopkg.in/yaml.v2 v2.2.7
go: extracting github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: extracting k8s.io/api v0.0.0-20190222213804-5cb15d344471
go: extracting k8s.io/client-go v0.0.0-20190228174230-b40b2a5939e4
go: extracting gopkg.in/yaml.v2 v2.2.7
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/imdario/mergo v0.3.8
go: downloading golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: extracting golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: downloading golang.org/x/text v0.3.0
go: extracting github.com/spf13/pflag v1.0.5
go: extracting github.com/imdario/mergo v0.3.8
go: extracting golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: extracting golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: downloading golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: extracting golang.org/x/text v0.3.0
go: extracting golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: extracting golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding github.com/openshift/client-go v3.9.0+incompatible
go: finding github.com/openshift/api v3.9.0+incompatible
go: finding k8s.io/client-go v0.0.0-20190228174230-b40b2a5939e4
go: finding k8s.io/apimachinery v0.0.0-20190221213512-86fb29eff628
go: finding k8s.io/api v0.0.0-20190222213804-5cb15d344471
go: finding github.com/gogo/protobuf v1.3.1
go: finding github.com/google/gofuzz v1.0.0
go: finding github.com/imdario/mergo v0.3.8
go: finding golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: finding github.com/spf13/pflag v1.0.5
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding github.com/json-iterator/go v1.1.8
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding gopkg.in/inf.v0 v0.9.1
go: finding k8s.io/klog v1.0.0
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding sigs.k8s.io/yaml v1.1.0
go: finding github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: finding golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: finding gopkg.in/yaml.v2 v2.2.7
=== RUN   TestCreateJenkins
--- PASS: TestCreateJenkins (12.20s)
PASS
ok  	github.com/opendevstack/ods-core/tests/create-projects	12.211s
sleep 5
go test -v github.com/opendevstack/ods-core/tests/create-projects -run "^(TestCreateProject)"
=== RUN   TestCreateProject
WARNING: Seeding special and default permission groups is not tested yet!
--- PASS: TestCreateProject (36.18s)
PASS
ok  	github.com/opendevstack/ods-core/tests/create-projects	36.188s
sleep 5
go test -v github.com/opendevstack/ods-core/tests/create-projects -run "^(TestJenkinsFile)"
=== RUN   TestJenkinsFile
--- FAIL: TestJenkinsFile (16.71s)
    jenkinsfile_test.go:89: Could not post request: <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1">
        
          <style type="text/css">
          /*!
           * Bootstrap v3.3.5 (http://getbootstrap.com)
           * Copyright 2011-2015 Twitter, Inc.
           * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
           */
          /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
          html {
            font-family: sans-serif;
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
          }
          body {
            margin: 0;
          }
          h1 {
            font-size: 1.7em;
            font-weight: 400;
            line-height: 1.3;
            margin: 0.68em 0;
          }
          * {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
          }
          *:before,
          *:after {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
          }
          html {
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
          }
          body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            line-height: 1.66666667;
            font-size: 13px;
            color: #333333;
            background-color: #ffffff;
            margin: 2em 1em;
          }
          p {
            margin: 0 0 10px;
            font-size: 13px;
          }
          .alert.alert-info {
            padding: 15px;
            margin-bottom: 20px;
            border: 1px solid transparent;
            background-color: #f5f5f5;
            border-color: #8b8d8f;
            color: #363636;
            margin-top: 30px;
          }
          .alert p {
            padding-left: 35px;
          }
          a {
            color: #0088ce;
          }
        
          ul {
            position: relative;
            padding-left: 51px;
          }
          p.info {
            position: relative;
            font-size: 15px;
            margin-bottom: 10px;
          }
          p.info:before, p.info:after {
            content: "";
            position: absolute;
            top: 9%;
            left: 0;
          }
          p.info:before {
            content: "i";
            left: 3px;
            width: 20px;
            height: 20px;
            font-family: serif;
            font-size: 15px;
            font-weight: bold;
            line-height: 21px;
            text-align: center;
            color: #fff;
            background: #4d5258;
            border-radius: 16px;
          }
        
          @media (min-width: 768px) {
            body {
              margin: 4em 3em;
            }
            h1 {
              font-size: 2.15em;}
          }
        
          </style>
          </head>
          <body>
            <div>
              <h1>Application is not available</h1>
              <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>
        
              <div class="alert alert-info">
                <p class="info">
                  Possible reasons you are seeing this page:
                </p>
                <ul>
                  <li>
                    <strong>The host doesn't exist.</strong>
                    Make sure the hostname was typed correctly and that a route matching this hostname exists.
                  </li>
                  <li>
                    <strong>The host exists, but doesn't have a matching path.</strong>
                    Check if the URL path was typed correctly and that the route was created using the desired path.
                  </li>
                  <li>
                    <strong>Route and path matches, but all pods are down.</strong>
                    Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
                  </li>
                </ul>
              </div>
            </div>
          </body>
        </html>
FAIL
FAIL	github.com/opendevstack/ods-core/tests/create-projects	16.720s
FAIL
make: *** [test] Error 1

**Comment by clemensutschig** [comment]
@michaelsauter  - GOPROXY did the trick? ... there must be some cache behind for 3.9 :)

now we just need to fix the tests ... :)

**Comment by clemensutschig** [comment]
the problem is in 
https://github.com/opendevstack/ods-core/blob/master/tests/create-projects/jenkinsfile_test.go#L74

namely:
a) the 'nip.io' address is wrong ... :) and 
b) 'webhook-proxy-prov-cd' is wrong as well ... This should be going against the definitions in ods-configuration- - namely `ODS_NAMESPACE` and `OPENSHIFT_APPS_BASEDOMAIN`

**Comment by clemensutschig** [comment]
@metmajer - we tried them against ods in a box - and 2 already worked...!

**Comment by clemensutschig** [comment]
we also might want to take the chance to ensure that we don't have (too) much overlap @hugowschneider

**Comment by metmajer** [comment]
Yay! Well done!

**Comment by clemensutschig** [comment]
I Talked with @hugowschneider  about this.. 
Idea is Pretty simple.. extract whats usefull into ods-devenv (eg. The docker deamon part). Then remove the /Tests folder here and also in ods-quickstarters and @metmajer s Team will deliver solid e2e Tests in a new Repository for ods3

**Comment by michaelsauter** [comment]
@clemensutschig @georgfedermann I guess we can close this with the work you've done there now?

**Comment by metmajer** [comment]
I have created a new repo for the e2e tests here: https://github.com/opendevstack/ods-e2e-tests. Team is aware. FYI @martsec @jorge-romero
