### ISSUE TITLE
amend DOCKER_REGISTRY setting in default config to use 'docker-registry.default.svc'

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#638]
**Describe the bug**
setting an IP address as `DOCKER_REGISTRY` is not a good idea - especially given that this can be replaced with `docker-registry.default.svc` which works across the cluster. I tried from a jenkins pod in another project - and nslookup works .. on multiple clusters - so default is a "global project" and hence the service is available everywhere

Somewhat similar - `APP_DNS` - should point to the external route of the docker registry of OCP ... Unfortunately this is not really standardized :/ (so here we should just add a comment to the env sample)

So for docker registry either we set it in the code base /namely in ods-jenkins-shared-library:
1. https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L86-L102
1. https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/vars/odsOrchestrationPipeline.groovy#L126

or we at least default it in https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L159

@michaelsauter  - wishes? the quickfix is in ods-configuration :)

**Comment by clemensutschig** [comment]
@georgfedermann fyi.

**Comment by clemensutschig** [comment]
So i checked the codebase .. to be backward compatible..  we should amend the param / env ... in the codebase ist minimal..  all in jenkins shared lib.. 

Let me know the Route and i make it work

**Comment by michaelsauter** [comment]
Cool.

I think I prefer amending the configuration (to make that a better default). And we can add a comment that this likely does not need to be changed.

We could still remove the item from the config altogether in some future version of ODS. But maybe there is an edge case we haven't thought about yet? So I would not remove the param completely right away.
