### ISSUE TITLE
setup repos syntax error

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-core#666]
`./setup_repos.sh: line 198: syntax error near unexpected token `<'`
sh ./setup_repos.sh -g=master --confirm --sync -b=https://example.bitbucket.com

**Comment by clemensutschig** [comment]
@michaelsauter  @sino92  - hugh, this works with oDS in a box super nice .. what shell are you using?

**Comment by sino92** [comment]
zsh 5.3. I was convinced it was a syntactical bug after running the script in one of the slaves but haven't verified in another shell environment

**Comment by clemensutschig** [comment]
we ran this over an over - as part of ods-devenv ...

**Comment by sino92** [comment]
Ok, assuming dev-env is frequently updated/tested and the script has been the same since June 16th, it should be a defect on my side.

**Comment by michaelsauter** [comment]
`./setup_repos.sh` does not exist in `ods-core`? That must be some script based on an earlier version of the script here? Your shell should not matter ... the shebang dictates the script is run in `bash`.

**Comment by sino92** [comment]
I ran the one from ods-core, which was named `repos.sh`. But you're right, the name `setup-repos.sh` is based on an older version, which also ran successfully on shell. And duh.. I was trying to run it in shell again, not bash. Didn't notice the shebang in the newer version...
