### ISSUE TITLE
Latest jenkins-master:v3.11 breaks

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#670]
Latest Jenkins Master image (`v3.11.232`) from RedHat ships with Jenkins 2.222 and a bunch of new plugins. Updating to that breaks the pipelines, as new pods do not launch. The reason is that the cloud configuration gets lost somehow ... adding it back manually fixes the issue.

Workaround for now is to pin the tag to `v3.11.219`.

**Comment by clemensutschig** [comment]
@michaelsauter  - adding it back is what ... ? couldn't we check if it's there and just add it, in case it's not? ...

**Comment by michaelsauter** [comment]
Will be fixed by #672. It seems that the cloud config gets lost when Jenkins boots with the new version, but the Kubernetes plugin is still old. In that case, even updating Kubernetes later doesn't bring the config back. With the fix in #672, updating from an old to a new image preserved the config.
