### ISSUE TITLE
Specify which verison of Git repos.sh supports

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-core#680]
**Is your feature request related to a problem? Please describe.**
While running the script on our base Jenkins agent, I've noticed it wasn't properly executing a boolean statement [here](https://github.com/opendevstack/ods-core/blob/master/ods-setup/repos.sh#L191). Because the statement ended up with `false`, it was trying to reassign the already existing `ods` remote. It wasn't clear from the logs as `git remote get-url ods` standard output was suppressed.    

On another note, I believe OC centos base images ship with git version `1.8.3.1`. I imagine there are some deprecated methods since that release but it would be nice to use later versions of Git in our images.

**Describe the solution you'd like**
Clarify which version of GIT the script supports. In this [Git Release Note](https://github.com/git/git/blob/228f53135a4a41a37b6be8e4d6e2b6153db4a8ed/Documentation/RelNotes/2.7.0.txt#L13), you can see that get-url feature was added for version 2.7. It'd be extremely helpful to see that noted in the script. 

**Describe alternatives you've considered**
Don't suppress the output of `git remote get-url ods`?

**Comment by michaelsauter** [comment]
Requirements are listed here: https://www.opendevstack.org/ods-documentation/opendevstack/3.x/administration/installation.html#_server_prerequisites.

Where / How would you like to see this with `repos.sh`?

**Comment by sino92** [comment]
Ah its cool we already have the server requirements. It sounds like we need git version `>= 2.13.2` only for OC and Atlassian Suite. One can misunderstand then `repos.sh` doesn't adhere to such system requirements. In my use case, I've chosen to clone ODS codebase in a separate machine (that doesn't run OC or Atlassian) to regularly update a remote Bitbucket ODS fork. 

Maybe we can add the git version requirement to the same document and to the script itself?

**Comment by michaelsauter** [comment]
@sino92 You're right, the docs are not clear that this is a "ODS prerequisite". Do you mind updating it?

**Comment by sino92** [comment]
Sure, will do.
