### ISSUE TITLE
update prov app configuration with properties basic auth and confluence adapter

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#696]
Update ods-core.env.sample prov app 'cm.yml' and ods-devenv with latest new configuration properties:
`provision.auth.basic-auth.enabled`
`adapters.confluence.enabled`

**Comment by clemensutschig** [comment]
@stitakis  - this needs to go into two pieces.. the CM AND the sample core env

**Comment by stitakis** [comment]
@clemensutschig both are done... including the ods-devenv change in `deploy.sh` to disable the confluence adapter in ods box environment
