### ISSUE TITLE
ods-provision-app and others that pull opendevstackorg - do NOT refresh on change of latest

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#705]
**Describe the bug**
if the latest tag on dockerhub changes - one would assume that a rebuild of the "local" image pulls in the latest version of the 'remote' tag .. this does not happen

**To Reproduce**
Build the image on openshift, build a new dockerhub image and rebuild the ocp one again - it will not change - and take the local latest one.

The problem / bug is a missing flag in the docker config, `forcePull` and `noCache` need to be set to true in 
https://github.com/opendevstack/ods-core/blob/master/ods-provisioning-app/ocp-config/bc.yml#L54

@michaelsauter / @georgfedermann  fyi

**Comment by michaelsauter** [comment]
Fixed by #706.
