### ISSUE TITLE
Avoid view rights on ODS namespace

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#714]
https://github.com/opendevstack/ods-core/blob/master/ods-setup/setup-ods-project.sh#L56 is probably not needed. Only image puller rights are required.

**Comment by clemensutschig** [comment]
That would remove any possibility for a user to look what happened in Case a prov job failed..

**Comment by michaelsauter** [comment]
True. Might be wanted in some cases though? Maybe a setting whether users should be able to view project provision jobs or not. Anyway low prio I think.

**Comment by michaelsauter** [comment]
Closing as not really needed. View rights are OK and can be beneficial for us (e.g. using a central `ConfigMap` to expose central settings).
