### ISSUE TITLE
PROV_APP_PIPELINE_TRIGGER_SECRET seems to be redundant

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-core#722]
**Is your feature request related to a problem? Please describe.**
The property [PROV_APP_PIPELINE_TRIGGER_SECRET](PROV_APP_PIPELINE_TRIGGER_SECRET) seems to be redundant, since there is already [PIPELINE_TRIGGER_SECRET](PIPELINE_TRIGGER_SECRET) 

**Describe the solution you'd like**
- Remove PROV_APP_PIPELINE_TRIGGER_SECRET  from https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L276
- Replace PROV_APP_PIPELINE_TRIGGER_SECRET by PIPELINE_TRIGGER_SECRET in https://github.com/opendevstack/ods-core/blob/master/ods-provisioning-app/ocp-config/cm.yml#L59 and https://github.com/opendevstack/ods-core/blob/master/ods-provisioning-app/ocp-config/cm.yml#L208

**Comment by michaelsauter** [comment]
@renedupont Yes! Could you attempt to remove that param this week? That way we can remove it from the installation for v3.
