### ISSUE TITLE
Jenkins logs WARNING: Unknown parameter: label

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#732]
**Describe the bug**
When running Jenkins pipelines we see warning messages when the ShellStep gets executed:
```
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label
```

**Affected version (please complete the following information):**
 - Jenkins version 2.204.2

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label
```

**Additional context**
We see this behaviour when running quickstarter provisioned pipelines.

**Comment by michaelsauter** [comment]
Reverted the fix as it might have broken something else (switching dirs in pipelines).

**Comment by quanjinzhang** [comment]
any good news for this problem?

**Comment by michaelsauter** [comment]
@quanjinzhang I don't think so, seems like RedHat abandoned 3.11, espacially the non-RHEL version.

**Comment by michaelsauter** [comment]
The CentOS image for OpenShift 3.11 is definitely abandoned, see https://github.com/openshift/jenkins/issues/1109. Therefore this is a WONTFIX.
