### ISSUE TITLE
Move ods-document-generation-templates push in repos.sh to --sync part

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-core#739]
Currently, when you follow the installation documentation for ODS, at this point https://github.com/opendevstack/ods-core/blob/master/docs/modules/administration/pages/installation.adoc#repositories you can either call` ./repos.sh --init` for your first installation, or` ./repos.sh `(without init) if you already have an existing installation. 
In case of an already existing installation you have to use a bitbucket user with write permission, due to this push: https://github.com/opendevstack/ods-core/blob/master/ods-setup/repos.sh#L213

The question is if this push should only happen if `--sync` is given.

This issue is a follow up of this discussion: https://github.com/opendevstack/ods-core/pull/731#discussion_r462090986

fyi @michaelsauter

**Comment by michaelsauter** [comment]
@renedupont Can you check if this is still valid? I think this is "fixed" by now.

**Comment by renedupont** [comment]
You changed that https://github.com/opendevstack/ods-core/blob/3.x/ods-setup/repos.sh#L213 into https://github.com/opendevstack/ods-core/blob/master/scripts/repos.sh#L129 so basically the git push that required the write permission is gone. Therefore looks good to me, shall I close?

**Comment by renedupont** [comment]
was done by https://github.com/opendevstack/ods-core/pull/831
