### ISSUE TITLE
(Tests) ods (master) jenkins - misses environment vars for non standard ODS installation - in case not triggered via prov app

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#744]
**Describe the bug**
ODS JENKINS master misses
https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L23  and
https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L12

**To Reproduce**
1. Configure different to standard settings for ODS_BITBUCKET_PROJECT and ODS_NAMESPACE
1. Create new ODS Project via /tests - jenkinsfile-test.go

This will fail - on two occasions:
1. on bootstrapping the base agent in create_jenkins job - because it defaults to `ods` and 
1. on ods-configuration cloning 

**Expected behavior**
New ods project successfully created.

**Affected version (please complete the following information):**
 - OpenDevStack [3/master]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Log output here...
```

**Comment by michaelsauter** [comment]
This works as the prov app sends env vars to the Jenkins job, see https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java#L288-L291.
