### ISSUE TITLE
storage class empty make PVC creation fails

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#755]
**Describe the bug**
if parameter STORAGE_CLASS_DATA is set on "" on core.env in ods-configuration (expecting tailor  select default storage class defined in openshift)
PVC deployment fails because no storage class is defined but the attribute is set

OUR Openshift Support team recommends to use always the default storageclass as they can control the balance of them.

**Expected behavior**
in case the parameter is empty/non-set, the storage-class attribute shoudn't be set.
Then openshift will select the default storage class by default.

**Comment by michaelsauter** [comment]
@segator Where exactly does that fail?

**Comment by segator** [comment]
the  storageclass atribute is empty, and then PVC  can not deploy a PV, if we instead deploy the PVC without the attribute it chose the default storage class defined in openshift.

What i would like to see if you set the STORAGE_CLASS parameter in ods-core.env empty instead of write the attribute empty don't even write the attribute.

**Comment by michaelsauter** [comment]
@segator Can you please provide logs?

This works for me:
```
+ pvc/foobar to create
--- Current State (OpenShift cluster)
+++ Desired State (Processed template)
@@ -1 +1,17 @@
+apiVersion: v1
+kind: PersistentVolumeClaim
+metadata:
+  annotations:
+    volume.beta.kubernetes.io/storage-class: ""
+    volume.beta.kubernetes.io/storage-provisioner: ""
+  finalizers:
+  - kubernetes.io/pvc-protection
+  name: foobar
+spec:
+  accessModes:
+  - ReadWriteOnce
+  resources:
+    requests:
+      storage: 1Gi
+  storageClassName: ""


Summary: 0 in sync, 1 to create, 0 to update, 0 to delete

Apply all changes? [y=yes, n=no]: y

Creating pvc/foobar ... done
```

**Comment by clemensutschig** [comment]
@michaelsauter  . are you sure the PVC was in fact bootstrapped? --- creation is one thing - but started another ... just asking

**Comment by michaelsauter** [comment]
@clemensutschig Ah got it! I was thinking the creation failed from the description. Verified now, and yes it fails with: `no persistent volumes available for this claim and no storage class is set`.

**Comment by segator** [comment]
Yes, fails to create the pv not the pvc

**Comment by michaelsauter** [comment]
I see. I did some testing now, and the storage provisioner can be empty, but if the the storage class name is set, it does not work. 

So this works:
```
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ""
  finalizers:
  - kubernetes.io/pvc-protection
  name: foobar
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Unfortunately, the storage class name is an important setting which users may want to set explicitly. E.g. on AWS one can pick between `gp2` and `gp2-encrypted`.

Not sure what to do yet, just noting down what I figured out so far.

**Comment by michaelsauter** [comment]
From https://docs.openshift.com/container-platform/4.1/storage/understanding-persistent-storage.html#pvc-storage-class_understanding-persistent-storage:

> The cluster administrator can also set a default storage class for all PVCs. When a default storage class is configured, the PVC must explicitly ask for StorageClass or storageClassName annotations set to "" to be bound to a PV without a storage class.
>  If more than one StorageClass is marked as default, a PVC can only be created if the storageClassName is explicitly specified. Therefore, only one StorageClass should be set as the default.

@segator Could you follow up on this? How is are the storage classes configured in your cluster?

**Comment by michaelsauter** [comment]
OK.

We figured out that empty `storageClassName` means manually provisioned PV in that cluster.

Given it is possible to specify the default storage class explicitly, we won't fix this - until we find a really easy solution to do it.
