### ISSUE TITLE
make configure-nexus allow insecure connection

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#756]
some environments don't have CA signed certificates and then ```make configure-nexus``` fails,
I saw that we have an ```--insecure``` parameter on the configure.sh for nexus but we don't have a way to inject it from makefile, it will be nice if we have the option

**Comment by michaelsauter** [comment]
Hmm - what environments are that?

Nexus is exposed on a route using a domain that will be used for any application running on OpenShift. If you do not trust the CA signing the certs for that, you will always get errors e.g. when browsing any app deployed on OpenShift.

Why aren't you trusting the CA? Not sure if setting `--insecure` is a good option for this case.

**Comment by segator** [comment]
I think should be fine to set the insecure for the configure or at least allow a way to put this parameter on the make 

for exemple as my machine is windows  i need to run on cygwin or WSL and there the CA are not installed by default.

**Comment by clemensutschig** [comment]
The tests do similar... or we should provide a script that sucks down the ca and installs it... i vouch for --insecure
