### ISSUE TITLE
enable git lfs in jenkins pipeline

### ISSUE THREAD

**Issue by m-apsolon** [opendevstack/ods-core#76]

**Comment by michaelsauter** [comment]
Cool! Before we start to work on it, can one of you (@m-apsolon, @gerardcl) write a short but detailed paragraph about a) what work is required in ODS to enable this and b) what each user will have to do to use git-lfs.

**Comment by gerardcl** [comment]
- to enable it in ODS: 

  - your bitbucket needs to be enabled with GIT LFS (by default)
  - your repository needs to be enabled with GIT LFS (not by default, only a checkbox selection in the repo config site is required)
  - jenkins slave needs to come with GIT LFS plugin installed

- using git lfs as a developer in ODS:
  - the developer enables the repo with GIT LFS support (by previously assuring it is properly setup in the bitbucket installation..)
  - the developer installs in his local machine GIT LFS (see the getting started: https://git-lfs.github.com/ )
  - the developer tracks any large file he wants in GIT LFS and then it is already transparently being handled everywhere

**Comment by michaelsauter** [comment]
@gerardcl Thanks! Sounds very straight-forward. I guess we can continue by installing git-lfs in the slave-base then, according to the description at https://git-lfs.github.com.

**Comment by gerardcl** [comment]
right! I will align with @m-apsolon on proceeding 
to which project does this issue go?

**Comment by michaelsauter** [comment]
It's correct here in `ods-core`, because you will need to modify only the Jenkins slave base image, which is located in this repo.

**Comment by gerardcl** [comment]
nono, I mean to which "release project" in github

**Comment by michaelsauter** [comment]
Ah! Added it to 1.1.0, since this is a feature, and seems easy enough to implement for 1.1.

**Comment by gerardcl** [comment]
ok, after some research, not only the git lfs extension is required in the slaves, we also need to enhance the jenkins-shared-library at slave node level. will come with a proposal on that soonish!
