### ISSUE TITLE
make test not using cd_user instead openshift:openshift make test fails

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#766]
make test is not using cd_user variable in ods-core.env to fire the prov-app login tests.
We see we need to create a file ```prov-app-config.txt``` on ```tests/scripts``` with the credentials in the format of 

```BASIC_AUTH_CREDENTIAL="${BASIC_AUTH_CREDENTIAL:=openshift:openshift}"```

in case this is intended should be documented in the readme.md of tests folder, if not the behaviour should be changed,
I prefer to put another parameter on ods-core.env to use it for this specific case.

**Comment by michaelsauter** [comment]
@clemensutschig Not sure what we ended up with which user should be used to run the test.

I'm not too keen to put a test user in ods-core.env, I believe that file should be for the installation only.

**Comment by clemensutschig** [comment]
Its Documented how to do it... https://github.com/opendevstack/ods-core/tree/master/tests#running-the-core-tests
