### ISSUE TITLE
Adjust versioning slightly

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#773]
The current versioning scheme is documented at https://www.opendevstack.org/ods-documentation/opendevstack/3.x/getting-started/index.html#_versioning.

I want to propose the following adjustments:

* We notice that there is a need for more frequent "feature releases" which are backwards compatible. People typically talk about them as "3.1", "3.2" etc. However, there is also a need to do bugfix releases, and they should be distinguishable from a "feature release". Therefore we should document that Git tags have 3 digits: MAJOR.MINOR.PATCH, and that patch releases are possible. Note that we already tagged ODS 3 with 3 digits - `v3.0.0`.

* Currently users install ODS most likely with `ODS_GIT_REF=3.x`, which means they point the installation against a branch, and not a tag. This is required because the value of `ODS_GIT_REF` is used when the `Jenkinsfile.template` of a quickstarter is rendered (as the pointer to the Jenkins shared library), and we don't want to require users to update their Jenkinsfiles every time there is a compatible (patch) release. However, it would be better (e.g. for documentation purposes) if installations are based on a tag, to make it crystal clear which sources are used. Therefore, I propose change one small detail: to use the value of `ODS_IMAGE_TAG` instead of `ODS_GIT_REF` when rendering the Jenkins shared library reference  `Jenkinsfile.template`. We then need to ensure during installation that the value of `ODS_IMAGE_TAG` exists as a Git reference in `ods-jenkins-shared-library`, and that it points to the same Git commit as the Git reference specified in `ODS_GIT_REF`.

We could also think about renaming `ODS_IMAGE_TAG` to `ODS_VERSION` so that it isn't confusing when that value is used for the Jenkins shared lib ref. But honestly not sure if this minor detail is worth the effort. One technical note which is also relevant for this decision: during testing of quickstarters, it has proven beneficial to be able to specify the Jenkins shared library and agent image tags separately, so I would still have different input variables. E.g. `env.AGENT_IMAGE_TAG` and `env.JENKINS_SHARED_LIBRARY_REF`, and just fill them, if not set, with `env.ODS_IMAGE_TAG`

@metmajer @clemensutschig @martsec @oalyman @henrjk @stitakis @gerardcl Would be good to hear your thoughts on this. I don't see other exceptions than the one "jenkins shared library reference". Maybe you do see one? Or you have alternative suggestions / ideas?

I would propose to make this change for ODS 4, making it the first version wich can and should be installed from a Git tag.

**Comment by gerardcl** [comment]
I see two points here: 
1- the need to make PATCH level releases transparent to the user
2- the need to make as simple as possible the release process

I still think we do not need tags at all if we want to be transparent and simple. Because by doing this we can even let the companies decide when to cut a MINOR release and also get specific MINOR.PATCH releases by them selfs, so to manage it internally, and maybe via tags.

**Comment by michaelsauter** [comment]
@gerardcl  I am not proposing to make patch level releases transparent for users. I don't want users to know about patch releases. I want to make them transparent for admins - to satisfy documentation needs. Moreover I think we do well to avoid any work for companies to manage release themselves. I believe we should strive for vanilla installs as much as possible. Anything else just gets complicated.

**Comment by gerardcl** [comment]
Ok! then, from what you mention:
-  `ODS_IMAGE_TAG`/`AGENT_IMAGE_TAG`/`ODS_VERSION` -> would relate to specific tag v$MAJOR.$MINOR.$PATCH 
- `JENKINS_SHARED_LIBRARY_REF` -> would relate to specific branch $MAJOR.$MINOR

Which means we should have branches defined with specific $MAJOR.$MINOR values (no more $MAJOR.x) and for the sake of being clear I would have as less references to versions within config params as possible, so to try to only have `ODS_IMAGE_TAG`/`AGENT_IMAGE_TAG`/`ODS_VERSION` and `JENKINS_SHARED_LIBRARY_REF`.

Better?

**Comment by michaelsauter** [comment]
@gerardcl No, I meant it completely different:

* `ODS_GIT_REF` -> Git tag `v$MAJOR.$MINOR.$PATCH`
* `ODS_IMAGE_TAG ` -> value `$MAJOR.x`

`ODS_IMAGE_TAG` is used to tag the images, and - this is the only change - it is also used to reference the shared library.

`ODS_GIT_REF` is basically just used in the `ref` field of a `BuildConfig`.

Branches such as `2.x`, `3.x` will continue to exist on GitHub. They will be used to develop minor, backwards-compatible features. 

And there are only two config params, just as it is today.

**Comment by henrjk** [comment]
@michaelsauter thank you for the write up. I have some questions to clarify my understanding.

Are we planning or aiming to enable developing patches/minor-features for past ODS releases, for example a minor feature could be added to ODS 3 and ODS 4? 

Do you mean with transparent releases an implicit update as described in the [docs](https://www.opendevstack.org/ods-documentation/opendevstack/3.x/getting-started/index.html#_versioning)? Do we need to look into cluster load issues caused by these? 

It seems desirable for a project to decide to only get implicit patch updates but not minor compatible feature updates. I believe this would require routinely creating and maintaining a `$MAJOR.$MINOR.x` branch.   

If we developed a patch for ODS3 and merged it into branch 3.x would this effectively release it?    

On a release all ods projects get a new tag on github of format `v$MAJOR.$MINOR.$PATCH` and trailing `0` are not dropped. I would assume that this would constitute the release, but how would one ignore newer commits on the `$MAJOR.x` branches to avoid prematurely adopting changes before the release tagging occurred?

**Comment by michaelsauter** [comment]
> Are we planning or aiming to enable developing patches/minor-features for past ODS releases, for example a minor feature could be added to ODS 3 and ODS 4?

There are plans for an ODS 3.1. EDP has expressed the desire to release (backwards compatible features) more often than half yearly. We need to strike a balance between "frequent releases" and "not too much upgrade work for users". My suggestion is to have at most two major releases in one year (potentially even less?) and more frequent minor releases.

> Do you mean with transparent releases an implicit update as described in the docs? Do we need to look into cluster load issues caused by these?

Update of the shared lib and the Jenkins agent images would be implicit for users: as soon as the cluster admin updates those versions, users will consume them. The Jenkins master image and the webhook proxy image cannot be updated implicitly without incurring server load. Cluster admins could make use of https://github.com/opendevstack/oc-batch-rollout to rollout explicitly in batches (then it would appear to be an implicit update from a user perspective).

> It seems desirable for a project to decide to only get implicit patch updates but not minor compatible feature updates. I believe this would require routinely creating and maintaining a $MAJOR.$MINOR.x branch.

I understand that a project might want this. However, they would incur more work for them, having to update their Jenkinsfiles more often. To offer this, we would need to tag images with multiple tags, e.g. `3.x` and `3.0.x`, `3.1.x` and so on ... I would say this would be an additional "feature" we can implement but I would see this as a separate topic.

> If we developed a patch for ODS3 and merged it into branch 3.x would this effectively release it?

No. The installations would point to Git tags, such as `v3.0.0`. So unless cluster admins change this, no update will happen. Maybe it is confusing that there is a branch `3.x` on GitHub, but that is not necessarily the content of the `3.x` image tag. Maybe we can use different naming? Maybe `release/v3.x` and `release/v3.1.x` etc?

> On a release all ods projects get a new tag on github of format v$MAJOR.$MINOR.$PATCH and trailing 0 are not dropped. I would assume that this would constitute the release, but how would one ignore newer commits on the $MAJOR.x branches to avoid prematurely adopting changes before the release tagging occurred?

As above, in my proposal admins consume Git tags, not branches. This is exactly the point of my proposal - right now admins consume the branches, and therefore what they get depends on the time on install, not on what is officially released as a Git tag.

**Comment by henrjk** [comment]
Thank you for your quick detailed response.

> There are plans for an ODS 3.1. EDP has expressed the desire to release (backwards compatible features) more often than half yearly. We need to strike a balance between "frequent releases" and "not too much upgrade work for users". My suggestion is to have at most two major releases in one year (potentially even less?) and more frequent minor releases.
> 
Releasing more often reduces risks as the amount of changes decreases. 
With the better coverage of automated testing introduced in ODS 3 the releases process should more on more become a routine task. On the other hand I am sure we are not at a point yet where we could do monthly releases for example.  How frequently should minor releases happen?

> > It seems desirable for a project to decide to only get implicit patch updates but not minor compatible feature updates. I believe this would require routinely creating and maintaining a $MAJOR.$MINOR.x branch.
> 
> I understand that a project might want this. However, they would incur more work for them, having to update their Jenkinsfiles more often. To offer this, we would need to tag images with multiple tags, e.g. `3.x` and `3.0.x`, `3.1.x` and so on ... I would say this would be an additional "feature" we can implement but I would see this as a separate topic.

Let's limit the scope of this item then to not offer this unless actually requested/needed in a separate topic. 

> 
> > If we developed a patch for ODS3 and merged it into branch 3.x would this effectively release it?
> 
> No. The installations would point to Git tags, such as `v3.0.0`. So unless cluster admins change this, no update will happen. Maybe it is confusing that there is a branch `3.x` on GitHub, but that is not necessarily the content of the `3.x` image tag. Maybe we can use different naming? Maybe `release/v3.x` and `release/v3.1.x` etc?
> 
Your comment helped clarify things for me. So unless others feel confused, I'd say no need to rename. 

> > On a release all ods projects get a new tag on github of format v$MAJOR.$MINOR.$PATCH and trailing 0 are not dropped. I would assume that this would constitute the release, but how would one ignore newer commits on the $MAJOR.x branches to avoid prematurely adopting changes before the release tagging occurred?
> 
> As above, in my proposal admins consume Git tags, not branches. This is exactly the point of my proposal - right now admins consume the branches, and therefore what they get depends on the time on install, not on what is officially released as a Git tag.

Ahaa, now this makes perfect sense to me. I agree that depending on time of install should be avoided.

**Comment by michaelsauter** [comment]
> How frequently should minor releases happen?

I am not sure to be honest, and I'm also not certain there is huge value in releasing that often for a platform tool like ODS. For now I am just concerned with adjusting the versioning scheme to be a better fit to have more releases that are backwards compatible. Maybe we have 3-4 backwards compatible (minor) releases followed by a major release. The minor releases could still be 3-4 months from each other.

Regarding the image tag naming: We could also switch from a `3.x`/`3.1.x` scheme to have just the numbers, say `3`, `3.1`, `3.1.0`. `3` would always point to the latest "3 something" release, and `3.1` would always point to the latest "3.1 something" release. This is a very common way to tag images on Docker Hub...  by dropping the `x` we don't confuse it with the branches.

**Comment by henrjk** [comment]
I like the idea of aligning the image tag naming scheme with Docker Hub practices.

**Comment by martsec** [comment]
> My suggestion is to have at most two major releases in one year (potentially even less?) and more frequent minor releases.

I would go towards minimizing major releases, since they are an opportunity to include breaking changes, and it's something we should try to avoid in my opinion, thinking about the stability we need to build things around it. 

In minor releases, we can include new quickstarters for example, backwards compatibility updates to the shared-lib, to sonarqube/nexus version or support for OCP 3 and 4. 

Major releases for me would include for example, changing the CI tool.

**Comment by michaelsauter** [comment]
As an update: I think I'd prefer to stick with `3.x`, `4.x` and so on:

* It keeps the current versioning scheme, so is less confusing for current users
* The `x` highlights that this is a "moving target"

For 4.0, my suggestion is therefore pretty much what I had originally in mind. Let's go baby steps. Here's the proposal again, summarised:

* `ODS_GIT_REF` should point to a tag, e.g. `v3.0.0`. Note though that this is only suggested - one can still use branches such as `master`.
* `ODS_IMAGE_TAG` should be something like `3.x`, `4.x.  Note though that this is only suggested - any value can be used.
* The only implementation change is that `ODS_IMAGE_TAG` will also be used as the Jenkins shared library reference. For that, we'll need a new `make` target which creates a Git ref in that repo with the name of `ODS_IMAGE_TAG` (pointing to the same commit referenced by `ODS_GIT_REF`). Further, the "sync repos" script needs to be adjusted to be able to handle tags.

**Comment by stitakis** [comment]
@metmajer @michaelsauter did you have the chance to align on this?

**Comment by michaelsauter** [comment]
This has been implemented.
