### ISSUE TITLE
add new project templates in prov-app via ods-core.env

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#778]
ods-core.env should support a way to automatically add new project types on prov-app application.properties cm

example
```
#Jira EDP Project template
jira.project.template.key.EDP-project-template=org.opendevstack.jira.plugins.projecttemplate:org-opendevstack-jira-platform-project-template
jira.project.template.type.EDP-project-template=software
```
as we need to make this change by hand on the configmap meaning the ods test fails in the step ```TestVerifyOdsNamespaceProvAppOcpConfig```

**Comment by stitakis** [comment]
@segator what do you think as workaround? Should we go for it?

**Comment by segator** [comment]
Better than nothing but we still need to update cm
Yml, and ods3 already released.

**Comment by stitakis** [comment]
ok, I'll add this in ODS 3.1

**Comment by stitakis** [comment]
@borja44 @martsec this change is needed to avoid manual configuration of prov-app config map when releasing ODS

**Comment by clemensutschig** [comment]
I am really confused,.. why do you not just do the change in your 3.x branch installation, then tailor will not diff ... ?!
