### ISSUE TITLE
add SSH Pipeline Steps plugin to Jenkins Master

### ISSUE THREAD

**Issue by alanbort** [opendevstack/ods-core#779]
**Is your feature request related to a problem? Please describe.**
Attempting to use this: https://www.jenkins.io/doc/pipeline/steps/ssh-steps/ returns errors about missing definitions.

**Describe the solution you'd like**
The SSH Pipeline Steps plugin should be available in the Jenkins Master in the <project>-cd namespace.

**Describe alternatives you've considered**
There is no sane alternative to manage ssh operations. Simple shell steps are insufficient and would require handling interactive input requests from regular ssh tools.

**Additional context**
I am assuming it is still not possible to do this at the project level. I haven't found a way to persist plugins through instance restarts.

**Comment by michaelsauter** [comment]
Hmm, that is odd - plugins should persist when the instance restarts. Plugins are stored in a location that is on the PVC. Did you try to install it and then the plugin went away? I would consider this a bug then.

**Comment by alanbort** [comment]
Indeed. I have tested in an isolated project and it is persistent. I apologize for bringing this here as it would seem it is an internal process issue rather than a technical limitation. Thank you very much for the quick answer :)
