### ISSUE TITLE
Document that ods-core.env is needs to be in LF, not CRLF

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#785]
we should add in the documentation that in case work in windows(WSL) ensure file is in LF!! Otherwise ODS Installation and ODS Tests fail.

**Comment by felipecruz91** [comment]
After checking the docs it seems to be mentioned in the [repo](https://github.com/opendevstack/ods-core/blob/3.x/docs/modules/administration/pages/installation.adoc#configuration), and therefore in the [public documentation](https://www.opendevstack.org/ods-documentation/opendevstack/3.x/administration/installation.html#_configuration)

If you think this should be mentioned somewhere else in the documentation, I'd be happy to contribute to it.

**Comment by michaelsauter** [comment]
I think this can be closed, @segator added it in a PR to the docs but this issue was not closed.
