### ISSUE TITLE
create-projects tests are not executed if verify fails

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#790]
I ran `make test` and expected it to run `create-projects` tests, but did not realise that if the `verify` prerequisite fails, the tests do not run. I'm not sure that `verify` is actually a technical requirement for the tests. If it is not, it would be good to still run the tests. If it is, it would be nice to tell the user that the tests did not run when `verfify` fails.

FYI @clemensutschig @georgfedermann 

@henrjk Do you have input on this?

**Comment by clemensutschig** [comment]
@michaelsauter  - one would expect if verify does not work - that create projects will fail anyway .. that was the reason

**Comment by michaelsauter** [comment]
@clemensutschig cool, then I'll just add a comment to make this clear. I missed it, but makes a lot of sense.
