### ISSUE TITLE
Make test dependencies explicit, and remove duplicated tests

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#792]
The recent refactoring of the quickstarter tests, and issues like #790 got me thinking about our tests. First, here's what we have right now as I understand it:

1. "Verify tests". These check that an actual ODS installation is as it should be.
2. "Create project tests". These (re)create `unitt-*` projects, in 3 different ways: once just the projects through shell scripts, once projects with Jenkins through shell scripts, and once projects with Jenkins through the webhook proxy. The last test actually depends on the verify tests as the webhook proxy must exist. Originally, this test package was designed to be run in a naked, local OpenShift cluster (@hugowschneider correct me if I'm wrong?).
3. "Quickstarter tests". These are executed in the `unitt-*` projects (from point 2 above - the project does not cleaned up after the tests so still exists for the quickstarter tests), and execute quickstarters through the webhook proxy in the `unitt-cd` project. They also depend on point 1 above as they require e.g. a working SonarQube.

A couple of things that I observed:

* The tests in (2) are to a large extend redundant. There is just one additional check on top of what (1) already provides, which could easily be moved to (1): `CheckProjectSetup` in `create-projects_test.go`. The only difference I see is that the first two tests in (2) in theory work without an actual ODS installation. I think I would propose to only run one test, which works without ODS installation, and kill the other two.
* Right now there is an implicit dependency of the quickstarter tests on both (1) and (2) - it is only noted in the readme. I think it would be good to have some kind of explicit prerequisite, e.g. create `unitt-*` projects if they don't exist, and check if they are configured correctly ... here we can just use the code already there in (1).
* The only thing in (1) which is not required for the quickstarters is the provisioning app check (the odsverify project). Maybe it would be good to not execute the prov app check if we only want to run quickstarter tests to save time.

So all up, my current thinking is:

* Kill webhook proxy and project-only tests from `create-projects`
* Move shell-script approach to (re)create `unitt-*` projects and check config of it to a prerequisite of the quickstarter test
* Move prov app verification into it's own target

With this in mind, the new targets would look sth. like this:
```
verify: verify-ods-namespace verify-provisioning-app

verify-ods-namespace:
  # what we have currently in verify, minus prov app

verify-provisioning-app:
  # prov app

prepare-quickstarter-test:
  # unitt project creation if it does not exist, plus config check (one test from the current create-projects tests)

test-quickstarter: verify-ods-namespace prepare-quickstarter-test
  # quickstarter tests as is right now
```

I'm not entirely sure yet if this is the right thing to do, but I wanted to write down my thoughts.

@henrjk @hugowschneider @clemensutschig @georgfedermann @segator What are your thoughts?

**Comment by segator** [comment]
It make sense @michaelsauter 
I have only a comment: When creating the quickstarters are using always same name or is generated based in random asset?
we should ensure even if the test fails we are safe to rerun again them, something that right now is not possible for example with odsverify project even we have the cleanup parameter to true, cleanup can also fails.

**Comment by henrjk** [comment]
What you are saying makes sense to me. 

The name verify meant to me that the tests would not do any changes in the cluster. With this in mind, perhaps:

```
verify: verify-ods-namespace

verify-ods-namespace:
  # what we have currently in verify, minus prov app

test-provisioning-app: verify-ods-namespace 
  # prov app test

prepare-quickstarter-test:
  # unitt project creation if it does not exist, plus config check (one test from the current create-projects tests)

test-quickstarter: verify-ods-namespace prepare-quickstarter-test
  # quickstarter tests as is right now
```

**Comment by michaelsauter** [comment]
@henrjk Agree, I find the word "verification" weird for something that does tests. However, I guess one could argue that this "test" actually verifies if the whole config is such that the provisioning app can really provision projects and components. So in the end it is a "verification step". That said, I still like your names because they make a clear distinction between "verify = just checks" and "test = making actual changes in the cluster".
