### ISSUE TITLE
Dump Jenkins log in case of quickstarter test failure

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#796]
Would be nice to get the Jenkins logs. Otherwise it is not clear what went wrong, and one has to run the test again.

This is a follow-up from #795.

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-core/blob/master/tests/scripts/print-jenkins-log.sh provides that script ...

https://github.com/opendevstack/ods-core/blob/65f621cdaf0354c534958d7d608bfa4570f2ca3e/tests/utils/jenkins.go#L134-L148

:D

**Comment by michaelsauter** [comment]
Closing this as to me it looks like the logs are actually printed, regardless of whether the pipeline succeeded or not. Either this has changed since this issue, or it was always like this and we didn't get the logs for other reasons.
