### ISSUE TITLE
make configure-sonarqube fails when using special characters

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#798]
when you use special characters in your password  for example & the target is not skipping the password and make the script fails.

**Comment by michaelsauter** [comment]
Where exactly does it fail? Can you please link to the place in the script that is broken?

**Comment by felipecruz91** [comment]
Hi @michaelsauter,

It happens when it tries to read a base64 password that is set in the `ods-core.env` file.

The place in the script is here: https://github.com/opendevstack/ods-core/blob/8ca79d5fc37897a8e4b978cf2a1d77ac05a77430/nexus/configure.sh#L110

**Comment by segator** [comment]
My fault.. the issue was in configure-sonarqube
https://github.com/opendevstack/ods-core/blob/master/sonarqube/configure.sh#L152
here as the password is sent in plain text if your password have & then you have a problem
