### ISSUE TITLE
mono quickstarter is not provisioned thru prov app on 3.0.0

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#800]
ods-quickstarter folder be-fe-mono-repo-plain but in cm.yml is fe-be-mono-repo-plain so create new quickstarter fail as jenkinsfile not exist on this path. Typo on the pat fe-be... instead be-fe

https://github.com/opendevstack/ods-core/blob/3.x/ods-provisioning-app/ocp-config/cm.yml#L327-L328

how is this possible? someone tested this before the release?

**Comment by clemensutschig** [comment]
@michaelsauter  - this is an interesting case - which is just not covered by the automated tests - we should do a quick automated check if CM matches ods-quickstarters´...

**Comment by clemensutschig** [comment]
@michaelsauter as the test framework already expects a deployed ods ... we could easily verify that there is corresponding entry in the config map?! ...

**Comment by michaelsauter** [comment]
@clemensutschig Sounds good, at least we can check if the referenced folder exists and has a Jenkinsfile in it.
