### ISSUE TITLE
Local installation - "make prepare-bitbucket-repos" hangs forever

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-core#812]
Hi,

First of all, I'd like to congratulate you all on your tremendous effort with ODS, especially with the 3.x release 👏👏 Keep up the great work!

Secondly, I'm highly interested in carrying out an ODS 3.x local installation so I am following this [guide](https://www.opendevstack.org/ods-documentation/opendevstack/3.x/administration/installation.html).

In order to meet the server prerequisites, I have provisioned a brand-new VM in Google Cloud Platform with enough resources (Centos 8, 4 vCPUs, 16 GB).

### OpenShift Cluster info

```
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0
```

### ODS Environment configuration (Bitbucket only)

```
$ cat ods-core.env | grep -i bitbucket
# Bitbucket project name
ODS_BITBUCKET_PROJECT=opendevstack
# Bitbucket / Git #
# Bitbucket host (without protocol!)
BITBUCKET_HOST=192.168.56.31:7990
# Bitbucket URL (including protocol!)
BITBUCKET_URL=http://192.168.56.31:7990
# Typically ends in "/scm" for Bitbucket.
# Technical user ("cd_user") to authenticate against Bitbucket.
PROV_APP_CROWD_USER_GROUP=bitbucket-users
PROV_APP_CROWD_ADMIN_GROUP=bitbucket-administrators
# Comma-separated list of events for which Bitbucket sends a request to the webhook proxy service
```

When running the `make prepare-bitbucket-repos` command, the script asks for some information and after typing the password and pressing `Enter`, the script execution hangs forever and it never ends.

![image](https://user-images.githubusercontent.com/15997951/93260004-04c47280-f7a1-11ea-8c51-aecbb179fb3c.png)

My understanding is that, the `make prepare-bitbucket-repos` command, will spin up a new Bitbucket server in my localhost, so, I have even tried setting `BITBUCKET_HOST` and `BITBUCKET_URL` to `127.0.0.1` in the `ods-core.env` file but, it did not work either.

If my assumption is not correct, I guess I will need to have a Bitbucket server installation in my localhost before starting with the ODS 3.x installation.

Any guidance here would be very much appreciated 😊

**Comment by michaelsauter** [comment]
Thanks ❤️ 

`prepare-bitbucket-repos` expects a running Atlassian suite. It will then create the `OPENDEVSTACK` project and the repos inside. It won't spin up a Bitbucket instance. You'll need to setup Bitbucket prior to running this. You can make use of either the Ansible stuff in `infrastructure-setup` (however beware that this hasn't been updated in a while and might be buggy) or take inspiration from the `ods-devenv` setup, which uses containers to run Bitbucket.

In general, maybe getting a `ods-devenv` based box might be the best way to get a working local env? FYI @georgfedermann

**Comment by felipecruz91** [comment]
Thanks, @michaelsauter. I thought it would be beneficial to have such a useful information in the docs so, I've created a PR with it here: https://github.com/opendevstack/ods-core/pull/813
