### ISSUE TITLE
Remove dockerImageRepository from Jenkins image streams

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#815]
That field is not needed in the Jenkins image streams (defined in https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/build/is.yml).

It enables a "pull through" to repositories on the Docker Hub, which we neither need nor want. We already removed that field in other `ImageStream` definitions.

**Comment by clemensutschig** [comment]
@michaelsauter  - we should close this, it's done, or?
