### ISSUE TITLE
Parameterization of CPU req/limits in OpenShift templates

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-core#817]
**Is your feature request related to a problem? Please describe.**
When carrying out a new ODS installation, we may find the necessity to configure how much CPU and memory request/limits we want to establish for Sonar, Nexus, Prov app and Jenkins. As of version 3.x, those values seem to be hard-coded in the Tailor Template yml files and cannot be overriden.

**Describe the solution you'd like**
An option could be to extend the Tailor .yml files so that it reads the parameters from variables that could be set in the `ods-core.env` file, for instance. If no variable has been found in `ods-core.env` or other `.env` file, Tailor will use the hard-coded values in its Template yml file.

**Example**
For instance, if I wanted to increase the Nexus memory limit constraint (which is currently [hard-coded](https://github.com/opendevstack/ods-core/blob/master/nexus/ocp-config/bc.yml#L21) to 2Gi), I could define that variable in `ods-core.env` and extend the [bc.yml](https://github.com/opendevstack/ods-core/blob/master/nexus/ocp-config/bc.yml) file to handle this scenario.

Any input would be very much appreciated, thanks 👍

**Comment by michaelsauter** [comment]
The templates are already parameterised: https://github.com/opendevstack/ods-core/blob/master/nexus/ocp-config/bc.yml#L14-L21.

What you see there are just default values.

If you set one of those parameters in your `ods-core.env` file, they'll get used :)

So maybe this just needs to be documented?

**Comment by felipecruz91** [comment]
That's really great news then!

If you could point me to the right section where you'd like this to be documented, I'd be happy to do it.

**Comment by michaelsauter** [comment]
Not sure. Maybe as comments in `ods-core.env` that point to the templates for more customisation? Where would you have searched for / found this information?

**Comment by felipecruz91** [comment]
Yes, `ods-core.env` is a good starting point to document it.

**Comment by michaelsauter** [comment]
I think this is done, right? I'll close the issue. If there are still some params missing, please open a new issue for them.
