### ISSUE TITLE
SonarQube edition and distribution URL alignment

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-core#819]
**Is your feature request related to a problem? Please describe.**
When installing ODS 3.x, there are a few parameters in the `ods-core.env` file that need to be configured for SonarQube.
`SONAR_EDITION` and `SONAR_DISTRIBUTION_URL` must be aligned, otherwise you could end up in an scenario where SonarQube Community Edition is installed (because the distribution URL points to a non-commercial .zip file) despite having set the `SONAR_EDITION` to enterprise.

**Describe the solution you'd like**
A simple comment in the `ods-core.env` file would help to highlight the importance of such alignment, if `SONAR_EDITION` is set to `enterprise`, then make sure you point to the Commercial Distribution URL in `SONAR_DISTRIBUTION_URL`

**Describe alternatives you've considered**
See below an example of how the `ods-core.env` could look like after adding the information aforementioned:

```env
# SonarQube edition
# See https://www.sonarsource.com/plans-and-pricing/.
# - Use "community" for free edition
# - Use "developer", "enterprise" or "datacenter" for commercial editions
SONAR_EDITION=enterprise
# SonarQube version.
# Officially supported are:
# - 7.9 (LTS release)
# - 8.2.0.32929 (latest tested release)
SONAR_VERSION=8.2.0.32929
# SonarQube distribution URL.
# Must be aligned with both SONAR_VERSION and SONAR_EDITION.
# Check https://binaries.sonarsource.com/ for options.
# If using the enterprise edition, use the CommercialDistribution path as below:
SONAR_DISTRIBUTION_URL=https://binaries.sonarsource.com/CommercialDistribution/sonarqube-enterprise/sonarqube-enterprise-8.2.0.32929.zip
# If using the community edition, use the Distribution path as below:
# SONAR_DISTRIBUTION_URL=https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.2.0.32929.zip
```

**Comment by michaelsauter** [comment]
Good point. Maybe adding the line `# Must be aligned with both SONAR_VERSION and SONAR_EDITION.` is enough?
