### ISSUE TITLE
Deploy phase of Release Manager fails in case of component type 'ods-service' (missing tailor binary)

### ISSUE THREAD

**Issue by FLIGHTLAMA** [opendevstack/ods-core#841]
**Describe the bug**
After successfully building components in the deploy step
The pipeline breaks with the following error (on every component)

```
+ tailor --verbose -n adam-dev export -l app=adam-adam-app
script.sh: line 1: tailor: command not found
```
installing tailor manually in the jenkins master container solved this problem

**To Reproduce**
1. Deployment stage of every component with the release manager

**Expected behavior**
Tailor should be available in the jenkins master container

**Affected version (please complete the following information):**
 - OpenShift: v3.11.219
 - OpenDevStack: 3.x

**Comment by FLIGHTLAMA** [comment]
id: adam
name: Project adam
description: Description of adam.

services:
  bitbucket:
    credentials:
      id: adam-cd-cd-user-with-password

# Uncomment (below) to connect to jira
#  jira:
#    credentials:
#      id: adam-cd-cd-user-with-password
  nexus:
    repository:
      name: leva-documentation

repositories:
  - id: gateway
    branch: master
    type: ods-service
  - id: redis-service
    branch: master
    type: ods-service 
  - id: integration-service
    branch: master
    type: ods-service
  - id: jchem-io
    branch: master
    type: ods-service
  - id: landing-page
    branch: master
    type: ods-service
  - id: marvinjs
    branch: master
    type: ods-service
  - id: adam-app
    branch: dev
    type: ods-service

**Comment by clemensutschig** [comment]
ok - this confirmed my suspicion .. 

we have to add a test for this ..
https://github.com/opendevstack/ods-quickstarters/blob/master/be-gateway-nginx/files/metadata.yml 

maybe to release manager tests ... .
