### ISSUE TITLE
Add R language SonarQube plugin

### ISSUE THREAD

**Issue by stevegbrooks** [opendevstack/ods-core#844]
Merck has developed a plugin for SonarQube for scanning R code. It would be helpful to integrate this plugin for use by R developers.

https://github.com/Merck/sonar-r-plugin

**Comment by michaelsauter** [comment]
Cool. Do you want to open a PR for it? See for example https://github.com/opendevstack/ods-core/pull/653.

**Comment by stevegbrooks** [comment]
sure I can work on it - thanks

**Comment by stevegbrooks** [comment]
@michaelsauter i tried to create a branch and push it, but seems i dont have permission to do that. How do I submit a PR then?

**Comment by michaelsauter** [comment]
You need to fork the repo under your user. For more info, see https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.

**Comment by stevegbrooks** [comment]
started PR
