### ISSUE TITLE
openshift pipeline build status steps don't get updates from jenkins piepline 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#86]
Logs from jenkins master:

Terminated Kubernetes instance for agent tost-cd/jenkins-slave-vm5x7-65pk8
  | Disconnected computer jenkins-slave-vm5x7-65pk8
  | Mar 06, 2019 7:25:59 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
  | INFO: Terminated Kubernetes instance for agent tost-cd/jenkins-slave-vm5x7-65pk8
  | Mar 06, 2019 7:25:59 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
  | INFO: Disconnected computer jenkins-slave-vm5x7-65pk8
  | Mar 06, 2019 7:25:59 AM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
  | INFO: tost-cd/tost-cd-be-docker-plain-test-master #10 completed: SUCCESS
  | Mar 06, 2019 7:25:59 AM hudson.model.listeners.RunListener report
  | WARNING: RunListener failed
  | java.lang.NullPointerException
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.upsertBuild(BuildSyncRunListener.java:336)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:226)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.onFinalized(BuildSyncRunListener.java:193)
  | at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:257)
  | at hudson.model.Run.onEndBuilding(Run.java:1998)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:611)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$900(WorkflowRun.java:132)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:993)
  | at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1440)
  | at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:417)
  | at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)
  | at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
  | at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
  | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)

see below:
![image](https://user-images.githubusercontent.com/40628552/53863466-91a64180-3fea-11e9-8fab-01d110b7656a.png)

https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L336 
nodes == null :(

**Comment by clemensutschig** [comment]
[openshift-sync-jar-fix.zip](https://github.com/opendevstack/ods-core/files/2935722/openshift-sync-jar-fix.zip)

extract and rsync replace `openshift-sync.jar` in `/var/lib/jenkins/plugins/openshift-sync/WEB-INF/lib`

**Comment by clemensutschig** [comment]
Fixed in openshift Master;-) waiting for release information- where this will show up.

**Comment by michaelsauter** [comment]
Awesome 👍 

FYI @adyachok I think this is the reason for what you should me recently

**Comment by clemensutschig** [comment]
@michaelsauter  - so in chatting with Gabe - the fix goes into OCP 4.0x :( .... 
I suggest we package it with jenkins master... thoughts?

**Comment by michaelsauter** [comment]
@clemensutschig What?! So they broke the sync in 3.11 and are going to leave this as it is? That is crazy.

I personally don't feel that ODS should fix what is broken in OpenShift ... if you feel strongly about it, we can package it with Jenkins, otherwise I would leave as is.

**Comment by maierl** [comment]
Thanks for taking care about this!

**Comment by michaelsauter** [comment]
As we have done some other "bugfixes" in the Jenkins master image, we decided to pull this into 1.1 too - see referenced PR.
