### ISSUE TITLE
Add Keycloak as supported IAM solution

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-core#87]
Most customers do not have Atlassian Crowd. A lot already have keycloak.
Roadmap for Atlassian Crowd is unclear. We therefore should support alternative Identity and Access Management solutions. Keycloak is a very popular one at the moment.

To support Keycloak, we have to support Login to Keycloak from

* Confluence
* Jira
* Bitbucket
* Provisioning App
* Rundeck

**Comment by stitakis** [comment]
@rattermeyer this makes sense to me... happy to help here, specially with the prov-app, I´m currently working to setup a connector to AzureAD for it, so setting up another auth connector shouldn´t be much work... I hope :-)

**Comment by rattermeyer** [comment]
we have this already in place. internal code review is under way. problematic are the atlassian tools, that differ slightly between each version and between each tool. we need to come up with an smart solution for the repo organization. hopefully, I can share the repos next week.

**Comment by stitakis** [comment]
@rattermeyer excellent, did you created a quickstarter or something similiar? Asking because we will be exploring to secure nexus and sonarqube with Keycloak and underlying openshift auth if possible.

**Comment by michaelsauter** [comment]
Can this be closed now?

**Comment by tjaeschke** [comment]
I think so.
