### ISSUE TITLE
CI tests fail for master with error message "Repo 'candidates' is missing"

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#871]
**Describe the bug**
TestVerifyOdsNamespaceNexusFunctions fails during CI tests on master

**Affected version (please complete the following information):**
 - OpenShift: OKD 3.11
 - OpenDevStack master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
    amazon-ebs: === RUN   TestVerifyOdsNamespaceNexusFunctions
    amazon-ebs:     verify-ods-namespace-functional_test.go:31: Execution of nexus test.sh failed at /home/openshift/opendevstack/ods-core/nexus/test.sh:
    amazon-ebs:         StdOut: Skip checking for blobstores. This requires an admin password.
    amazon-ebs:           See help on how to specify the admin-password.
    amazon-ebs:           Alternatively env variable NEXUS_ADMIN_PASSWORD can be set or stored in ods-core.env
    amazon-ebs:         Check for repositories
    amazon-ebs:         Repo 'candidates' is missing
    amazon-ebs:
    amazon-ebs:         StdErr:
    amazon-ebs: --- FAIL: TestVerifyOdsNamespaceNexusFunctions (0.21s)
...
    amazon-ebs: === RUN   TestVerifyOdsNamespaceImages
    amazon-ebs:     resources.go:31: Image tag 'jenkins-agent-nodejs10-angular:latest' not found.
    amazon-ebs: --- FAIL: TestVerifyOdsNamespaceImages (0.03s)
```

**Comment by michaelsauter** [comment]
I noticed that the Nexus version we used in the GitHub Actions test was still set to 3.22.0. I've updated it in #872, and the tests fail: https://github.com/opendevstack/ods-core/pull/872/checks?check_run_id=1372997064.

I'll create a new PR with a working Nexus version, and then a new issue to look into what needs to change for the new Nexus version.
