### ISSUE TITLE
Verification of quickstarter unit test fails

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#886]
`make test-quickstarter` fails on my machine with:

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
```

This happens because of `grep -oP '\K[[:digit:]]*(?= tests)'`, which was introduced in b2c136dfc9e6dabc6242a67d11b982162ade2561. Therefore, only `master` is affected (3.x is fine).

The version of `grep` I'm using is `grep (BSD grep) 2.5.1-FreeBSD`.

@georgfedermann Do you have other ideas how to implement this?

**Comment by michaelsauter** [comment]
@georgfedermann ping

At the moment, I'd rather revert the commit because I can't properly run the test suite locally.

**Comment by georgfedermann** [comment]
@michaelsauter sorry, only saw the issue now. The command is meant for the GNU grep version as available on Linux machines. On my MacBook I have the HomeBrew package ggrep installed and an alias for grep pointing to ggrep.

**Comment by michaelsauter** [comment]
@georgfedermann I see. However, I feel like that is not a good solution. The "feature" is so small that requiring a specific package just for that is too much IMHO. We should try to have as few dependencies as possible so that really anyone can run those tests.

**Comment by georgfedermann** [comment]
ok. On the other hand, this is just an additional package on BSD i.e. if you're using a MacBook, it's the default on Linux system, and also on MacBooks if you have GNU coreutils installed to reduce issues with differences in command line tools between BSD and Linux. The previous approach made use of pup which is also an additional package to be installed for bash html processing.

**Comment by michaelsauter** [comment]
Note that `pup` usage was optional. I also objected to this initially, but was convinced it is OK as it is not required.

I would really like to avoid this specific `grep` usage.

**Comment by georgfedermann** [comment]
ok, if it's ok for you, I'll try to find a fix on the weekend

**Comment by michaelsauter** [comment]
Sure. Maybe I have some time this week to look into it already, then I'll update this issue.

**Comment by michaelsauter** [comment]
I'm taking this on now.
