### ISSUE TITLE
Changelog enforcer

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-core#891]
**Is your feature request related to a problem? Please describe.**
When I was preparing the ODS 3 Release, it was a HUGE pain to write all the changelogs. Not only because of the amount, but also to trace back everything that happened in tickets, sometimes something completely different happened than the title implied. Merged PRs had no issues and vice versa etc. . I came to the conclusion that there is a lot that I am not aware of just because I did not participate in every ticket there was and some information apparently stayed just between the issue participants and was not 100% complete written down (which I see as a normal happening). 

So basically, even though I spent hours trying to trace back stuff in the tickets and PRs, It seems obvious that the release notes will have a higher quality if the committer adds them by himself.

**Describe the solution you'd like**
I'd like to discuss using a changelog enforcer and if the release notes are so important that it justifies the effort. I found this https://github.com/marketplace/actions/changelog-enforcer which also has a skip functionality. 

**Describe alternatives you've considered**
Keep it as it is and let the releaser die the changelog death.

**Additional context**
I openend this issure for ods-core since it is the biggest repo but it is valid for all relevant repos.

Any thoughts @michaelsauter @clemensutschig ?

**Comment by michaelsauter** [comment]
Fully agree that the manual assembly is a pain.

Maybe you can try this action in a repo you own to see how it goes? And then we also have an example to look at to understand if it fits well.

**Comment by renedupont** [comment]
I tested the mentioned [github action in a repo ](https://github.com/renedupont/changelog-enforcer-test/blob/master/.github/workflows/blank.yml) in a repo:
- The check in a pull request will fail if the changelog file was not changed and succeed if it was changed
- Also, skip labels can be configured to skip failing on unchanged changelog files in a PR check
- It lets you configure a changelog file which is checked for changes (CHANGELOG.md by default)

So far that worked pretty well, two things to mention though:
- Since this check runs when a PR has been created, one can't reference this PR in the changelog file prior to that. So we either say only issues should be referenced or the PR reference needs to be commited after the PR was created.
- Even though this check can be skipped by adding the skip label, I'm afraid some contributers will get annoyed it. Would there be any action/communication necessary to avoid that? 


Any thoughts @clemensutschig @metmajer @michaelsauter ? Maybe we could try it in one of the repos and see how it works for us?

**Comment by michaelsauter** [comment]
I'm all in on this 👍 

I thought a little more about it after our discussion yesterday, and having an up-to-date changelog will be really crucial going forward. It will allow us to release patch versions of ODS at any given time easily by just tagging the the repos - without other manual work. This is important because from ODS 4 onwards, administrators are encouraged to install from a Git Tag (such as `v4.0.2`), not a branch (such as `4.x`).

The check already has a pretty clear error message (`Error: No update to CHANGELOG.md found!`), so that is good. However, I wonder if it would be possible to add a comment or a link to a document to explain to the PR author what is expected. E.g. it is not clear that the issue / PR should be linked, that we use [keepachangelog](https://keepachangelog.com/en/1.0.0/) format etc. Do you think we can customise the message in the check to link to some document that explains this?

**Comment by renedupont** [comment]
The error message is hardcoded, see https://github.com/dangoslen/changelog-enforcer/blob/master/src/changelog-enforcer.js#L94
I can open a feature request there or would you rather fork it?

**Comment by stitakis** [comment]
@renedupont @michaelsauter I propose the repo `ods-provisioning-app` if you want to try in a repo... I'm just willing to handle eventually overhead :-)

**Comment by michaelsauter** [comment]
@renedupont Maybe there is a way to add some text in our workflow definition? I could imagine there is a way to configure some text in case of failure, or maybe one can run a step if the previous step failed ...?

**Comment by renedupont** [comment]
@michaelsauter It is possible to execute a step after a failed one like this:
```
    - run: echo "runs on failure"
      if: ${{ failure() }}
```
but for me that is more a workaround. I will use all my non-existing javascript skills and try to open a PR 😄.

**Comment by renedupont** [comment]
_current status:_
- a custom error message option was added to new version of the changelog enforcer
- the latest changelog enforcer version is in use at the ods-provisioning-app, see https://github.com/opendevstack/ods-provisioning-app/blob/master/.github/workflows/changelog-enforcer.yml

**Comment by michaelsauter** [comment]
@renedupont This looks really great. How about enabling on another repo as well to get some more experience with it?

**Comment by renedupont** [comment]
Any suggestions which ones to start with? I'd like to get some more contributors on board so that this does not come as a surprise to many of them.

**Comment by michaelsauter** [comment]
OK then let's start with ods-core. This repo has fewer contributions than quickstarters or jenkins-shared-library.
