### ISSUE TITLE
ODS AMI build failing due to go missing openshift api dependency

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#940]
**Describe the bug**
ODS AMI build failing due to go missing openshift api dependency

**AMI build log file error**
amazon-ebs: go: github.com/openshift/api@v3.9.0+incompatible: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0ESC[0m
ESC[1;31m==> amazon-ebs: make: *** [prep-verify] Error 1ESC[0m
2021/01/10 01:08:26 packer-builder-amazon-ebs plugin: [ERROR] Remote command exited with '2': /tmp/script_8755.sh  --branch 3.x

**Proposed solution**
Apply this change to branch 3.x: https://github.com/opendevstack/ods-core/commit/9c79d7c0265d0d848e585c4a4e74d97e87b40e02

**Comment by stitakis** [comment]
@michaelsauter do you see other needed change than the linked above to solve this issue?

**Comment by michaelsauter** [comment]
@stitakis I think cherry-picking that commit should fix the issue.

**Comment by stitakis** [comment]
I've done it in my local env and run a quick test.
```
stitakis@stitakis-ubuntu:~/dev/github/opendevstack/ods-core/tests$ go get github.com/openshift/api@release-3.9
go: downloading github.com/openshift/api v0.0.0-20180801171038-322a19404e37
```
I'll push and create a PR
