### ISSUE TITLE
narrow down system:authenticated permissions when creating new ODS project

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-core#942]
**Is your feature request related to a problem? Please describe.**
When creating a new project and there are no specific groups defined then `system:authenticated` is used.
In this case, the roles/permissions given to `system:authenticated` (everyone that can login...) are `view` and `edit`.

**Describe the solution you'd like**
To just give `view` role by default.

**Describe alternatives you've considered**
Keep as is.

**Additional context**
This means removing https://github.com/opendevstack/ods-core/blob/1c2df074acc5f418190b1458cf63fead16657a53/create-projects/create-projects.sh#L121-L124

**Comment by michaelsauter** [comment]
As discussed earlier, I am in favour of this change. However, I want to highlight two things:

* This has no impact when the `PROJECT_GROUPS` are given. I think it is good that this "mode" is unaffected.
* It means that for typical teams, each member needs to be added manually with edit/admin permissions to *-dev/*-test/*-cd. This is cumbersome, but I think the "safer" default still makes sense.

I would love to hear more thoughts on this @henrjk @oalyman @stitakis @buegelbeatz.

**Comment by stitakis** [comment]
I think the request makes sense and I don't see any problem with it.

btw... I'd like to point out, that since this change in ProvApp "Add default project groups to project groups on project creation (https://github.com/opendevstack/ods-provisioning-app/pull/636)", project groups can be added per configuration in ProvApp. This feature will be used in corporate environment to automatically give access to a cluster admin group.

**Comment by gerardcl** [comment]
PR provided is ready now :) 

I will wait for more comments though, this is not urgent I believe

**Comment by henrjk** [comment]
This makes sense to me. I guess we could add configurable sets of users if needed later.

**Comment by gerardcl** [comment]
makes sense! agree on following that approach afterwards, @michaelsauter shall I merge or provide a proposal for what @henrjk suggests?

**Comment by gerardcl** [comment]
@henrjk from your comment I think that can already be set/configured at ods-provisioning-app level when creating new projects since one can specifiy users and/or groups for admin
