### ISSUE TITLE
ODS CI branch 3.x is failing due to unknown reason

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#949]
Since last Saturday 6 of February the ODS CI build of branch 3.x failing. 

I can't find any hint in the log file.

There was a change in `ods-jenkins-sharelib` on Friday: https://github.com/opendevstack/ods-jenkins-shared-library/commits/3.x
However I can't see any relation to the log output.

Below as reference the log output in the same place of the broken build and of the last successful build.

**Log Output of broken build**
```
[0;32m    amazon-ebs: --- PASS: TestVerifyOdsQuickstarterProvisionThruProvisionApi (602.85s)ESC[0m
ESC[0;32m    amazon-ebs: PASSESC[0m
ESC[0;32m    amazon-ebs: ok     github.com/opendevstack/ods-quickstarters/tests/release-manager 602.862sESC[0m
ESC[0;32m    amazon-ebs: ?      github.com/opendevstack/ods-quickstarters/tests/utils   [no test files]ESC[0m
ESC[0;32m    amazon-ebs: FAILESC[0m
ESC[1;31m==> amazon-ebs: make: *** [test] Error 1ESC[0m
2021/02/08 03:24:44 packer-builder-amazon-ebs plugin: [ERROR] Remote command exited with '2': /tmp/script_1736.sh  --branch 3.x
```

**Log Output of last successful build at same place**
```
0;32m    amazon-ebs: --- PASS: TestVerifyOdsQuickstarterProvisionThruProvisionApi (602.18s)ESC[0m
ESC[0;32m    amazon-ebs: PASSESC[0m
ESC[0;32m    amazon-ebs: ok     github.com/opendevstack/ods-quickstarters/tests/release-manager 602.196sESC[0m
ESC[0;32m    amazon-ebs: ?      github.com/opendevstack/ods-quickstarters/tests/utils   [no test files]ESC[0m
ESC[0;32m    amazon-ebs: ~/opendevstack/ods-coreESC[0m
ESC[0;32m    amazon-ebs: project.project.openshift.io "unitt-cd" deletedESC[0m
ESC[0;32m    amazon-ebs: project.project.openshift.io "unitt-dev" deletedESC[0m
ESC[0;32m    amazon-ebs: project.project.openshift.io "unitt-test" deletedESC[0m
ESC[0;32m    amazon-ebs: Writing crontab entry: 38 1-22/3 * * * /home/openshift/bin/restart_atlassian_suite.shESC[0m
ESC[0;32m    amazon-ebs: Installation completed.ESC[0m
ESC[0;32m    amazon-ebs: Now start a new terminal session or run:ESC[0m
2021/02/05 03:38:30 packer-builder-amazon-ebs plugin: [INFO] RPC endpoint: Communicator ended with: 0
2021/02/05 03:38:30 [INFO] 79725 bytes written for 'stderr'
2021/02/05 03:38:30 [INFO] 3585358 bytes written for 'stdout'
2021/02/05 03:38:30 [INFO] RPC client: Communicator ended with: 0
2021/02/05 03:38:30 [INFO] RPC endpoint: Communicator ended with: 0
2021/02/05 03:38:30 packer-provisioner-shell plugin: [INFO] 79725 bytes written for 'stderr'
2021/02/05 03:38:30 packer-provisioner-shell plugin: [INFO] 3585358 bytes written for 'stdout'
2021/02/05 03:38:30 packer-provisioner-shell plugin: [INFO] RPC client: Communicator ended with: 0
ESC[1;31m==> amazon-ebs:ESC[0m
```

**Comment by stitakis** [comment]
@michaelsauter any idea why the build is failing?

**Comment by clemensutschig** [comment]
@stitakis  - is there errors above the success logs?!

ESC[1;31m==> amazon-ebs: make: *** [test] Error 1ESC[0m
2021/02/08 03:24:44 packer-builder-amazon-ebs plugin: [ERROR] Remote command exited with '2': /tmp/script_1736.sh  --branch 3.x

**Comment by stitakis** [comment]
> @stitakis - is there errors above the success logs?!
It seems to be fine the success logs... 
I did some more research the error happens in the between this line https://github.com/opendevstack/ods-core/blob/e11cf4767c08001aa4e62d4825de7b1ec058538e/ods-devenv/scripts/deploy.sh#L1788 and the following one.

is possible to increase the logging level of the `test-quickstarter`?

**Comment by michaelsauter** [comment]
I think as @clemensutschig mentions, the error must be way before ...

**Comment by stitakis** [comment]
@michaelsauter @clemensutschig I found this error in the log file (somehow I missed it yesterday):
```
[0;32m    amazon-ebs: error: build error: The command '/bin/sh -c apt-key adv --fetch-keys http://archive.cloudera.com/cdh5/ubuntu/xenial/amd64/cdh/archive.key &&     echo 'deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/xenial/amd64/cdh xenial-cdh5 contrib' > /etc/apt/sources.list.d/cloudera.list' returned a non-zero code: 2
```
The ODS CI build for master is currently failing. The log file shows same error: https://github.com/opendevstack/ods-quickstarters/issues/540

**Comment by stitakis** [comment]
@michaelsauter @clemensutschig 
after a quick investigation... it looks like the domain archive.cloudera.com requires authentication (see https://community.cloudera.com/t5/Support-Questions/need-to-register-https-archive-cloudera-com/td-p/293344)... it looks to me that this worked in the past but since last weekend authentication was enabled to the whole cloudera domain. I haven't sought for this thou.
Since this is a duplicate of https://github.com/opendevstack/ods-quickstarters/issues/540 I'll close this issue here and continue investigation in other one.
