### ISSUE TITLE
SonarQube Postgres image is old (9.6) and doesn't exist in OpenShift 4.6

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#951]
See https://github.com/opendevstack/ods-core/blob/master/sonarqube/ocp-config/sonarqube.yml#L246

OpenShift Dedicated 4.6 has only `postgresql:9.6-el8`.

Besides, maybe better to update to something newer? But then we need to provide an upgrade path.

**Comment by gerardcl** [comment]
I propose shifting to "registry.redhat.io/rhscl/postgresql-12-rhel7"

**Comment by michaelsauter** [comment]
Agree. Right now thinking to make this configurable, and default to the image you mention. Then people do not have to update if they don't want to.

**Comment by michaelsauter** [comment]
Closed in #984.
