### ISSUE TITLE
add pub key parameter to buildbot

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#956]
Since the merge of this change #953 the packer provision configuration of CentOS2ODSBox is able to copy a public key to the authorized_keys.
To take advantage of this feature we need to extend the buildbot configuration to enables us to configure a public key.
This public key will be injected then in the AMI images. This will allow further automation.

**Comment by stitakis** [comment]
need to port this change to 3.x

**Comment by metmajer** [comment]
3.x is frozen, no more commits please, thank you!
