### ISSUE TITLE
[question]: Impact of Atlassians "Journey to cloud"

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-core#962]
As far as I know the OpenDevStack is at the moment based on the server products of the Atlassian tools. 

> **End of sale for new licenses**
> On February 2, 2021 PT, we will stop selling new licenses for our server products and cease new feature development in our server product line.
> 
> **Three years of maintenance**
> If you have an existing server license, you can continue to renew and receive maintenance and support for your licenses until February 2, 2024 PT.
> 
> **Updates to future pricing**
> On February 2, 2021 PT, we will increase the price of maintenance for existing server licenses to ensure the continued security and maintenance of our server platform.
>
> https://www.atlassian.com/migration/journey-to-cloud

What impact will it have on the OpenDevStack project?

**Comment by metmajer** [comment]
@SimonGolms can we handle this internally?
