### ISSUE TITLE
Sonar edition not set in Jenkins master DeploymentConfig

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-core#966]
**Describe the bug**
SonarQube won't analyze non-master branches unless the env. var `SONAR_EDITION` is set to `enterprise` in the  Jenkins master **DeploymentConfig** resource in OpenShift.

**Expected behavior**
Despite defining the `SONAR_EDITION=enterprise` line in the ods-core.env file, it is not set here: https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/deploy/jenkins-master.yml#L53-L56, which means the env. var is not being used in this case.

**Screenshots**

![image](https://user-images.githubusercontent.com/15997951/112460651-6c1a3b00-8d5f-11eb-80b6-c657f7b32b9b.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.1

**Comment by michaelsauter** [comment]
I'm closing this as per #967.
