### ISSUE TITLE
Jenkins build URL missing on existing Jenkins instance - set of build status not working

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#97]
@michaelsauter i gave this some thought and we should add the groovy script

**Comment by clemensutschig** [comment]
@michaelsauter  - 1.1? or 1.2?

**Comment by michaelsauter** [comment]
Let's leave this in 1.1 for now, and we'll see how we go. I'd say it is not a blocker for 1.1 but ideally in there ...

**Comment by clemensutschig** [comment]
BUILD_URL is required to set a proper build status in BitBucket, but it is not present. Normally, it is provided by Jenkins - please check your JenkinsUrl configuration.

**Comment by michaelsauter** [comment]
The file to copy is https://github.com/opendevstack/ods-core/blob/master/jenkins/master/configuration/init.groovy.d/url.groovy

**Comment by michaelsauter** [comment]
The file should be located under `/opt/openshift/configuration/init.groovy.d` and needs to be copied to `/var/lib/jenkins/init.groovy.d`.

**Comment by clemensutschig** [comment]
also see opendevstack/ods-jenkins-shared-library#87
