### ISSUE TITLE
APEX code analyzer plugin for SonarQube

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-core#975]
**Is your feature request related to a problem? Please describe.**
We would like for SonarQube to be able to scan Apex code

**Describe the solution you'd like**
Install APEX code analyzer plugin into SonarQube

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
We can submit a PR regarding this for master and 3.x branches

@metmajer @felipecruz91 @segator @borja44

**Comment by braisvq1996** [comment]
This plugin is a requirement for the Salesforce quickstarter

**Comment by clemensutschig** [comment]
this is waiting for 3.x correct?

**Comment by braisvq1996** [comment]
I am currently preparing the 3.x PR, in a moment I will create it
