### ISSUE TITLE
Simplify SonarQube config

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#986]
Instead of forcing auth via API in the configure script (https://github.com/opendevstack/ods-core/blob/master/sonarqube/configure.sh#L199-L205) we can do this in the container startup script: https://github.com/opendevstack/ods-core/blob/master/sonarqube/docker/run.sh.

FYI @felipecruz91

**Comment by slayer321** [comment]
Hey @michaelsauter, I am new to open source and will like to contribute to this project, can you guide me on what needs to be done.

**Comment by michaelsauter** [comment]
Hi! Basically removing the code from configure.sh and writing the setting in run.sh like the other settings. Once done, the tests in GitHub Actions should verify that the setting is still working as expected.

**Comment by gerardcl** [comment]
hi @michaelsauter is this still required? if yes, I would like to make it happen for ODS 4.2.0

**Comment by michaelsauter** [comment]
Yes we could do that change, see how we enforce auth in ods-pipeline: https://github.com/opendevstack/ods-pipeline/blob/master/scripts/sonarqube/Dockerfile#L3.
