### ISSUE TITLE
Missing jenkins service account in clean installation of ODS 4.x

### ISSUE THREAD

**Issue by albertpuente** [opendevstack/ods-core#987]
**Describe the bug**
The setup-ods-project.sh script requires having a service account with the name `jenkins` and does not create it in the process. The problem has been easily fixed in the installation by running `oc create sa jenkins`, but this command should perhaps be part of the installation script.

**To Reproduce**
Call `make install-ods-project`

**Expected behavior**
The installation executes line 66 of `setup-ods-project.sh` successfully.
`oc adm policy add-cluster-role-to-user self-provisioner system:serviceaccount:${NAMESPACE}:jenkins`

**Affected version (please complete the following information):**
 - OpenDevStack `master`.

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Warning: ServiceAccount 'jenkins' not found
```

**Comment by michaelsauter** [comment]
I think this is OK though as that script only creates a role binding. The actual service account is created later when Jenkins is created, see https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/deploy/jenkins-master.yml#L254-L262.

**Comment by albertpuente** [comment]
I see, so the actual role binding is defined regardless of the existence of the service account. And it only comes into effect later on once it is actually created.
