### ISSUE TITLE
SQ liveness probe missing

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#992]
There is no `livenessProbe` configured for SonarQube, only a readiness probe. The liveness probe should depend on a working database connection, we have seen this to be broken.

Readiness probe is defined here: https://github.com/opendevstack/ods-core/blob/master/sonarqube/ocp-config/sonarqube.yml#L314-L323

**Comment by gerardcl** [comment]
hi @michaelsauter I will take a look into this for ODS 4.2.0

**Comment by gerardcl** [comment]
thanks to @braisvq1996  to provide https://next.sonarqube.com/sonarqube/web_api <- will try to approach the fix via this API

**Comment by gerardcl** [comment]
we will need to add a section in the admin docs that when upgrading sonarqube one needs to disable the probes

**Comment by braisvq1996** [comment]
We can make use of this endpoint https://next.sonarqube.com/sonarqube/web_api/api/system/status as it does not need of any credential

![image](https://user-images.githubusercontent.com/26645694/184144741-d92f5ed5-33ab-439c-ba17-75e3cba2c12a.png)
