### ISSUE TITLE
Jenkins audit plugin

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-core#999]
**Is your feature request related to a problem? Please describe.**
Sometimes it’s difficult to tell who is doing what in Jenkins. Something happens, the Jenkins has/need a reset , a pipeline was deleted, and we do not know who did the change.

**Describe the solution you'd like**
Can we consider to install a plugin like this one?
https://plugins.jenkins.io/audit-trail/#documentation

Consider that an audit trail plugin will fill up the disk space much quicker. Jenkins instances are not prepared to store loads of log files so we need to be aware of this in case we install this plugin.

@metmajer @felipecruz91 @jssnull

**Comment by metmajer** [comment]
+1

**Comment by metmajer** [comment]
@braisvq1996 identify an owner, figure out a solution to the disk space problem, and do it, thanks

**Comment by metmajer** [comment]
@braisvq1996 since we're approaching the installation of ODS 4.x, was there any progress?

**Comment by braisvq1996** [comment]
@metmajer , I did not have much time to take a look into it.
We will try to allocate time for this

**Comment by braisvq1996** [comment]
@metmajer we have created a draft pr for this
